WOLF: ConstraintContainer Class Reference
ConstraintContainer Class Reference
#include <constraint_container.h>
Public Member Functions
ConstraintContainer (FeatureBase *_ftr_ptr, LandmarkContainer *_lmk_ptr, const unsigned int _corner, StateBase *_robotPPtr, StateOrientation *_robotOPtr, StateBase *_landmarkPPtr, StateOrientation *_landmarkOPtr)
virtual ~ConstraintContainer ()
LandmarkContainer * getLandmarkPtr ()
template<typename T >
bool operator() (const T *const _robotP, const T *const _robotO, const T *const _landmarkP, const T *const _landmarkO, T *_residuals) const
Public Member Functions inherited from ConstraintSparse< 3, 2, 1, 2, 1 >
state_block_sizes_vector_ ({BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, 0, 0, 0, 0, 0, 0})
state_block_ptr_vector_ ({_state0Ptr, _state1Ptr, _state2Ptr, _state3Ptr, _state4Ptr, _state5Ptr, _state6Ptr, _state7Ptr, _state8Ptr, _state9Ptr})
block_sizes_vector_ ({BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, 0, 0, 0, 0, 0, 0})
ConstraintSparse (FeatureBase *_ftr_ptr, ConstraintType _tp, StateBase *_state0Ptr, StateBase *_state1Ptr=nullptr, StateBase *_state2Ptr=nullptr, StateBase *_state3Ptr=nullptr, StateBase *_state4Ptr=nullptr, StateBase *_state5Ptr=nullptr, StateBase *_state6Ptr=nullptr, StateBase *_state7Ptr=nullptr, StateBase *_state8Ptr=nullptr, StateBase *_state9Ptr=nullptr)
Contructor with state pointer separated.
ConstraintSparse (WolfScalar *_measurementPtr, WolfScalar **_blockPtrArray)
virtual ~ConstraintSparse ()
Destructor.
virtual ~ConstraintSparse ()
virtual const std::vector
< WolfScalar * > getStateBlockPtrVector ()
Returns a vector of pointers to the state blocks.
virtual const std::vector
< StateBase * > getStatePtrVector () const
Returns a vector of pointers to the states.
virtual unsigned int getSize () const
Returns the constraint residual size.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
virtual ConstraintType getType () const =0
virtual const std::vector
< WolfScalar * > getBlockPtrVector ()
Public Member Functions inherited from ConstraintXBase
ConstraintXBase (WolfScalar *_measurement_ptr)
virtual ~ConstraintXBase ()
Public Member Functions inherited from ConstraintBase
ConstraintBase (FeatureBase *_ftr_ptr, ConstraintType _tp)
Constructor.
virtual ~ConstraintBase ()
Destructor.
ConstraintType getConstraintType () const
Returns the constraint type.
const Eigen::VectorXs & getMeasurement ()
Returns a pointer to the feature measurement.
FeatureBase * getFeaturePtr () const
Returns a pointer to its capture.
CaptureBase * getCapturePtr () const
Returns a pointer to its capture.
Public Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FeatureBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Static Public Attributes
static const unsigned int N_BLOCKS = 4
Static Public Attributes inherited from ConstraintSparse< 3, 2, 1, 2, 1 >
static const unsigned int measurementSize
static const unsigned int block0Size
static const unsigned int block1Size
static const unsigned int block2Size
static const unsigned int block3Size
static const unsigned int block4Size
static const unsigned int block5Size
static const unsigned int block6Size
static const unsigned int block7Size
static const unsigned int block8Size
static const unsigned int block9Size
Protected Attributes
LandmarkContainer * lmk_ptr_
unsigned int corner_
Protected Attributes inherited from ConstraintSparse< 3, 2, 1, 2, 1 >
std::vector< StateBase * > state_ptr_vector_
std::vector< unsigned int > state_block_sizes_vector_
std::vector< WolfScalar * > state_block_ptr_vector_
std::vector< unsigned int > block_sizes_vector_
Protected Attributes inherited from ConstraintXBase
WolfScalar * measurement_ptr_
Protected Attributes inherited from ConstraintBase
ConstraintType type_
const Eigen::VectorXs & measurement_
const Eigen::MatrixXs & measurement_covariance_
Protected Attributes inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef FeatureBase * UpperNodePtr
typedef NodeTerminus * LowerNodePtr
Protected Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 9 of file constraint_container.h.
Constructor & Destructor Documentation
ConstraintContainer::ConstraintContainer (FeatureBase * _ftr_ptr, LandmarkContainer * _lmk_ptr, const unsigned int _corner, StateBase * _robotPPtr, StateOrientation * _robotOPtr, StateBase * _landmarkPPtr, StateOrientation * _landmarkOPtr) inline
Definition at line 18 of file constraint_container.h.
References LandmarkBase::hit(), and lmk_ptr_.
virtual ConstraintContainer::~ConstraintContainer () inline virtual
Definition at line 27 of file constraint_container.h.
References lmk_ptr_, and LandmarkBase::unhit().
Member Function Documentation
LandmarkContainer* ConstraintContainer::getLandmarkPtr () inline
Definition at line 33 of file constraint_container.h.
References lmk_ptr_.
template<typename T > bool ConstraintContainer::operator() (const T *const _robotP, const T *const _robotO, const T *const _landmarkP, const T *const _landmarkO, T * _residuals) const inline
Definition at line 39 of file constraint_container.h.
References corner_, ConstraintBase::getCapturePtr(), LandmarkContainer::getCorner(), SensorBase::getOPtr(), SensorBase::getPPtr(), StateOrientation::getRotationMatrix(), CaptureBase::getSensorPtr(), StatePoint< SIZE >::getVector(), lmk_ptr_, ConstraintBase::measurement_, and ConstraintBase::measurement_covariance_.
Field Documentation
LandmarkContainer* ConstraintContainer::lmk_ptr_ protected
Definition at line 12 of file constraint_container.h.
Referenced by ConstraintContainer(), getLandmarkPtr(), operator()(), and ~ConstraintContainer().
unsigned int ConstraintContainer::corner_ protected
Definition at line 13 of file constraint_container.h.
Referenced by operator()().
const unsigned int ConstraintContainer::N_BLOCKS = 4 static
Definition at line 16 of file constraint_container.h.
The documentation for this class was generated from the following file:
constraint_container.h