WOLF: StateBase Class Reference
StateBase Class Reference abstract
#include <state_base.h>
Public Member Functions
StateBase (WolfScalar *_st_ptr)
Constructor with scalar pointer.
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
virtual ~StateBase ()
Destructor.
virtual WolfScalar * getPtr ()
Returns the pointer to the first element of the state.
virtual Eigen::Map< const
Eigen::VectorXs > getVector () const =0
Returns a (mapped) vector of the state unit.
virtual void setPtr (WolfScalar *_new_ptr)
Set the pointer of the first element of the state.
virtual StateType getStateType () const =0
Returns the parametrization of the state unit.
StateStatus getStateStatus () const
Returns the status of the state unit.
void setStateStatus (const StateStatus &_status)
Set the status of the state unit.
virtual unsigned int getStateSize () const =0
Returns the state unit size.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const =0
Prints all the elements of the state unit.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
WolfScalar * state_ptr_
StateStatus status_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 15 of file state_base.h.
Constructor & Destructor Documentation
StateBase::StateBase (WolfScalar * _st_ptr)
Constructor with scalar pointer
Parameters
_st_ptr is the pointer of the first element of the state unit
Definition at line 4 of file state_base.cpp.
StateBase::StateBase (Eigen::VectorXs & _st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit
Parameters
_st_remote is the whole state vector
_idx is the index of the first element of the state in the whole state vector
Definition at line 12 of file state_base.cpp.
StateBase::~StateBase () virtual
Destructor
Definition at line 20 of file state_base.cpp.
Member Function Documentation
WolfScalar * StateBase::getPtr () virtual
Returns the scalar pointer to the first element of the state
Definition at line 25 of file state_base.cpp.
References state_ptr_.
Referenced by WolfProblem::addCovarianceBlock(), SolverManager::addStateUnit(), CeresManager::addStateUnit(), CeresManager::computeCovariances(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::computeOdomCapture(), WolfProblem::getCovarianceBlock(), FrameBase::getState(), LandmarkContainer::LandmarkContainer(), WolfProblem::removeState(), FrameBase::setState(), and CeresManager::updateStateUnitStatus().
virtual Eigen::Map<const Eigen::VectorXs> StateBase::getVector () const pure virtual
Returns a (mapped) vector of the state unit
Implemented in StatePoint< SIZE >, StateQuaternion, StateTheta, StateComplexAngle, and StateOrientation.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::establishConstraintsMHTree().
void StateBase::setPtr (WolfScalar * _new_ptr) virtual
Set the pointer of the first element of the state
Definition at line 30 of file state_base.cpp.
References state_ptr_.
Referenced by WolfProblem::addState().
virtual StateType StateBase::getStateType () const pure virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implemented in StatePoint< SIZE >, StateQuaternion, StateTheta, and StateComplexAngle.
Referenced by SolverManager::addStateUnit(), CeresManager::addStateUnit(), CaptureTwist2D::computePrior(), and LandmarkContainer::LandmarkContainer().
StateStatus StateBase::getStateStatus () const
Returns the stateStatus (see wolf.h) of the state unit
Definition at line 35 of file state_base.cpp.
References status_.
Referenced by SolverManager::addStateUnit(), CeresManager::addStateUnit(), SolverQR::addStateUnit(), and CeresManager::updateStateUnitStatus().
void StateBase::setStateStatus (const StateStatus & _status)
Set tthe stateStatus (see wolf.h) of the state unit
Definition at line 40 of file state_base.cpp.
References ADD_PENDING, NodeBase::getPendingStatus(), NodeBase::setPendingStatus(), status_, and UPDATE_PENDING.
Referenced by FrameBase::fix(), and FrameBase::unfix().
virtual unsigned int StateBase::getStateSize () const pure virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implemented in StatePoint< SIZE >, StateQuaternion, StateTheta, and StateComplexAngle.
Referenced by WolfProblem::addCovarianceBlock(), WolfProblem::addState(), SolverQR::addStateUnit(), CeresManager::computeCovariances(), WolfProblem::getCovarianceBlock(), FrameBase::getState(), LandmarkContainer::LandmarkContainer(), and FrameBase::setState().
virtual void StateBase::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const pure virtual
Prints all the elements of the state unit
Reimplemented from NodeBase.
Implemented in StateQuaternion, StatePoint< SIZE >, StateTheta, and StateComplexAngle.
Referenced by FrameBase::printSelf().
Field Documentation
WolfScalar* StateBase::state_ptr_ protected
Definition at line 18 of file state_base.h.
Referenced by getPtr(), StateQuaternion::getQuaternion(), StateComplexAngle::getVector(), StateTheta::getVector(), StateQuaternion::getVector(), StatePoint< SIZE >::getVector(), StateComplexAngle::getYaw(), StateTheta::getYaw(), StateQuaternion::getYaw(), StateQuaternion::normalize(), StateComplexAngle::print(), StateTheta::print(), StatePoint< SIZE >::print(), StateQuaternion::print(), StateComplexAngle::rotationMatrix(), StateQuaternion::rotationMatrix(), and setPtr().
StateStatus StateBase::status_ protected
Definition at line 19 of file state_base.h.
Referenced by getStateStatus(), and setStateStatus().
The documentation for this class was generated from the following files:
state_base.h
state_base.cpp