WOLF: CaptureBase Class Reference
CaptureBase Class Reference abstract
#include <capture_base.h>
Public Member Functions
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data, const Eigen::MatrixXs &_data_covariance)
virtual ~CaptureBase ()
void linkToFrame (FrameBase *_frm_ptr)
Set link to Frame.
void addFeature (FeatureBase *_ft_ptr)
Adds a Feature to the down node list.
FrameBase * getFramePtr () const
Gets up_node_ptr_.
FeatureBaseList * getFeatureListPtr ()
Gets a pointer to feature list.
void getConstraintList (ConstraintBaseList &_ctr_list)
Fills the provided list with all constraints related to this capture.
TimeStamp getTimeStamp () const
SensorBase * getSensorPtr () const
SensorType getSensorType () const
void setTimeStamp (const TimeStamp &_ts)
void setTimeStampToNow ()
Eigen::VectorXs getData ()
Eigen::MatrixXs getDataCovariance ()
void setData (unsigned int _size, const WolfScalar *_data)
void setData (const Eigen::VectorXs &_data)
void setDataCovariance (const Eigen::MatrixXs &_data_cov)
virtual void processCapture ()
virtual Eigen::VectorXs computePrior (const TimeStamp &_now) const =0
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FrameBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
TimeStamp time_stamp_
Time stamp.
SensorBase * sensor_ptr_
Pointer to sensor.
Eigen::VectorXs data_
raw data
Eigen::MatrixXs data_covariance_
Noise of the capture.
Eigen::Vector3s sensor_pose_global_
Sensor pose in world frame: composition of the frame pose and the sensor pose. TODO: use state units.
Eigen::Vector3s inverse_sensor_pose_
World pose in the sensor frame: inverse of the global_pose_. TODO: use state units.
Protected Attributes inherited from NodeLinked< FrameBase, FeatureBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef FrameBase * UpperNodePtr
typedef FeatureBase * LowerNodePtr
Protected Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 20 of file capture_base.h.
Constructor & Destructor Documentation
CaptureBase::CaptureBase (const TimeStamp & _ts, SensorBase * _sensor_ptr)
Definition at line 3 of file capture_base.cpp.
CaptureBase::CaptureBase (const TimeStamp & _ts, SensorBase * _sensor_ptr, const Eigen::VectorXs & _data)
Definition at line 11 of file capture_base.cpp.
CaptureBase::CaptureBase (const TimeStamp & _ts, SensorBase * _sensor_ptr, const Eigen::VectorXs & _data, const Eigen::MatrixXs & _data_covariance)
Definition at line 20 of file capture_base.cpp.
CaptureBase::~CaptureBase () virtual
Definition at line 30 of file capture_base.cpp.
Member Function Documentation
void CaptureBase::linkToFrame (FrameBase * _frm_ptr)
Set link to Frame
Definition at line 35 of file capture_base.cpp.
References NodeLinked< FrameBase, FeatureBase >::linkToUpperNode().
void CaptureBase::addFeature (FeatureBase * _ft_ptr)
Adds a Feature to the down node list
Definition at line 41 of file capture_base.cpp.
References NodeLinked< FrameBase, FeatureBase >::addDownNode().
Referenced by CaptureLaser2D::createFeatures(), CaptureFix::processCapture(), CaptureGPSFix::processCapture(), CaptureTwist2D::processCapture(), and CaptureOdom2D::processCapture().
FrameBase * CaptureBase::getFramePtr () const
Gets up_node_ptr_, which is a pointer to the Frame owning of this Capture
Definition at line 47 of file capture_base.cpp.
References NodeLinked< FrameBase, FeatureBase >::upperNodePtr().
Referenced by CaptureTwist2D::addConstraints(), CaptureOdom2D::addConstraints(), CaptureLaser2D::computeExpectedFeature(), CaptureTwist2D::computePrior(), CaptureOdom2D::computePrior(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), CaptureLaser2D::createCornerLandmark(), CaptureLaser2D::establishConstraintsMHTree(), CaptureFix::processCapture(), and CaptureGPSFix::processCapture().
FeatureBaseList * CaptureBase::getFeatureListPtr ()
Gets a pointer to feature list
Definition at line 52 of file capture_base.cpp.
References NodeLinked< FrameBase, FeatureBase >::getDownNodeListPtr().
Referenced by CaptureTwist2D::addConstraints(), CaptureOdom2D::addConstraints(), CaptureLaser2D::establishConstraintsMHTree(), getConstraintList(), CaptureTwist2D::integrateCapture(), CaptureOdom2D::integrateCapture(), CaptureFix::processCapture(), CaptureGPSFix::processCapture(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
void CaptureBase::getConstraintList (ConstraintBaseList & _ctr_list)
Fills the provided list with all constraints related to this capture
Definition at line 57 of file capture_base.cpp.
References getFeatureListPtr().
TimeStamp CaptureBase::getTimeStamp () const
Definition at line 63 of file capture_base.cpp.
References time_stamp_.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::checkNewFrame(), CaptureRelative::getInitTimeStamp(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
SensorBase * CaptureBase::getSensorPtr () const
Definition at line 68 of file capture_base.cpp.
References sensor_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::establishConstraintsMHTree(), ConstraintContainer::operator()(), ConstraintCorner2DTheta::operator()(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
SensorType CaptureBase::getSensorType () const
Definition at line 73 of file capture_base.cpp.
References SensorBase::getSensorType(), and sensor_ptr_.
void CaptureBase::setTimeStamp (const TimeStamp & _ts)
Definition at line 78 of file capture_base.cpp.
References time_stamp_.
Referenced by CaptureRelative::setInitTimeStamp().
void CaptureBase::setTimeStampToNow ()
Definition at line 83 of file capture_base.cpp.
References TimeStamp::setToNow(), and time_stamp_.
Eigen::VectorXs CaptureBase::getData ()
Definition at line 88 of file capture_base.cpp.
References data_.
Referenced by CaptureTwist2D::integrateCapture(), and CaptureOdom2D::integrateCapture().
Eigen::MatrixXs CaptureBase::getDataCovariance ()
Definition at line 93 of file capture_base.cpp.
References data_covariance_.
Referenced by CaptureTwist2D::integrateCapture(), and CaptureOdom2D::integrateCapture().
void CaptureBase::setData (unsigned int _size, const WolfScalar * _data)
Definition at line 98 of file capture_base.cpp.
References data_.
void CaptureBase::setData (const Eigen::VectorXs & _data)
Definition at line 104 of file capture_base.cpp.
References data_.
void CaptureBase::setDataCovariance (const Eigen::MatrixXs & _data_cov)
Definition at line 109 of file capture_base.cpp.
References data_covariance_.
void CaptureBase::processCapture () virtual
Reimplemented in CaptureLaser2D, CaptureOdom2D, CaptureTwist2D, CaptureGPSFix, and CaptureFix.
Definition at line 114 of file capture_base.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
virtual Eigen::VectorXs CaptureBase::computePrior (const TimeStamp & _now) const pure virtual
Implemented in CaptureLaser2D, CaptureOdom2D, CaptureTwist2D, CaptureGPSFix, and CaptureFix.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
void CaptureBase::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from NodeLinked< FrameBase, FeatureBase >.
Definition at line 119 of file capture_base.cpp.
References NodeLinked< UpperType, LowerType >::printSelf().
Field Documentation
TimeStamp CaptureBase::time_stamp_ protected
Definition at line 23 of file capture_base.h.
Referenced by CaptureTwist2D::computePrior(), getTimeStamp(), CaptureOdom2D::interpolateCapture(), setTimeStamp(), and setTimeStampToNow().
SensorBase* CaptureBase::sensor_ptr_ protected
Definition at line 24 of file capture_base.h.
Referenced by CaptureLaser2D::CaptureLaser2D(), getSensorPtr(), getSensorType(), CaptureTwist2D::interpolateCapture(), and CaptureOdom2D::interpolateCapture().
Eigen::VectorXs CaptureBase::data_ protected
Definition at line 25 of file capture_base.h.
Referenced by CaptureFix::computePrior(), CaptureGPSFix::computePrior(), CaptureTwist2D::computePrior(), CaptureOdom2D::computePrior(), getData(), CaptureTwist2D::integrateCapture(), CaptureOdom2D::integrateCapture(), CaptureTwist2D::interpolateCapture(), CaptureOdom2D::interpolateCapture(), CaptureFix::processCapture(), CaptureGPSFix::processCapture(), CaptureTwist2D::processCapture(), CaptureOdom2D::processCapture(), and setData().
Eigen::MatrixXs CaptureBase::data_covariance_ protected
Definition at line 26 of file capture_base.h.
Referenced by CaptureOdom2D::CaptureOdom2D(), getDataCovariance(), CaptureTwist2D::integrateCapture(), CaptureOdom2D::integrateCapture(), CaptureTwist2D::interpolateCapture(), CaptureOdom2D::interpolateCapture(), CaptureFix::processCapture(), CaptureGPSFix::processCapture(), CaptureTwist2D::processCapture(), CaptureOdom2D::processCapture(), and setDataCovariance().
Eigen::Vector3s CaptureBase::sensor_pose_global_ protected
Definition at line 27 of file capture_base.h.
Eigen::Vector3s CaptureBase::inverse_sensor_pose_ protected
Definition at line 28 of file capture_base.h.
The documentation for this class was generated from the following files:
capture_base.h
capture_base.cpp