WOLF: SolverManager Class Reference
SolverManager Class Reference
solver manager for WOLF
#include <solver_manager.h>
Public Member Functions
SolverManager (ceres::Problem::Options _options)
~SolverManager ()
ceres::Solver::Summary solve (const ceres::Solver::Options &_ceres_options)
void update (const WolfProblemPtr _problem_ptr)
void addConstraint (ConstraintBase *_corr_ptr)
void removeConstraint (const unsigned int &_corr_idx)
void addStateUnit (StateBase *_st_ptr)
void removeAllStateUnits ()
void updateStateUnitStatus (StateBase *_st_ptr)
ceres::CostFunction * createCostFunction (ConstraintBase *_corrPtr)
Detailed Description
Definition at line 20 of file solver_manager.h.
Constructor & Destructor Documentation
SolverManager::SolverManager (ceres::Problem::Options _options)
Definition at line 3 of file solver_manager.cpp.
SolverManager::~SolverManager ()
Definition at line 8 of file solver_manager.cpp.
References removeAllStateUnits().
Member Function Documentation
void SolverManager::solve (const ceres::Solver::Options & _ceres_options)
Definition at line 13 of file solver_manager.cpp.
void SolverManager::update (const WolfProblemPtr _problem_ptr)
Definition at line 22 of file solver_manager.cpp.
References ADD_PENDING, addConstraint(), addStateUnit(), TrajectoryBase::getConstraintList(), WolfProblem::getRemovedStateListPtr(), WolfProblem::getStateListPtr(), WolfProblem::getTrajectoryPtr(), WolfProblem::isReallocated(), UPDATE_PENDING, and updateStateUnitStatus().
void SolverManager::addConstraint (ConstraintBase * _corr_ptr)
Definition at line 62 of file solver_manager.cpp.
References NOT_PENDING, and NodeBase::setPendingStatus().
Referenced by update().
void SolverManager::removeConstraint (const unsigned int & _corr_idx)
Definition at line 72 of file solver_manager.cpp.
void SolverManager::addStateUnit (StateBase * _st_ptr)
Definition at line 77 of file solver_manager.cpp.
References StateBase::getPtr(), StateBase::getStateStatus(), StateBase::getStateType(), NOT_PENDING, NodeBase::setPendingStatus(), ST_COMPLEX_ANGLE, ST_ESTIMATED, ST_POINT_1D, ST_POINT_2D, ST_POINT_3D, ST_THETA, and updateStateUnitStatus().
Referenced by update().
void SolverManager::removeAllStateUnits ()
Definition at line 124 of file solver_manager.cpp.
Referenced by ~SolverManager().
void SolverManager::updateStateUnitStatus (StateBase * _st_ptr)
Definition at line 134 of file solver_manager.cpp.
Referenced by addStateUnit(), and update().
ceres::CostFunction * SolverManager::createCostFunction (ConstraintBase * _corrPtr)
Definition at line 148 of file solver_manager.cpp.
References ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block0Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block1Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block2Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block3Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block4Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block5Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block6Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block7Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block8Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block9Size, CTR_CORNER_2D_THETA, CTR_GPS_FIX_2D, CTR_ODOM_2D_COMPLEX_ANGLE, CTR_ODOM_2D_THETA, ConstraintBase::getConstraintType(), and ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::measurementSize.
The documentation for this class was generated from the following files:
solver_manager.h
solver_manager.cpp