WOLF: Node Class Reference
Node Class Reference
Base class for Nodes.
#include <node.h>
Public Member Functions
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Print node information.
Protected Member Functions
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Detailed Description
Base class for all Nodes in the Wolf tree. It implements the ID factory.
Definition at line 19 of file node.h.
Constructor & Destructor Documentation
Node::Node (std::string _label) protected
Constructor from label
Definition at line 6 of file node.cpp.
Node::~Node () protected virtual
Default destructor
Definition at line 13 of file node.cpp.
Member Function Documentation
unsigned int Node::nodeId () const inline
Gets node ID. Inline function.
Definition at line 48 of file node.h.
Referenced by EpipolarConstraint::computeExpectation(), and CorrespondenceRelative::printSelf().
std::string Node::nodeLabel () const inline
Gets node label. Inline function.
Definition at line 58 of file node.h.
virtual void Node::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const inline virtual
Prints node information. Inine function.
Parameters
_ntabs number of tabulations to print at the left of the printed information
_ost output stream
Overload this function in derived classes to adapt the printed output to each object's relevant info.
Reimplemented in NodeLinked< UpperType, LowerType >, NodeLinked< NodeTerminus, NodeTerminus >, NodeLinked< Capture, CorrespondenceBase >, NodeLinked< Frame, FeatureBase >, NodeLinked< VehicleBase, NodeTerminus >, NodeLinked< VehicleBase, Capture >, NodeLinked< NodeTerminus, Frame >, and NodeLinked< FeatureBase, NodeTerminus >.
Definition at line 72 of file node.h.
void Node::printNTabs (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const inline protected
Prints a number of tabulations, i.e., "\t". Inline function.
Parameters
_ntabs number of tabulations to print
_ost output stream
Definition at line 86 of file node.h.
Referenced by Frame::printSelf(), CorrespondenceRelative::printSelf(), FeatureBase::printSelf(), CorrespondenceBase::printSelf(), NodeConstrainer< UpperType, LowerType >::printSelf(), and Capture::printSelf().
The documentation for this class was generated from the following files:
node.h
node.cpp