WOLF: StatePose Class Reference
StatePose Class Reference
Base class for pose states.
#include <state_pose.h>
Public Member Functions
StatePose ()
Default local constructor.
StatePose (unsigned int _size)
Local constructor from size.
StatePose (const Eigen::VectorXs &_x)
Local constructor from vector.
StatePose (const StatePose &_pose)
Local constructor from StatePose.
StatePose (unsigned int _size, Eigen::Vector3s &_p, Eigen::Quaternions &_q)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_x)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size, Eigen::Vector3s &_p, Eigen::Quaternions &_q)
virtual ~StatePose ()
virtual void setToOrigin ()
Set to origin.
void p (Eigen::Vector3s &_pos)
Eigen::Map< Eigen::Vector3s > & p ()
const Eigen::Map
< Eigen::Vector3s > & p () const
void q (Eigen::Quaternions &_quat)
Eigen::Map< Eigen::Quaternions > & q ()
const Eigen::Map
< Eigen::Quaternions > & q () const
virtual StatePose composeWithLocal (const StatePose &_local_pose) const
compose this pose with a local pose
virtual void composeWithLocal (const StatePose &_local_pose, StatePose &_return_pose) const
virtual void composeWithLocal (const StatePose &_local_pose)
virtual StatePose composeOnTopOf (const StatePose &_base_pose) const
compose this pose with a base pose
virtual void composeOnTopOf (const StatePose &_base_pose, StatePose &_return_pose) const
virtual void composeOnTopOf (const StatePose &_base_pose)
virtual StatePose composeRelativeTo (const StatePose &_reference_pose) const
compose poses
virtual void composeRelativeTo (const StatePose &_reference_pose, StatePose &_return_pose) const
virtual void composeRelativeTo (const StatePose &_reference_pose)
virtual StatePose inverse () const
inverse pose
void inverse (StatePose &_result) const
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Public Member Functions inherited from StateBase
StateBase (const unsigned int _size)
StateBase (const Eigen::VectorXs &_x)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateBase ()
Eigen::Map< Eigen::VectorXs > & x ()
const Eigen::Map
< Eigen::VectorXs > & x () const
void x (const Eigen::VectorXs &_x)
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
unsigned int size ()
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
A pose state is a state containing, at least, a position P and an orientation Q.
Derive from this class to include additional substates such as velocities or other possible things related to motion.
Orientation is represented with a quaternion.
It inherits StateRootBase, so it can be constructed as local or remote. P and Q parts are mapped over the StateRootBase map. The Q part is an Eigen Quaternion Map, i.e., Map < Quaternions >, so when it is returned it can be used as a standard Eigen Quaternion.
The class implements p() and q() accessors returning const and non-const references to the Maps, Map<VectorXs>& and Map<Quaternions>&.
The const references allow no-cost read access of P and Q directly on the remote storage vector pointed by the Map.
The non-const references allow no-cost manipulations of P and Q directly on the remote storage vector pointed by the Map.
Definition at line 35 of file state_pose.h.
Constructor & Destructor Documentation
StatePose::StatePose ()
Default local constructor. The pose is set to the origin and the rest of states to zero.
Definition at line 12 of file state_pose.cpp.
Referenced by composeOnTopOf(), composeRelativeTo(), and composeWithLocal().
StatePose::StatePose (unsigned int _size)
Local constructor from size
Parameters
_size dimension of the state vector
Definition at line 20 of file state_pose.cpp.
StatePose::StatePose (const Eigen::VectorXs & _x)
Local constructor from vector.
Parameters
_x the state vector
StatePose::StatePose (const StatePose & _pose)
Local constructor from StatePose.
Parameters
_pose the pose
Definition at line 35 of file state_pose.cpp.
References p(), and q().
StatePose::StatePose (unsigned int _size, Eigen::Vector3s & _p, Eigen::Quaternions & _q)
Local constructor from state vector
Parameters
_size dimension of the state vector
_p position
_q orientation quaternion (must be normalized)
NOTE: Enter a valid unity Quaternion. It is not normalized by the constructor.
Definition at line 44 of file state_pose.cpp.
References p(), and q().
StatePose::StatePose (Eigen::VectorXs & _storage, unsigned int _idx, unsigned int _size)
Remote constructor
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_size dimension of the state vector
Note: The state takes the values existing in the given storage vector.
Note: Enter a valid unity Quaternion. It is not normalized by the constructor.
StatePose::StatePose (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _x)
Remote constructor from vector
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_x the state vector.
Note: The state takes the values existing in the given storage vector.
Note: The Quaternion is not normalized by the constructor.
StatePose::StatePose (Eigen::VectorXs & _storage, unsigned int _idx, unsigned int _size, Eigen::Vector3s & _p, Eigen::Quaternions & _q)
Remote constructor from vectors
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_size dimension of the state vector
_p position
_q orientation quaternion (must be normalized by the caller)
StatePose::~StatePose () virtual
Destructor
Definition at line 77 of file state_pose.cpp.
Member Function Documentation
void StatePose::setToOrigin () inline virtual
Set state to the origin.
Sets the position to 0, the quaternion to Quaternions::Identity(), and the rest of the states to 0.
This class may be overloaded in case the states other than P, Q need a different origin than the default 0.
Definition at line 216 of file state_pose.h.
References StateRootBase::size(), and StateRootBase::state_estimated_map_.
void StatePose::p (Eigen::Vector3s & _pos) inline
Set position
Parameters
_pos position
Definition at line 232 of file state_pose.h.
Referenced by Wolf::composeFrames(), composeOnTopOf(), composeRelativeTo(), composeWithLocal(), EpipolarConstraint::computeExpectation(), inverse(), main(), and StatePose().
Eigen::Map< Eigen::Vector3s > & StatePose::p () inline
Get reference to position
Definition at line 227 of file state_pose.h.
Referenced by composeOnTopOf(), composeRelativeTo(), composeWithLocal(), inverse(), and StatePose().
const Eigen::Map< Eigen::Vector3s > & StatePose::p () const inline
Get reference to position
Definition at line 222 of file state_pose.h.
void StatePose::q (Eigen::Quaternions & _quat) inline
Set quaternion
Parameters
_quat quaternion
Definition at line 247 of file state_pose.h.
Referenced by composeOnTopOf(), composeRelativeTo(), composeWithLocal(), EpipolarConstraint::computeExpectation(), inverse(), main(), TransPinHole::precomputeConstants(), and StatePose().
Eigen::Map< Eigen::Quaternions > & StatePose::q () inline
Get reference to quaternion
Definition at line 242 of file state_pose.h.
Referenced by composeOnTopOf(), composeRelativeTo(), composeWithLocal(), inverse(), and StatePose().
const Eigen::Map< Eigen::Quaternions > & StatePose::q () const inline
Get reference to quaternion
Definition at line 237 of file state_pose.h.
StatePose StatePose::composeWithLocal (const StatePose & _local_pose) const inline virtual
Parameters
_local_pose local pose to compose with. Acts as local wrt this.
Returns
a composed pose, this * _other
Composes another pose locally on top of this.
Definition at line 252 of file state_pose.h.
References p(), q(), and StatePose().
void StatePose::composeWithLocal (const StatePose & _local_pose, StatePose & _return_pose) const inline virtual
Definition at line 273 of file state_pose.h.
References p(), and q().
void StatePose::composeWithLocal (const StatePose & _local_pose) inline virtual
Definition at line 291 of file state_pose.h.
References p(), and q().
StatePose StatePose::composeOnTopOf (const StatePose & _base_pose) const inline virtual
Parameters
_base_pose base pose to compose with. Acts as global or base wrt this.
Returns
a composed pose, _other * this
Composes this pose on top of another.
Definition at line 259 of file state_pose.h.
References p(), q(), and StatePose().
void StatePose::composeOnTopOf (const StatePose & _base_pose, StatePose & _return_pose) const inline virtual
Definition at line 279 of file state_pose.h.
References p(), and q().
void StatePose::composeOnTopOf (const StatePose & _base_pose) inline virtual
Definition at line 297 of file state_pose.h.
References p(), and q().
StatePose StatePose::composeRelativeTo (const StatePose & _reference_pose) const inline virtual
Parameters
_reference_pose the pose in relation to which we compose
Expresses this pose relative to another
Definition at line 266 of file state_pose.h.
References p(), q(), and StatePose().
void StatePose::composeRelativeTo (const StatePose & _reference_pose, StatePose & _return_pose) const inline virtual
Definition at line 285 of file state_pose.h.
References p(), and q().
void StatePose::composeRelativeTo (const StatePose & _reference_pose) inline virtual
Definition at line 303 of file state_pose.h.
References p(), and q().
StatePose StatePose::inverse () const inline virtual
Returns
a State pose whose pose is the inverse of this.
Definition at line 315 of file state_pose.h.
References p(), and q().
Referenced by Capture::precomputeGlobalPose().
void StatePose::inverse (StatePose & _result) const inline
Definition at line 309 of file state_pose.h.
References p(), and q().
void StatePose::remap (Eigen::VectorXs & _st_remote, const unsigned int _idx) inline virtual
Reimplemented from StateRootBase.
Reimplemented in StatePQV.
Definition at line 323 of file state_pose.h.
References StateRootBase::remap(), and StateRootBase::state_estimated_map_.
Referenced by StatePQV::remap().
The documentation for this class was generated from the following files:
state_pose.h
state_pose.cpp