WOLF: MapBase Class Reference
MapBase Class Reference
#include <map_base.h>
Public Member Functions
MapBase ()
Constructor.
~MapBase ()
Destructor.
virtual void addLandmark (LandmarkBase *_landmark_ptr)
Adds a landmark.
void removeLandmark (const LandmarkBaseIter &_landmark_iter)
Removes a landmark.
void removeLandmark (LandmarkBase *_landmark_ptr)
Removes a landmark.
LandmarkBaseList * getLandmarkListPtr ()
Returns Frame list.
Public Member Functions inherited from NodeLinked< WolfProblem, LandmarkBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const WolfProblem & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Additional Inherited Members
Public Types inherited from NodeLinked< WolfProblem, LandmarkBase >
typedef WolfProblem * UpperNodePtr
typedef LandmarkBase * LowerNodePtr
Protected Types inherited from NodeLinked< WolfProblem, LandmarkBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< WolfProblem, LandmarkBase >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from NodeLinked< WolfProblem, LandmarkBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 23 of file map_base.h.
Constructor & Destructor Documentation
MapBase::MapBase ()
Constructor
Definition at line 3 of file map_base.cpp.
MapBase::~MapBase ()
Destructor
Definition at line 9 of file map_base.cpp.
Member Function Documentation
void MapBase::addLandmark (LandmarkBase * _landmark_ptr) virtual
Adds a landmark
Definition at line 14 of file map_base.cpp.
References NodeLinked< WolfProblem, LandmarkBase >::addDownNode().
Referenced by CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::createCornerLandmark().
void MapBase::removeLandmark (const LandmarkBaseIter & _landmark_iter)
Removes a landmark
Definition at line 19 of file map_base.cpp.
References NodeLinked< WolfProblem, LandmarkBase >::removeDownNode().
Referenced by CaptureLaser2D::createContainerLandmark().
void MapBase::removeLandmark (LandmarkBase * _landmark_ptr)
Removes a landmark
Definition at line 24 of file map_base.cpp.
References NodeBase::nodeId(), and NodeLinked< WolfProblem, LandmarkBase >::removeDownNode().
LandmarkBaseList * MapBase::getLandmarkListPtr ()
Returns FrameBase list
Definition at line 29 of file map_base.cpp.
References NodeLinked< WolfProblem, LandmarkBase >::getDownNodeListPtr().
Referenced by CeresManager::computeCovariances(), CaptureLaser2D::establishConstraintsMHTree(), and CaptureLaser2D::fitNewContainer().
The documentation for this class was generated from the following files:
map_base.h
map_base.cpp