WOLF: LandmarkBase Class Reference
LandmarkBase Class Reference
#include <landmark_base.h>
Public Member Functions
LandmarkBase (const LandmarkType &_tp, StateBase *_p_ptr, StateOrientation *_o_ptr=nullptr, StateBase *_v_ptr=nullptr, StateBase *_w_ptr=nullptr)
Constructor with type, time stamp and the position state pointer.
virtual ~LandmarkBase ()
Constructor with type, time stamp and state list.
void setStatus (LandmarkStatus _st)
void hit (ConstraintBase *_ctr_ptr)
void unhit (ConstraintBase *_ctr_ptr)
void fix ()
void unfix ()
unsigned int getHits () const
std::list< ConstraintBase * > * getConstraints ()
StateBase * getPPtr () const
StateOrientation * getOPtr () const
StateBase * getVPtr () const
StateBase * getWPtr () const
void setPPtr (StateBase *_st_ptr)
void setOPtr (StateOrientation *_st_ptr)
void setVPtr (StateBase *_st_ptr)
void setWPtr (StateBase *_st_ptr)
void setDescriptor (const Eigen::VectorXs &_descriptor)
const Eigen::VectorXs & getDescriptor () const
WolfScalar getDescriptor (unsigned int _ii) const
Returns _ii component of descriptor vector.
const LandmarkType getType () const
Public Member Functions inherited from NodeLinked< MapBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const MapBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
LandmarkType type_
LandmarkStatus status_
TimeStamp stamp_
StateBase * p_ptr_
StateOrientation * o_ptr_
StateBase * v_ptr_
StateBase * w_ptr_
Eigen::VectorXs descriptor_
std::list< ConstraintBase * > constraints_list_
Protected Attributes inherited from NodeLinked< MapBase, NodeTerminus >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< MapBase, NodeTerminus >
typedef MapBase * UpperNodePtr
typedef NodeTerminus * LowerNodePtr
Protected Types inherited from NodeLinked< MapBase, NodeTerminus >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< MapBase, NodeTerminus >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 29 of file landmark_base.h.
Constructor & Destructor Documentation
LandmarkBase::LandmarkBase (const LandmarkType & _tp, StateBase * _p_ptr, StateOrientation * _o_ptr = nullptr, StateBase * _v_ptr = nullptr, StateBase * _w_ptr = nullptr)
Constructor with type, and state pointer
Parameters
_tp indicates landmark type.(types defined at wolf.h)
_p_ptr StateBase pointer to the position
_o_ptr StateOrientation pointer to the orientation (default: nullptr)
_v_ptr StateBase pointer to the velocity (default: nullptr)
_w_ptr StateBase pointer to the angular velocity (default: nullptr)
Definition at line 4 of file landmark_base.cpp.
virtual LandmarkBase::~LandmarkBase () virtual
Constructor with type and state pointer list
Parameters
_tp indicates frame type. Generally either REGULAR_FRAME or KEY_FRAME. (types defined at wolf.h)
_stp_list StateBase list of the landmark estimationDestructor
Destructor
Member Function Documentation
void LandmarkBase::setStatus (LandmarkStatus _st)
void LandmarkBase::hit (ConstraintBase * _ctr_ptr)
Referenced by ConstraintContainer::ConstraintContainer(), and ConstraintCorner2DTheta::ConstraintCorner2DTheta().
void LandmarkBase::unhit (ConstraintBase * _ctr_ptr)
Referenced by ConstraintContainer::~ConstraintContainer(), and ConstraintCorner2DTheta::~ConstraintCorner2DTheta().
void LandmarkBase::fix ()
void LandmarkBase::unfix ()
unsigned int LandmarkBase::getHits () const
std::list<ConstraintBase*>* LandmarkBase::getConstraints ()
Referenced by CaptureLaser2D::createContainerLandmark().
StateBase* LandmarkBase::getPPtr () const
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), CaptureLaser2D::createCornerLandmark(), CaptureLaser2D::establishConstraintsMHTree(), and LandmarkContainer::LandmarkContainer().
StateOrientation* LandmarkBase::getOPtr () const
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), CaptureLaser2D::createCornerLandmark(), and CaptureLaser2D::establishConstraintsMHTree().
StateBase* LandmarkBase::getVPtr () const
StateBase* LandmarkBase::getWPtr () const
void LandmarkBase::setPPtr (StateBase * _st_ptr)
void LandmarkBase::setOPtr (StateOrientation * _st_ptr)
void LandmarkBase::setVPtr (StateBase * _st_ptr)
void LandmarkBase::setWPtr (StateBase * _st_ptr)
void LandmarkBase::setDescriptor (const Eigen::VectorXs & _descriptor)
Referenced by LandmarkContainer::LandmarkContainer(), and LandmarkCorner2D::LandmarkCorner2D().
const Eigen::VectorXs& LandmarkBase::getDescriptor () const
WolfScalar LandmarkBase::getDescriptor (unsigned int _ii) const
Returns ii component of descriptor vector WARNING: To be fast, it does not check that index _ii is smaller than dimension.
const LandmarkType LandmarkBase::getType () const
Referenced by CaptureLaser2D::computeExpectedFeature(), and CaptureLaser2D::establishConstraintsMHTree().
Field Documentation
LandmarkType LandmarkBase::type_ protected
Definition at line 32 of file landmark_base.h.
LandmarkStatus LandmarkBase::status_ protected
Definition at line 33 of file landmark_base.h.
TimeStamp LandmarkBase::stamp_ protected
Definition at line 34 of file landmark_base.h.
StateBase* LandmarkBase::p_ptr_ protected
Definition at line 36 of file landmark_base.h.
StateOrientation* LandmarkBase::o_ptr_ protected
Definition at line 37 of file landmark_base.h.
StateBase* LandmarkBase::v_ptr_ protected
Definition at line 38 of file landmark_base.h.
StateBase* LandmarkBase::w_ptr_ protected
Definition at line 39 of file landmark_base.h.
Eigen::VectorXs LandmarkBase::descriptor_ protected
Definition at line 41 of file landmark_base.h.
Referenced by LandmarkCorner2D::getAperture(), LandmarkContainer::getLength(), and LandmarkContainer::getWidth().
std::list<ConstraintBase*> LandmarkBase::constraints_list_ protected
Definition at line 42 of file landmark_base.h.
The documentation for this class was generated from the following files:
landmark_base.h
landmark_base.cpp