WOLF: StateOrientation Class Reference
StateOrientation Class Reference abstract
#include <state_orientation.h>
Public Member Functions
StateOrientation (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StateOrientation (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StateOrientation ()
Destructor.
Eigen::Matrix3s getRotationMatrix () const
Returns the 3x3 rotation matrix of the orientation.
virtual void rotationMatrix (Eigen::Matrix3s &R) const =0
virtual WolfScalar getYaw () const =0
Returns the yaw angle.
virtual Eigen::Map< const
Eigen::VectorXs > getVector () const =0
Returns a (mapped) vector of the state unit.
Public Member Functions inherited from StateBase
StateBase (WolfScalar *_st_ptr)
Constructor with scalar pointer.
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
virtual ~StateBase ()
Destructor.
virtual WolfScalar * getPtr ()
Returns the pointer to the first element of the state.
virtual void setPtr (WolfScalar *_new_ptr)
Set the pointer of the first element of the state.
virtual StateType getStateType () const =0
Returns the parametrization of the state unit.
StateStatus getStateStatus () const
Returns the status of the state unit.
void setStateStatus (const StateStatus &_status)
Set the status of the state unit.
virtual unsigned int getStateSize () const =0
Returns the state unit size.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const =0
Prints all the elements of the state unit.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from StateBase
WolfScalar * state_ptr_
StateStatus status_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 14 of file state_orientation.h.
Constructor & Destructor Documentation
StateOrientation::StateOrientation (Eigen::VectorXs & _st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit
Parameters
_st_remote is the whole state vector
_idx is the index of the first element of the state in the whole state vector
Definition at line 4 of file state_orientation.cpp.
StateOrientation::StateOrientation (WolfScalar * _st_ptr)
Constructor with scalar pointer
Parameters
_st_ptr is the pointer of the first element of the state unit
Definition at line 11 of file state_orientation.cpp.
StateOrientation::~StateOrientation () virtual
Destructor
Definition at line 17 of file state_orientation.cpp.
Member Function Documentation
Eigen::Matrix3s StateOrientation::getRotationMatrix () const
Returns the 3x3 rotation matrix of the orientation
Definition at line 22 of file state_orientation.cpp.
References rotationMatrix().
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createCornerLandmark(), CaptureLaser2D::establishConstraintsMHTree(), main(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
virtual void StateOrientation::rotationMatrix (Eigen::Matrix3s & R) const pure virtual
Implemented in StateQuaternion, StateTheta, and StateComplexAngle.
Referenced by getRotationMatrix().
virtual WolfScalar StateOrientation::getYaw () const pure virtual
Returns the yaw angle
Implemented in StateQuaternion, StateTheta, and StateComplexAngle.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::establishConstraintsMHTree().
virtual Eigen::Map<const Eigen::VectorXs> StateOrientation::getVector () const pure virtual
Returns a (mapped) vector of the state unit
Implements StateBase.
Implemented in StateQuaternion, StateTheta, and StateComplexAngle.
The documentation for this class was generated from the following files:
state_orientation.h
state_orientation.cpp