WOLF: TransPinHole Class Reference
TransPinHole Class Reference
TransSensor involving two pin-hole sensors.
#include <trans_pin_hole.h>
Public Member Functions
TransPinHole (const CapturePtr &_capt_own_ptr, const CapturePtr &_capt_other_ptr)
virtual ~TransPinHole ()
virtual void precomputeConstants ()
Compute Essential and Fundamental matrices.
virtual void computeExpectation (const Eigen::VectorXs &_pixel_other, Eigen::VectorXs &_epi_line) const
Compute the expected epipolar line in the own camera, from the pixel measured in the other camera.
Public Member Functions inherited from TransSensor
TransSensor (const CapturePtr &_capt_own_ptr, const CapturePtr &_capt_other_ptr)
virtual ~TransSensor ()
void precomputePoseRelative ()
const StatePose & poseRelative () const
Additional Inherited Members
Protected Attributes inherited from TransSensor
CapturePtr capt_own_ptr_
Pointer to the Capture owning this.
CapturePtr capt_other_ptr_
Pointer to the other Capture.
StatePose pose_other_to_own_
The relative pose between captures, "other - to - this".
Detailed Description
Definition at line 16 of file trans_pin_hole.h.
Constructor & Destructor Documentation
TransPinHole::TransPinHole (const CapturePtr & _capt_own_ptr, const CapturePtr & _capt_other_ptr) inline
Definition at line 57 of file trans_pin_hole.h.
TransPinHole::~TransPinHole () inline virtual
Definition at line 65 of file trans_pin_hole.h.
Member Function Documentation
void TransPinHole::precomputeConstants () inline virtual
These matrices remain constant as long as the relative pose between captures does not change.
Implements TransSensor.
Definition at line 70 of file trans_pin_hole.h.
References PinHole::inverseIntrinsicMatrix(), TransSensor::poseRelative(), TransSensor::precomputePoseRelative(), StatePose::q(), and Wolf::skew().
void TransPinHole::computeExpectation (const Eigen::VectorXs & _pixel_other, Eigen::VectorXs & _epi_line) const inline virtual
Parameters
_pixel_other the pixel measured in the other camera
_epi_line the epipolar line in the own camera. This is the return value.
Implements TransSensor.
Definition at line 82 of file trans_pin_hole.h.
The documentation for this class was generated from the following file:
trans_pin_hole.h