WOLF: AssociationNode Class Reference
AssociationNode Class Reference
A node in the association decision tree.
#include <association_node.h>
Public Member Functions
AssociationNode (const unsigned int _det_idx, const unsigned int _tar_idx, const double _prob, AssociationNode *_un_ptr, bool _is_root=false)
Constructor.
virtual ~AssociationNode ()
Destructor.
bool isRoot () const
True if this is the root node.
bool isTerminus () const
True if this is node is terminus (no more nodes below)
unsigned int getDetectionIndex () const
Returns det_idx_.
unsigned int getTargetIndex () const
Returns tar_idx_.
double getNodeProb () const
Returns node_prob_.
void setNodeProb (double _np)
Sets node_prob_.
double getTreeProb () const
Returns tree_prob_.
AssociationNode * upNodePtr () const
Returns a copy of up_node_ptr_.
double computeNodeProb (const unsigned int _nd, const unsigned int _nt, const unsigned int _di, const unsigned int _tj, const Matrixx< double > &_stab) const
Computes node probability.
void normalizeNodeProbs ()
Normalizes node probabilities recursively.
double computeTreeProb (const double &_up_prob, std::list< AssociationNode * > &_tn_list)
Computes tree probabilities recursively.
void growTree (const unsigned int _nd, const unsigned int _nt, const unsigned int _det_i, const Matrixx< double > &_stab, std::vector< unsigned int > &_excluded)
Grows tree recursively.
void destroyTree ()
Destroys tree.
void printNode () const
Prints node info.
void printTree (const unsigned int _ntabs=0)
Prints the tree, by printing node info recursively.
Protected Attributes
bool is_root_
true if the node is root
unsigned int det_idx_
detection node index
unsigned int tar_idx_
target node index
double node_prob_
Node Probability. Normalized->Conditional Probability that detection associates to target. Non-normalizeNodeProbs->Product of likelihoods.
double tree_prob_
Tree Probability. Joint Probability from the root node up to this (product of node probabilities)
AssociationNode * up_node_ptr_
Pointer to up node.
std::list< AssociationNode > node_list_
List of nodes below of this in the association tree.
Detailed Description
A node in the association decision tree. A node associates a pair between a detection index and a target index, which is usually diferent from detection Id and target Id. Therefore, Id to index mapping has to be implemented outside of this class.
Definition at line 24 of file association_node.h.
Constructor & Destructor Documentation
AssociationNode::AssociationNode (const unsigned int _det_idx, const unsigned int _tar_idx, const double _prob, AssociationNode * _un_ptr, bool _is_root = false)
Constructor with arguments _det_idx and _tar_idx which indicates association of detection and target, with the probability _prob;
Definition at line 4 of file association_node.cpp.
References up_node_ptr_.
Referenced by growTree().
AssociationNode::~AssociationNode () virtual
Destructor
Definition at line 14 of file association_node.cpp.
Member Function Documentation
bool AssociationNode::isRoot () const
True if this is the root node, which is equivalent to check if up_node_ptr_ == NULL
Definition at line 19 of file association_node.cpp.
References is_root_.
Referenced by AssociationTree::solve().
bool AssociationNode::isTerminus () const
True if this is node is terminus (no more nodes below), which is equivalent to check node_list_.empty()
Definition at line 26 of file association_node.cpp.
References node_list_.
Referenced by computeTreeProb(), and normalizeNodeProbs().
unsigned int AssociationNode::getDetectionIndex () const
Returns det_idx_
Definition at line 32 of file association_node.cpp.
References det_idx_.
Referenced by AssociationTree::solve().
unsigned int AssociationNode::getTargetIndex () const
Returns tar_idx_
Definition at line 37 of file association_node.cpp.
References tar_idx_.
Referenced by AssociationTree::solve().
double AssociationNode::getNodeProb () const
Returns node_prob_
Definition at line 42 of file association_node.cpp.
References node_prob_.
void AssociationNode::setNodeProb (double _np)
Sets node_prob_
Definition at line 47 of file association_node.cpp.
References node_prob_.
double AssociationNode::getTreeProb () const
Returns tree_prob_
Definition at line 52 of file association_node.cpp.
References tree_prob_.
AssociationNode * AssociationNode::upNodePtr () const
Returns a copy of up_node_ptr_
Definition at line 57 of file association_node.cpp.
References up_node_ptr_.
Referenced by AssociationTree::solve().
double AssociationNode::computeNodeProb (const unsigned int _nd, const unsigned int _nt, const unsigned int _di, const unsigned int _tj, const Matrixx< double > & _stab) const
Computes probability that detection_i associates to target_j, given the scores table _stab.
Parameters
_di detection index (not id)
_tj target index (not id)
_stab score table Returns the probability. Nodes require computing other ij probs to decide if they continue growing or not at function growTree().
Definition at line 64 of file association_node.cpp.
Referenced by growTree().
void AssociationNode::normalizeNodeProbs ()
Normalizes node probabilities recursively. All node probs of node_list_ should sum 1
Definition at line 109 of file association_node.cpp.
References isTerminus(), and node_list_.
Referenced by AssociationTree::normalizeTree().
double AssociationNode::computeTreeProb (const double & _up_prob, std::list< AssociationNode * > & _tn_list)
Computes tree probabilities recursively, while setting tree_prob_ data member Updates the terminus node list, passed as second parameter, with all nodes that are terminus
Parameters
_up_prob probability of upper node
_tn_list List of terminus nodes. Filled with terminus nodes, while recurisve computing tree
Definition at line 125 of file association_node.cpp.
References isTerminus(), node_list_, node_prob_, and tree_prob_.
Referenced by AssociationTree::computeTree().
void AssociationNode::growTree (const unsigned int _nd, const unsigned int _nt, const unsigned int _det_i, const Matrixx< double > & _stab, std::vector< unsigned int > & _excluded)
Grows tree recursively according the association probability table provided
Parameters
_det_i detection index
_p_tab table of association probabilities between detections and targets
_ex_vec vector of target index for which the tree should not continue growing
Definition at line 145 of file association_node.cpp.
References AssociationNode(), computeNodeProb(), node_list_, and PROB_ZERO_.
Referenced by AssociationTree::growTree().
void AssociationNode::destroyTree ()
Recursively destroys tree
Definition at line 174 of file association_node.cpp.
References node_list_.
Referenced by AssociationTree::reset().
void AssociationNode::printNode () const
Prints node info
Definition at line 179 of file association_node.cpp.
References det_idx_, node_prob_, tar_idx_, and tree_prob_.
Referenced by printTree().
void AssociationNode::printTree (const unsigned int _ntabs = 0)
Prints the tree, by printing node info recursively
Parameters
_ntabs Number of tabulators before printing. Useful for recursively print a whole tree
TODO: This function should be const, but we run recursively with an iterator over the node_list_ and compiler claims saying it can't return a const iterator.
Definition at line 185 of file association_node.cpp.
References node_list_, and printNode().
Referenced by AssociationTree::printTree().
Field Documentation
bool AssociationNode::is_root_ protected
Definition at line 27 of file association_node.h.
Referenced by isRoot().
unsigned int AssociationNode::det_idx_ protected
Definition at line 28 of file association_node.h.
Referenced by getDetectionIndex(), and printNode().
unsigned int AssociationNode::tar_idx_ protected
Definition at line 29 of file association_node.h.
Referenced by getTargetIndex(), and printNode().
double AssociationNode::node_prob_ protected
Definition at line 30 of file association_node.h.
Referenced by computeTreeProb(), getNodeProb(), printNode(), and setNodeProb().
double AssociationNode::tree_prob_ protected
Definition at line 31 of file association_node.h.
Referenced by computeTreeProb(), getTreeProb(), and printNode().
AssociationNode* AssociationNode::up_node_ptr_ protected
Definition at line 32 of file association_node.h.
Referenced by AssociationNode(), and upNodePtr().
std::list<AssociationNode> AssociationNode::node_list_ protected
Definition at line 33 of file association_node.h.
Referenced by computeTreeProb(), destroyTree(), growTree(), isTerminus(), normalizeNodeProbs(), and printTree().
The documentation for this class was generated from the following files:
association_node.h
association_node.cpp