WOLF: NodeBase Class Reference
NodeBase Class Reference
Base class for Nodes.
#include <node_base.h>
Public Member Functions
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Print node information.
Protected Member Functions
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Base class for all Nodes in the Wolf tree. It implements the ID factory.
Definition at line 15 of file node_base.h.
Constructor & Destructor Documentation
NodeBase::NodeBase (std::string _label, bool _verbose = false)
Constructor from label
Definition at line 6 of file node_base.cpp.
References label_, node_id_, and verbose_.
NodeBase::~NodeBase () virtual
Default destructor
Definition at line 15 of file node_base.cpp.
Member Function Documentation
unsigned int NodeBase::nodeId () const
Gets node ID. Inline function.
Definition at line 20 of file node_base.cpp.
References node_id_.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), SolverQR::addConstraint(), SolverQR::addStateUnit(), StateComplexAngle::print(), StateTheta::print(), StatePoint< SIZE >::print(), StateQuaternion::print(), WolfProblem::printLower(), WolfProblem::printSelf(), MapBase::removeLandmark(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
std::string NodeBase::nodeLabel () const
Gets node label. Inline function.
Definition at line 25 of file node_base.cpp.
References label_.
Referenced by StateComplexAngle::print(), StateTheta::print(), StatePoint< SIZE >::print(), StateQuaternion::print(), and WolfProblem::printSelf().
PendingStatus NodeBase::getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
Definition at line 30 of file node_base.cpp.
References node_pending_.
Referenced by StateBase::setStateStatus().
void NodeBase::setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Definition at line 35 of file node_base.cpp.
References node_pending_.
Referenced by SolverManager::addConstraint(), CeresManager::addConstraint(), SolverQR::addConstraint(), SolverManager::addStateUnit(), CeresManager::addStateUnit(), SolverQR::addStateUnit(), StateBase::setStateStatus(), and CeresManager::updateStateUnitStatus().
void NodeBase::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints node information. Inine function.
Parameters
_ntabs number of tabulations to print at the left of the printed information
_ost output stream
Overload this function in derived classes to adapt the printed output to each object's relevant info.
Reimplemented in ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >, ConstraintSparse< 2, 2 >, ConstraintSparse< 3, 2, 1 >, ConstraintSparse< 3, 2, 1, 2, 1, 2, 1 >, ConstraintSparse< 2, 2, 2, 2, 2 >, ConstraintSparse< 2, 2, 1, 2, 1 >, ConstraintSparse< 3, 2, 2, 2, 2 >, ConstraintSparse< 3, 2, 1, 2, 1 >, WolfProblem, NodeLinked< UpperType, LowerType >, NodeLinked< NodeTerminus, FrameBaseX >, NodeLinked< FrameBase, FeatureBase >, NodeLinked< CaptureBase, ConstraintBase >, NodeLinked< WolfProblem, FrameBase >, NodeLinked< TrajectoryBaseX, CaptureBaseX >, NodeLinked< FeatureBaseX, NodeTerminus >, NodeLinked< WolfProblem, LandmarkBase >, NodeLinked< CaptureBaseX, CorrespondenceBaseX >, NodeLinked< FeatureBase, NodeTerminus >, NodeLinked< FrameBaseX, FeatureBaseX >, NodeLinked< MapBase, NodeTerminus >, NodeLinked< TrajectoryBase, CaptureBase >, StateQuaternion, StateBase, StatePoint< SIZE >, StateTheta, and StateComplexAngle.
Definition at line 40 of file node_base.cpp.
References label_, and node_id_.
void NodeBase::printTabs (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected
Prints a number of tabulations, i.e., "\t". Inline function.
Parameters
_ntabs number of tabulations to print
_ost output stream
Definition at line 45 of file node_base.cpp.
Referenced by StateComplexAngle::print(), StateTheta::print(), StatePoint< SIZE >::print(), StateQuaternion::print(), ConstraintSparse< 3, 2, 1, 2, 1 >::print(), WolfProblem::printLower(), FeatureBase::printSelf(), FrameBase::printSelf(), and WolfProblem::printSelf().
Field Documentation
std::string NodeBase::label_ protected
Definition at line 18 of file node_base.h.
Referenced by NodeBase(), nodeLabel(), and print().
unsigned int NodeBase::node_id_ protected
Definition at line 19 of file node_base.h.
Referenced by FrameBase::getNextFrame(), FrameBase::getPreviousFrame(), NodeBase(), nodeId(), and print().
unsigned int NodeBase::node_id_count_ = 0 static protected
Definition at line 20 of file node_base.h.
PendingStatus NodeBase::node_pending_ protected
Definition at line 21 of file node_base.h.
Referenced by getPendingStatus(), and setPendingStatus().
bool NodeBase::verbose_ protected
Definition at line 22 of file node_base.h.
Referenced by NodeBase().
The documentation for this class was generated from the following files:
node_base.h
node_base.cpp