WOLF: StateIMU Class Reference
StateIMU Class Reference
Class for IMU bias states.
#include <state_imu.h>
Public Member Functions
StateIMU ()
StateIMU (Eigen::VectorXs &_x)
StateIMU (Eigen::Vector3s &_abias, Eigen::Vector3s &_wbias)
StateIMU (Eigen::VectorXs &_storage, unsigned int _idx)
StateIMU (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_x)
StateIMU (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::Vector3s &_abias, Eigen::Vector3s &_wbias)
virtual ~StateIMU ()
void ab (Eigen::Vector3s &_abias)
Eigen::Map< Eigen::Vector3s > & ab ()
void wb (Eigen::Vector3s &_wbias)
Eigen::Map< Eigen::Vector3s > & wb ()
Public Member Functions inherited from StateBase
StateBase (const unsigned int _size)
StateBase (const Eigen::VectorXs &_x)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateBase ()
Eigen::Map< Eigen::VectorXs > & x ()
const Eigen::Map
< Eigen::VectorXs > & x () const
void x (const Eigen::VectorXs &_x)
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
unsigned int size ()
Static Public Attributes
static const unsigned int SIZE_ = 6
Size of the IMU bias state.
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Definition at line 17 of file state_imu.h.
Constructor & Destructor Documentation
StateIMU::StateIMU ()
Default local constructor
Definition at line 12 of file state_imu.cpp.
StateIMU::StateIMU (Eigen::VectorXs & _x)
Local constructor from vector
Parameters
_x the state vector
StateIMU::StateIMU (Eigen::Vector3s & _abias, Eigen::Vector3s & _wbias)
Local constructor from vectors
Parameters
_abias the accelerometer bias
_wbias the gyrometer bias
Definition at line 26 of file state_imu.cpp.
References ab(), and wb().
StateIMU::StateIMU (Eigen::VectorXs & _storage, unsigned int _idx)
Remote constructor
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
StateIMU::StateIMU (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _x)
Remote constructor from vector
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_x the state vector
StateIMU::StateIMU (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::Vector3s & _abias, Eigen::Vector3s & _wbias)
Remote constructor from vectors
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_abias the accelerometer bias
_wbias the gyrometer bias
StateIMU::~StateIMU () virtual
Destructor
Definition at line 60 of file state_imu.cpp.
Member Function Documentation
void StateIMU::ab (Eigen::Vector3s & _abias) inline
Set acc bias
Parameters
_abias acc bias
Definition at line 112 of file state_imu.h.
Eigen::Map< Eigen::Vector3s > & StateIMU::ab () inline
Get reference to acc bias
Definition at line 107 of file state_imu.h.
Referenced by StateIMU().
void StateIMU::wb (Eigen::Vector3s & _wbias) inline
Set gyro bias
Parameters
_wbias gyro bias
Definition at line 122 of file state_imu.h.
Eigen::Map< Eigen::Vector3s > & StateIMU::wb () inline
Get reference to gyro bias
Definition at line 117 of file state_imu.h.
Referenced by StateIMU().
Field Documentation
const unsigned int StateIMU::SIZE_ = 6 static
Definition at line 20 of file state_imu.h.
The documentation for this class was generated from the following files:
state_imu.h
state_imu.cpp