WOLF: StatePoint< SIZE > Class Template Reference
StatePoint< SIZE > Class Template Reference
#include <state_point.h>
Public Member Functions
StatePoint (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StatePoint (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StatePoint ()
Destructor.
virtual StateType getStateType () const
Returns the parametrization of the state unit.
virtual unsigned int getStateSize () const
Returns the state unit size.
virtual Eigen::Map< const
Eigen::VectorXs > getVector () const
Returns the point in a (mapped) vector.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints all the elements of the state unit.
Public Member Functions inherited from StateBase
StateBase (WolfScalar *_st_ptr)
Constructor with scalar pointer.
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
virtual ~StateBase ()
Destructor.
virtual WolfScalar * getPtr ()
Returns the pointer to the first element of the state.
virtual void setPtr (WolfScalar *_new_ptr)
Set the pointer of the first element of the state.
StateStatus getStateStatus () const
Returns the status of the state unit.
void setStateStatus (const StateStatus &_status)
Set the status of the state unit.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Static Public Attributes
static const unsigned int BLOCK_SIZE = SIZE
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from StateBase
WolfScalar * state_ptr_
StateStatus status_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
template<unsigned int SIZE>
class StatePoint< SIZE >
Definition at line 16 of file state_point.h.
Constructor & Destructor Documentation
template<unsigned int SIZE> StatePoint< SIZE >::StatePoint (Eigen::VectorXs & _st_remote, const unsigned int _idx) inline
Constructor with whole state storage and index where starts the state unit
Parameters
_st_remote is the whole state vector
_idx is the index of the first element of the state in the whole state vector
Definition at line 28 of file state_point.h.
template<unsigned int SIZE> StatePoint< SIZE >::StatePoint (WolfScalar * _st_ptr) inline
Constructor with scalar pointer
Parameters
_st_ptr is the pointer of the first element of the state unit
Definition at line 40 of file state_point.h.
template<unsigned int SIZE> virtual StatePoint< SIZE >::~StatePoint () inline virtual
Destructor
Definition at line 51 of file state_point.h.
Member Function Documentation
template<unsigned int SIZE> virtual StateType StatePoint< SIZE >::getStateType () const inline virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 61 of file state_point.h.
References StatePoint< SIZE >::BLOCK_SIZE, ST_POINT_1D, ST_POINT_2D, and ST_POINT_3D.
template<unsigned int SIZE> virtual unsigned int StatePoint< SIZE >::getStateSize () const inline virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 79 of file state_point.h.
References StatePoint< SIZE >::BLOCK_SIZE.
template<unsigned int SIZE> virtual Eigen::Map<const Eigen::VectorXs> StatePoint< SIZE >::getVector () const inline virtual
Returns the point in a (mapped) vector
Implements StateBase.
Definition at line 89 of file state_point.h.
References StatePoint< SIZE >::BLOCK_SIZE, and StateBase::state_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::establishConstraintsMHTree(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
template<unsigned int SIZE> virtual void StatePoint< SIZE >::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const inline virtual
Prints all the elements of the state unit
Implements StateBase.
Definition at line 99 of file state_point.h.
References StatePoint< SIZE >::BLOCK_SIZE, NodeBase::nodeId(), NodeBase::nodeLabel(), NodeBase::printTabs(), and StateBase::state_ptr_.
Field Documentation
template<unsigned int SIZE> const unsigned int StatePoint< SIZE >::BLOCK_SIZE = SIZE static
Definition at line 19 of file state_point.h.
Referenced by StatePoint< SIZE >::getStateSize(), StatePoint< SIZE >::getStateType(), StatePoint< SIZE >::getVector(), and StatePoint< SIZE >::print().
The documentation for this class was generated from the following file:
state_point.h