WOLF: AssociationTree Class Reference
AssociationTree Class Reference
The whole decision tree.
#include <association_tree.h>
Public Member Functions
AssociationTree ()
Constructor.
virtual ~AssociationTree ()
Destructor.
void reset ()
Reset.
void resize (const unsigned int _n_det, const unsigned int _n_tar)
Resizes the problem.
void growTree ()
Build tree from scores.
void computeTree ()
Computes tree probabilities.
void normalizeTree ()
Normalizes node probabilities.
void chooseBestTerminus (std::list< AssociationNode * >::iterator &_best_node)
choose best terminus node
void solve (std::map< unsigned int, unsigned int > &_pairs, std::vector< bool > &_associated_mask)
Gets tree decision.
void solve (std::vector< std::pair< unsigned int, unsigned int > > &_pairs, std::vector< bool > &_associated_mask)
Solves and sets decision pairs.
void printTree ()
Prints the tree.
void printTerminusNodes ()
Prints terminus_node_list_.
Public Member Functions inherited from AssociationSolver
AssociationSolver ()
Constructor.
virtual ~AssociationSolver ()
Destructor.
unsigned int numDetections ()
Returns num of detections nd_.
unsigned int numTargets ()
Returns num of actual targets nt_.
void setScore (const unsigned int _det_i, const unsigned int _tar_j, const double _m_ij)
Sets values to scores_ table.
void printScoreTable () const
Prints the score table.
Protected Attributes
AssociationNode root_
std::list< AssociationNode * > terminus_node_list_
Protected Attributes inherited from AssociationSolver
unsigned int nd_
unsigned int nt_
Matrixx< double > scores_
Detailed Description
The whole decision tree
Definition at line 22 of file association_tree.h.
Constructor & Destructor Documentation
AssociationTree::AssociationTree ()
Constructor
Definition at line 4 of file association_tree.cpp.
AssociationTree::~AssociationTree () virtual
Destructor
Definition at line 11 of file association_tree.cpp.
Member Function Documentation
void AssociationTree::reset () virtual
Deletes all nodes and clears scores and association list
Implements AssociationSolver.
Definition at line 16 of file association_tree.cpp.
References Matrixx< T >::clear(), AssociationNode::destroyTree(), AssociationSolver::nd_, AssociationSolver::nt_, root_, AssociationSolver::scores_, and terminus_node_list_.
void AssociationTree::resize (const unsigned int _n_det, const unsigned int _n_tar) virtual
Resizes the problem:
Parameters
_n_det num of detections
<em>n_tar num of targets Resizes the scores matrix which will allocate _n_det rows and _n_tar+1 columns to take into account void target
Implements AssociationSolver.
Definition at line 25 of file association_tree.cpp.
References AssociationSolver::nd_, AssociationSolver::nt_, Matrixx< T >::resize(), and AssociationSolver::scores_.
Referenced by CaptureLaser2D::establishConstraintsMHTree().
void AssociationTree::growTree ()
Build tree from scores
Definition at line 33 of file association_tree.cpp.
References AssociationNode::growTree(), AssociationSolver::nd_, AssociationSolver::nt_, root_, and AssociationSolver::scores_.
Referenced by solve().
void AssociationTree::computeTree ()
Computes tree probabilities
Definition at line 41 of file association_tree.cpp.
References AssociationNode::computeTreeProb(), AssociationSolver::nd_, root_, and terminus_node_list_.
Referenced by solve().
void AssociationTree::normalizeTree ()
Normalizes node probabilities
Definition at line 47 of file association_tree.cpp.
References AssociationNode::normalizeNodeProbs(), and root_.
Referenced by solve().
void AssociationTree::chooseBestTerminus (std::list< AssociationNode * >::iterator & _best_node)
Choose best terminus node based on the best tree probability
Parameters
<em>best_node a reference to an iterator to a list of pointers, where returned result is placed. At output, _best_node points the bets node in the terminus_node_list
Definition at line 52 of file association_tree.cpp.
References terminus_node_list_.
Referenced by solve().
void AssociationTree::solve (std::map< unsigned int, unsigned int > & _pairs, std::vector< bool > & _associated_mask)
Decides best hypothesis according tree computation made by computeTree() Return values are:
Parameters
_pairs Returned pairs: vector of pairs (d_i, t_j)
_unassoc Returned unassociated detections: vector of (d_i)
<em>associated_mask Resized to nd. Marks true at i if detection d_i has been associated, otherwise marks false
Definition at line 71 of file association_tree.cpp.
References chooseBestTerminus(), computeTree(), AssociationNode::getDetectionIndex(), AssociationNode::getTargetIndex(), growTree(), AssociationNode::isRoot(), AssociationSolver::nd_, normalizeTree(), AssociationSolver::nt_, terminus_node_list_, and AssociationNode::upNodePtr().
Referenced by CaptureLaser2D::establishConstraintsMHTree().
void AssociationTree::solve (std::vector< std::pair< unsigned int, unsigned int > > & _pairs, std::vector< bool > & _associated_mask) virtual
Solves and sets decision pairs Return values are:
Parameters
_pairs Returned pairs: vector of pairs (d_i, t_j)
_unassoc Returned unassociated detections: vector of (d_i)
<em>associated_mask Resized to nd. Marks true at i if detection d_i has been associated, otherwise marks false
Implements AssociationSolver.
Definition at line 117 of file association_tree.cpp.
References chooseBestTerminus(), computeTree(), AssociationNode::getDetectionIndex(), AssociationNode::getTargetIndex(), growTree(), AssociationNode::isRoot(), AssociationSolver::nd_, normalizeTree(), AssociationSolver::nt_, terminus_node_list_, and AssociationNode::upNodePtr().
void AssociationTree::printTree ()
Prints the tree
TODO: this function should be const. See comments on printTree() at association_node.h
Definition at line 163 of file association_tree.cpp.
References AssociationSolver::nd_, AssociationSolver::nt_, AssociationNode::printTree(), root_, AssociationSolver::scores_, and Matrixx< T >::size().
void AssociationTree::printTerminusNodes ()
Prints terminus_node_list_
Definition at line 172 of file association_tree.cpp.
References terminus_node_list_.
Field Documentation
AssociationNode AssociationTree::root_ protected
Definition at line 25 of file association_tree.h.
Referenced by computeTree(), growTree(), normalizeTree(), printTree(), and reset().
std::list<AssociationNode*> AssociationTree::terminus_node_list_ protected
Definition at line 26 of file association_tree.h.
Referenced by chooseBestTerminus(), computeTree(), printTerminusNodes(), reset(), and solve().
The documentation for this class was generated from the following files:
association_tree.h
association_tree.cpp