WOLF: WolfProblem Class Reference
WolfProblem Class Reference
Wolf problem node element in the Wolf Tree.
#include <wolf_problem.h>
Public Member Functions
WolfProblem ()
virtual ~WolfProblem ()
WolfScalar * getPrior ()
CorrespondenceCeresBase * getCorrespondence (const unsigned int _idx)
unsigned int getCorrespondencesSize ()
void resizeState (unsigned int _state_size)
void addCorrespondence (CorrespondenceCeresBase *_absCorrPtr)
void computePrior ()
void print ()
WolfProblem ()
virtual ~WolfProblem ()
WolfScalar * getPrior ()
AbsoluteCorrespondence * getCorrespondence (const unsigned int _idx)
unsigned int getCorrespondencesSize ()
void resizeState (unsigned int _state_size)
void addCorrespondence (AbsoluteCorrespondence *_absCorrPtr)
void inventMeasurements (std::default_random_engine &_generator)
void computePrior ()
void print ()
WolfProblem (unsigned int _size=1e3)
Constructor from state size.
WolfProblem (TrajectoryBase *_trajectory_ptr, MapBase *_map_ptr=nullptr, unsigned int _size=1e3)
Constructor from map and trajectory shared pointers.
virtual ~WolfProblem ()
Default destructor.
bool addState (StateBase *_new_state, const Eigen::VectorXs &_new_state_values)
Adds a new state unit to the state.
void addCovarianceBlock (StateBase *_state1, StateBase *_state2, const Eigen::MatrixXs &_cov)
Adds a new covariance block.
void getCovarianceBlock (StateBase *_state1, StateBase *_state2, Eigen::MatrixXs &_cov_block) const
Gets a covariance block.
void getCovarianceBlock (StateBase *_state1, StateBase *_state2, Eigen::MatrixXs &_cov, const int _row, const int _col) const
void removeState (StateBase *_state)
Removes a new state unit of the state.
WolfScalar * getStatePtr ()
Gets a pointer to the state first position.
WolfScalar * getNewStatePtr ()
Gets a pointer where a new state unit should be located.
const unsigned int getStateSize () const
Gets state size.
void addMap (MapBase *_map_ptr)
Sets the index of the last occupied position of the state.
void addTrajectory (TrajectoryBase *_Trajectory_ptr)
Adds a trajectory.
MapBase * getMapPtr ()
Gets a reference to map.
TrajectoryBase * getTrajectoryPtr ()
Gets a pointer to map.
FrameBase * getLastFramePtr ()
Returns a pointer to last Frame.
StateBaseList * getStateListPtr ()
Gets a pointer to the state units list.
std::list< WolfScalar * > * getRemovedStateListPtr ()
Gets a list of wolfscalar pointers contained by removed state units (in order to delete them in ceres)
const Eigen::VectorXs getState () const
Gets the state vector.
bool isReallocated () const
Gets if the state has been reallocated.
void reallocationDone ()
Turn off the reallocation flag.
virtual WolfProblem * getTop ()
get top node
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Member Functions
void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower nodes info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes
VectorXs state_
std::vector
< CorrespondenceCeresBase * > correspondences_
unsigned int state_size_
std::vector
< AbsoluteCorrespondence * > correspondences_
Eigen::VectorXs state_
Eigen::SparseMatrix< WolfScalar > covariance_
unsigned int state_idx_last_
NodeLocation location_
MapBase * map_ptr_
TrajectoryBase * trajectory_ptr_
StateBaseList state_list_
std::list< WolfScalar * > removed_state_ptr_list_
bool reallocated_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
A node has five main data members:
An unique ID to identify it over the whole Wolf Tree (inherited from Node)
A label indicating the node nature (inherited from Node)
An enum indicating tree location (see NodeLocation enum at wolf.h)
down_node_list_: A list of shared pointers to derived node objects, specified by the template parameter LowerType.
up_node_: A regular pointer to a derived node object, specified by the template parameter UpperType.
Definition at line 257 of file test_ceres_wrapper_jet_2_sensors.cpp.
Constructor & Destructor Documentation
WolfProblem::WolfProblem () inline
Definition at line 266 of file test_ceres_wrapper_jet_2_sensors.cpp.
WolfProblem::~WolfProblem () inline virtual
Definition at line 273 of file test_ceres_wrapper_jet_2_sensors.cpp.
WolfProblem::WolfProblem () inline
Definition at line 101 of file test_ceres_wrapper_jet_ind_block.cpp.
virtual WolfProblem::~WolfProblem () inline virtual
Definition at line 108 of file test_ceres_wrapper_jet_ind_block.cpp.
WolfProblem::WolfProblem (unsigned int _size = 1e3)
Constructor from state size
Definition at line 3 of file wolf_problem.cpp.
References NodeLinked< UpperType, LowerType >::linkToUpperNode(), map_ptr_, and trajectory_ptr_.
WolfProblem::WolfProblem (TrajectoryBase * _trajectory_ptr, MapBase * _map_ptr = nullptr, unsigned int _size = 1e3)
Constructor from map and trajectory shared pointers
Definition at line 19 of file wolf_problem.cpp.
References NodeLinked< UpperType, LowerType >::linkToUpperNode(), map_ptr_, and trajectory_ptr_.
virtual WolfProblem::~WolfProblem () virtual
Default destructor
Member Function Documentation
WolfScalar* WolfProblem::getPrior () inline
Definition at line 277 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
CorrespondenceCeresBase* WolfProblem::getCorrespondence (const unsigned int _idx) inline
Definition at line 282 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
unsigned int WolfProblem::getCorrespondencesSize () inline
Definition at line 288 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
void WolfProblem::resizeState (unsigned int _state_size) inline
Definition at line 293 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
void WolfProblem::addCorrespondence (CorrespondenceCeresBase * _absCorrPtr) inline
Definition at line 299 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
void WolfProblem::computePrior () inline
Definition at line 305 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
void WolfProblem::print () inline
Definition at line 310 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by main().
WolfScalar* WolfProblem::getPrior () inline
Definition at line 112 of file test_ceres_wrapper_jet_ind_block.cpp.
AbsoluteCorrespondence* WolfProblem::getCorrespondence (const unsigned int _idx) inline
Definition at line 117 of file test_ceres_wrapper_jet_ind_block.cpp.
unsigned int WolfProblem::getCorrespondencesSize () inline
Definition at line 122 of file test_ceres_wrapper_jet_ind_block.cpp.
void WolfProblem::resizeState (unsigned int _state_size) inline
Definition at line 127 of file test_ceres_wrapper_jet_ind_block.cpp.
void WolfProblem::addCorrespondence (AbsoluteCorrespondence * _absCorrPtr) inline
Definition at line 133 of file test_ceres_wrapper_jet_ind_block.cpp.
void WolfProblem::inventMeasurements (std::default_random_engine & _generator) inline
Definition at line 138 of file test_ceres_wrapper_jet_ind_block.cpp.
Referenced by main().
void WolfProblem::computePrior () inline
Definition at line 144 of file test_ceres_wrapper_jet_ind_block.cpp.
void WolfProblem::print () inline
Definition at line 149 of file test_ceres_wrapper_jet_ind_block.cpp.
bool WolfProblem::addState (StateBase * _new_state, const Eigen::VectorXs & _new_state_values)
Adds a new state unit to the state. Returns true if a remapping has been done.
Definition at line 39 of file wolf_problem.cpp.
References covariance_, StateBase::getStateSize(), reallocated_, StateBase::setPtr(), state_, state_idx_last_, and state_list_.
Referenced by CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::createCornerLandmark().
void WolfProblem::addCovarianceBlock (StateBase * _state1, StateBase * _state2, const Eigen::MatrixXs & _cov)
Adds a new covariance block
Definition at line 76 of file wolf_problem.cpp.
References covariance_, StateBase::getPtr(), StateBase::getStateSize(), state_, and state_idx_last_.
Referenced by CeresManager::computeCovariances(), CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::createCornerLandmark().
void WolfProblem::getCovarianceBlock (StateBase * _state1, StateBase * _state2, Eigen::MatrixXs & _cov_block) const
Gets a covariance block
Definition at line 104 of file wolf_problem.cpp.
References covariance_, StateBase::getPtr(), StateBase::getStateSize(), state_, and state_idx_last_.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::createContainerLandmark(), and CaptureLaser2D::createCornerLandmark().
void WolfProblem::getCovarianceBlock (StateBase * _state1, StateBase * _state2, Eigen::MatrixXs & _cov, const int _row, const int _col) const
Definition at line 129 of file wolf_problem.cpp.
References covariance_, StateBase::getPtr(), StateBase::getStateSize(), state_, and state_idx_last_.
void WolfProblem::removeState (StateBase * _state)
Removes a new state unit of the state
Definition at line 165 of file wolf_problem.cpp.
References StateBase::getPtr(), removed_state_ptr_list_, and state_list_.
Referenced by FrameBase::~FrameBase().
WolfScalar * WolfProblem::getStatePtr ()
Gets a pointer to the state first position
Definition at line 173 of file wolf_problem.cpp.
References state_.
WolfScalar * WolfProblem::getNewStatePtr ()
Gets a pointer where a new state unit should be located
Definition at line 178 of file wolf_problem.cpp.
References state_, and state_idx_last_.
const unsigned int WolfProblem::getStateSize () const
Gets state size
Definition at line 183 of file wolf_problem.cpp.
References state_idx_last_.
void WolfProblem::addMap (MapBase * _map_ptr)
Sets the index of the last occupied position of the stateAdds a map
Adds a map
Definition at line 188 of file wolf_problem.cpp.
References NodeLinked< UpperType, LowerType >::linkToUpperNode(), and map_ptr_.
void WolfProblem::addTrajectory (TrajectoryBase * _Trajectory_ptr)
Adds a trajectory
Definition at line 194 of file wolf_problem.cpp.
References NodeLinked< UpperType, LowerType >::linkToUpperNode(), and trajectory_ptr_.
MapBase * WolfProblem::getMapPtr ()
Gets a reference to mapGets a reference to Trajectory
Gets a reference to TrajectoryGets a pointer to map
Gets a pointer to map
Definition at line 200 of file wolf_problem.cpp.
References map_ptr_.
Referenced by CeresManager::computeCovariances(), CaptureLaser2D::createContainerLandmark(), CaptureLaser2D::createCornerLandmark(), CaptureLaser2D::establishConstraintsMHTree(), and CaptureLaser2D::fitNewContainer().
TrajectoryBase * WolfProblem::getTrajectoryPtr ()
Gets a pointer to map
Definition at line 205 of file wolf_problem.cpp.
References trajectory_ptr_.
Referenced by CeresManager::computeCovariances(), SolverManager::update(), CeresManager::update(), and SolverQR::update().
FrameBase * WolfProblem::getLastFramePtr ()
Returns a pointer to last Frame
Definition at line 210 of file wolf_problem.cpp.
References TrajectoryBase::getLastFramePtr(), and trajectory_ptr_.
StateBaseList * WolfProblem::getStateListPtr ()
Gets a pointer to the state units list
Definition at line 215 of file wolf_problem.cpp.
References state_list_.
Referenced by SolverManager::update(), CeresManager::update(), and SolverQR::update().
std::list< WolfScalar * > * WolfProblem::getRemovedStateListPtr ()
Gets a list of wolfscalar pointers contained by removed state units (in order to delete them in ceres)
Definition at line 220 of file wolf_problem.cpp.
References removed_state_ptr_list_.
Referenced by SolverManager::update(), CeresManager::update(), and SolverQR::update().
const Eigen::VectorXs WolfProblem::getState () const
Gets the state vector
Definition at line 238 of file wolf_problem.cpp.
References state_.
bool WolfProblem::isReallocated () const
Gets if the state has been reallocated
Definition at line 243 of file wolf_problem.cpp.
References reallocated_.
Referenced by SolverManager::update(), and CeresManager::update().
void WolfProblem::reallocationDone ()
Turn off the reallocation flag
Definition at line 249 of file wolf_problem.cpp.
References reallocated_.
Referenced by CeresManager::update().
WolfProblem * WolfProblem::getTop () virtual
Returns a pointer to this
Definition at line 254 of file wolf_problem.cpp.
Referenced by NodeLinked< UpperType, LowerType >::getTop().
void WolfProblem::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints node information.
Parameters
_ntabs number of tabulations to print at the left of the printed information
_ost output stream
Reimplemented from NodeBase.
Definition at line 225 of file wolf_problem.cpp.
References printLower(), and printSelf().
void WolfProblem::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Definition at line 231 of file wolf_problem.cpp.
References NodeBase::nodeId(), NodeBase::nodeLabel(), and NodeBase::printTabs().
Referenced by print().
void WolfProblem::printLower (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected
Prints recursively lower nodes info
Definition at line 259 of file wolf_problem.cpp.
References map_ptr_, NodeBase::nodeId(), NodeLinked< UpperType, LowerType >::print(), NodeBase::printTabs(), and trajectory_ptr_.
Referenced by print().
Field Documentation
VectorXs WolfProblem::state_ protected
Definition at line 260 of file test_ceres_wrapper_jet_2_sensors.cpp.
Referenced by addCovarianceBlock(), addState(), getCovarianceBlock(), getNewStatePtr(), getState(), and getStatePtr().
std::vector<CorrespondenceCeresBase*> WolfProblem::correspondences_ protected
Definition at line 261 of file test_ceres_wrapper_jet_2_sensors.cpp.
unsigned int WolfProblem::state_size_ protected
Definition at line 263 of file test_ceres_wrapper_jet_2_sensors.cpp.
std::vector<AbsoluteCorrespondence*> WolfProblem::correspondences_ protected
Definition at line 96 of file test_ceres_wrapper_jet_ind_block.cpp.
Eigen::VectorXs WolfProblem::state_ protected
Definition at line 23 of file wolf_problem.h.
Eigen::SparseMatrix<WolfScalar> WolfProblem::covariance_ protected
Definition at line 24 of file wolf_problem.h.
Referenced by addCovarianceBlock(), addState(), and getCovarianceBlock().
unsigned int WolfProblem::state_idx_last_ protected
Definition at line 25 of file wolf_problem.h.
Referenced by addCovarianceBlock(), addState(), getCovarianceBlock(), getNewStatePtr(), and getStateSize().
NodeLocation WolfProblem::location_ protected
Definition at line 26 of file wolf_problem.h.
MapBase* WolfProblem::map_ptr_ protected
Definition at line 27 of file wolf_problem.h.
Referenced by addMap(), getMapPtr(), printLower(), and WolfProblem().
TrajectoryBase* WolfProblem::trajectory_ptr_ protected
Definition at line 28 of file wolf_problem.h.
Referenced by addTrajectory(), getLastFramePtr(), getTrajectoryPtr(), printLower(), and WolfProblem().
StateBaseList WolfProblem::state_list_ protected
Definition at line 30 of file wolf_problem.h.
Referenced by addState(), getStateListPtr(), and removeState().
std::list<WolfScalar*> WolfProblem::removed_state_ptr_list_ protected
Definition at line 31 of file wolf_problem.h.
Referenced by getRemovedStateListPtr(), and removeState().
bool WolfProblem::reallocated_ protected
Definition at line 32 of file wolf_problem.h.
Referenced by addState(), isReallocated(), and reallocationDone().
The documentation for this class was generated from the following files:
test_ceres_wrapper_jet_2_sensors.cpp
test_ceres_wrapper_jet_ind_block.cpp
wolf_problem.h
wolf_problem.cpp