WOLF: CeresManager Class Reference
CeresManager Class Reference
Ceres manager for WOLF.
#include <ceres_manager.h>
Public Member Functions
CeresManager (ceres::Problem::Options _options)
~CeresManager ()
ceres::Solver::Summary solve (const ceres::Solver::Options &_ceres_options)
void computeCovariances (WolfProblem *_problem_ptr)
void update (const WolfProblemPtr _problem_ptr)
void addConstraint (ConstraintBase *_corr_ptr)
void removeConstraint (const unsigned int &_corr_idx)
void addStateUnit (StateBase *_st_ptr)
void removeAllStateUnits ()
void updateStateUnitStatus (StateBase *_st_ptr)
ceres::CostFunction * createCostFunction (ConstraintBase *_corrPtr)
CeresManager (ceres::Problem *_ceres_problem)
~CeresManager ()
ceres::Solver::Summary solve (const ceres::Solver::Options &_ceres_options)
void addConstraints (std::queue< ConstraintXBase * > &_new_constraints)
void removeConstraints ()
void addConstraint (ConstraintXBase *_corr_ptr)
void addStateUnits (std::queue< StateBase * > &_new_state_units)
void removeStateUnit (WolfScalar *_st_ptr)
void addStateUnit (StateBase *_st_ptr)
ceres::CostFunction * createCostFunction (ConstraintXBase *_corrPtr)
Protected Attributes
ceres::Problem * ceres_problem_
ceres::Covariance * covariance_
std::vector< std::pair
< ceres::ResidualBlockId,
ConstraintXBase * > > constraint_list_
Detailed Description
Definition at line 30 of file ceres_manager.h.
Constructor & Destructor Documentation
CeresManager::CeresManager (ceres::Problem::Options _options)
Definition at line 3 of file ceres_manager.cpp.
References covariance_.
CeresManager::~CeresManager ()
Definition at line 13 of file ceres_manager.cpp.
References ceres_problem_, covariance_, and removeAllStateUnits().
CeresManager::CeresManager (ceres::Problem * _ceres_problem) inline
Definition at line 482 of file test_ceres_manager.cpp.
CeresManager::~CeresManager () inline
Definition at line 487 of file test_ceres_manager.cpp.
Member Function Documentation
ceres::Solver::Summary CeresManager::solve (const ceres::Solver::Options & _ceres_options)
Definition at line 24 of file ceres_manager.cpp.
References ceres_problem_.
Referenced by main().
void CeresManager::computeCovariances (WolfProblem * _problem_ptr)
Definition at line 39 of file ceres_manager.cpp.
References WolfProblem::addCovarianceBlock(), ceres_problem_, covariance_, TrajectoryBase::getFrameListPtr(), MapBase::getLandmarkListPtr(), WolfProblem::getMapPtr(), StateBase::getPtr(), StateBase::getStateSize(), and WolfProblem::getTrajectoryPtr().
Referenced by main().
void CeresManager::update (const WolfProblemPtr _problem_ptr)
Definition at line 134 of file ceres_manager.cpp.
References ADD_PENDING, addConstraint(), addStateUnit(), ceres_problem_, TrajectoryBase::getConstraintList(), WolfProblem::getRemovedStateListPtr(), WolfProblem::getStateListPtr(), WolfProblem::getTrajectoryPtr(), WolfProblem::isReallocated(), WolfProblem::reallocationDone(), removeAllStateUnits(), UPDATE_PENDING, and updateStateUnitStatus().
Referenced by main().
void CeresManager::addConstraint (ConstraintBase * _corr_ptr)
Definition at line 188 of file ceres_manager.cpp.
References ceres_problem_, createCostFunction(), ConstraintBase::getStateBlockPtrVector(), NOT_PENDING, and NodeBase::setPendingStatus().
Referenced by update().
void CeresManager::removeConstraint (const unsigned int & _corr_idx)
Definition at line 195 of file ceres_manager.cpp.
void CeresManager::addStateUnit (StateBase * _st_ptr)
Definition at line 202 of file ceres_manager.cpp.
References ceres_problem_, StateBase::getPtr(), StateBase::getStateStatus(), StateBase::getStateType(), NOT_PENDING, NodeBase::setPendingStatus(), ST_COMPLEX_ANGLE, ST_ESTIMATED, ST_POINT_1D, ST_POINT_2D, ST_POINT_3D, ST_THETA, and updateStateUnitStatus().
Referenced by update().
void CeresManager::removeAllStateUnits ()
Definition at line 255 of file ceres_manager.cpp.
References ceres_problem_.
Referenced by update(), and ~CeresManager().
void CeresManager::updateStateUnitStatus (StateBase * _st_ptr)
Definition at line 265 of file ceres_manager.cpp.
References ceres_problem_, StateBase::getPtr(), StateBase::getStateStatus(), NOT_PENDING, NodeBase::setPendingStatus(), ST_ESTIMATED, and ST_FIXED.
Referenced by addStateUnit(), and update().
ceres::CostFunction * CeresManager::createCostFunction (ConstraintBase * _corrPtr)
Definition at line 277 of file ceres_manager.cpp.
References ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block0Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block1Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block2Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block3Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block4Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block5Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block6Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block7Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block8Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block9Size, CTR_CONTAINER, CTR_CORNER_2D_THETA, CTR_FIX, CTR_GPS_FIX_2D, CTR_ODOM_2D_COMPLEX_ANGLE, CTR_ODOM_2D_THETA, ConstraintBase::getConstraintType(), and ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::measurementSize.
Referenced by addConstraint().
ceres::Solver::Summary CeresManager::solve (const ceres::Solver::Options & _ceres_options) inline
Definition at line 500 of file test_ceres_manager.cpp.
void CeresManager::addConstraints (std::queue< ConstraintXBase * > & _new_constraints) inline
Definition at line 538 of file test_ceres_manager.cpp.
Referenced by main().
void CeresManager::removeConstraints () inline
Definition at line 548 of file test_ceres_manager.cpp.
void CeresManager::addConstraint (ConstraintXBase * _corr_ptr) inline
Definition at line 558 of file test_ceres_manager.cpp.
References ConstraintXBase::getBlockPtrVector().
void CeresManager::addStateUnits (std::queue< StateBase * > & _new_state_units) inline
Definition at line 564 of file test_ceres_manager.cpp.
Referenced by main().
void CeresManager::removeStateUnit (WolfScalar * _st_ptr) inline
Definition at line 573 of file test_ceres_manager.cpp.
void CeresManager::addStateUnit (StateBase * _st_ptr) inline
Definition at line 578 of file test_ceres_manager.cpp.
References StateBase::getPtr(), StateBase::getStateType(), ST_COMPLEX_ANGLE, ST_POINT_1D, ST_POINT_2D, and ST_POINT_3D.
ceres::CostFunction* CeresManager::createCostFunction (ConstraintXBase * _corrPtr) inline
Definition at line 622 of file test_ceres_manager.cpp.
References ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block0Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block1Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block2Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block3Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block4Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block5Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block6Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block7Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block8Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block9Size, CTR_GPS_FIX_2D, CTR_ODOM_2D_COMPLEX_ANGLE, CTR_ODOM_2D_THETA, ConstraintXBase::getType(), and ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::measurementSize.
Field Documentation
ceres::Problem * CeresManager::ceres_problem_ protected
Definition at line 34 of file ceres_manager.h.
Referenced by addConstraint(), addStateUnit(), computeCovariances(), removeAllStateUnits(), solve(), update(), updateStateUnitStatus(), and ~CeresManager().
ceres::Covariance* CeresManager::covariance_ protected
Definition at line 35 of file ceres_manager.h.
Referenced by CeresManager(), computeCovariances(), and ~CeresManager().
std::vector<std::pair<ceres::ResidualBlockId, ConstraintXBase*> > CeresManager::constraint_list_ protected
Definition at line 478 of file test_ceres_manager.cpp.
The documentation for this class was generated from the following files:
ceres_manager.h
test_ceres_manager.cpp
ceres_manager.cpp