WOLF: SensorBase Class Reference
SensorBase Class Reference
#include <sensor_base.h>
Public Member Functions
SensorBase (const SensorType &_tp, StatePoint3D *_p_ptr, StateOrientation *_o_ptr, const Eigen::VectorXs &_params)
Constructor without parameters.
SensorBase (const SensorType &_tp, StatePoint3D *_p_ptr, StateOrientation *_o_ptr, unsigned int _params_size)
Constructor with parameter size.
~SensorBase ()
const SensorType getSensorType () const
StatePoint3D * getPPtr () const
StateOrientation * getOPtr () const
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Print node information.
Protected Attributes
SensorType type_
StatePoint3D * p_ptr_
StateOrientation * o_ptr_
Eigen::VectorXs params_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 13 of file sensor_base.h.
Constructor & Destructor Documentation
SensorBase::SensorBase (const SensorType & _tp, StatePoint3D * _p_ptr, StateOrientation * _o_ptr, const Eigen::VectorXs & _params)
Constructor without parameters. Allows allocation of containers of StateBase, such as std::vector<SensorBase>Constructor with parameter vector
Constructor with parameter vector
Parameters
_tp Type of the sensor (types defined at wolf.h)
_p_ptr StateBase pointer to the sensor position
_o_ptr StateOrientation pointer to the sensor orientation
_params Vector containing the sensor parameters
Definition at line 3 of file sensor_base.cpp.
References params_.
SensorBase::SensorBase (const SensorType & _tp, StatePoint3D * _p_ptr, StateOrientation * _o_ptr, unsigned int _params_size)
Constructor with parameter vector
Parameters
_tp Type of the sensor (types defined at wolf.h)
_p_ptr StateBase pointer to the sensor position
_o_ptr StateOrientation pointer to the sensor orientation
_params_size size of the vector containing the sensor parameters
Definition at line 13 of file sensor_base.cpp.
SensorBase::~SensorBase ()
Definition at line 23 of file sensor_base.cpp.
Member Function Documentation
const SensorType SensorBase::getSensorType () const
Definition at line 28 of file sensor_base.cpp.
References type_.
Referenced by CaptureBase::getSensorType().
StatePoint3D * SensorBase::getPPtr () const
Definition at line 33 of file sensor_base.cpp.
References p_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::establishConstraintsMHTree(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
StateOrientation * SensorBase::getOPtr () const
Definition at line 38 of file sensor_base.cpp.
References o_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::establishConstraintsMHTree(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
Field Documentation
SensorType SensorBase::type_ protected
Definition at line 16 of file sensor_base.h.
Referenced by getSensorType().
StatePoint3D* SensorBase::p_ptr_ protected
Definition at line 17 of file sensor_base.h.
Referenced by getPPtr().
StateOrientation* SensorBase::o_ptr_ protected
Definition at line 18 of file sensor_base.h.
Referenced by getOPtr().
Eigen::VectorXs SensorBase::params_ protected
Definition at line 19 of file sensor_base.h.
Referenced by SensorTwist2D::getAngularNoise(), SensorOdom2D::getDisplacementNoiseFactor(), SensorTwist2D::getLinealNoise(), SensorGPSFix::getNoise(), SensorOdom2D::getRotationNoiseFactor(), SensorBase(), SensorOdom2D::SensorOdom2D(), SensorTwist2D::SensorTwist2D(), SensorLaser2D::setDefaultScanParams(), and SensorLaser2D::setScanParams().
The documentation for this class was generated from the following files:
sensor_base.h
sensor_base.cpp