WOLF: CaptureLaser2D Class Reference
CaptureLaser2D Class Reference
#include <capture_laser_2D.h>
Public Member Functions
CaptureLaser2D (const TimeStamp &_ts, SensorBase *_sensor_ptr, const std::vector< float > &_ranges)
Constructor with ranges.
CaptureLaser2D (const TimeStamp &_ts, SensorBase *_sensor_ptr, const std::vector< float > &_ranges, const std::vector< float > &_intensities)
Constructor with ranges and intensities.
virtual ~CaptureLaser2D ()
Destructor.
virtual void processCapture ()
Calls the necessary pipeline from raw scan to features.
virtual unsigned int extractCorners (std::list< laserscanutils::Corner > &_corner_list) const
Extract corners and push-back to Feature down list.
unsigned int extractLines (std::list< laserscanutils::Line > &_line_list) const
Extract lines from the capture.
virtual void createFeatures (std::list< laserscanutils::Corner > &_corner_list)
get corners
void establishConstraintsMHTree ()
Create constraints given current measured features and existing landmarks.
void computeExpectedFeature (LandmarkBase *_landmark_ptr, Eigen::Vector4s &expected_feature_, Eigen::Matrix3s &expected_feature_cov_)
virtual Eigen::VectorXs computePrior (const TimeStamp &_now) const
Eigen::VectorXs computeSquaredMahalanobisDistances (const FeatureBase *_feature_ptr, const LandmarkBase *_landmark_ptr, const Eigen::MatrixXs &_mu)
Eigen::VectorXs computeSquaredMahalanobisDistances (const FeatureBase *_feature_ptr, const Eigen::Vector4s &_expected_feature, const Eigen::Matrix3s &_expected_feature_cov, const Eigen::MatrixXs &_mu)
bool fitNewContainer (FeatureCorner2D *_corner_ptr, LandmarkCorner2D *&old_corner_landmark_ptr, int &feature_idx, int &corner_idx)
Tries to fit a container given a feature and all existing landmarks.
void createCornerLandmark (FeatureCorner2D *_corner_ptr, const Eigen::Vector3s &_feature_global_pose)
void createContainerLandmark (FeatureCorner2D *_corner_ptr, const Eigen::Vector3s &_feature_global_pose, LandmarkCorner2D *_old_corner_landmark_ptr, int &_feature_idx, int &_corner_idx)
Public Member Functions inherited from CaptureBase
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data, const Eigen::MatrixXs &_data_covariance)
virtual ~CaptureBase ()
void linkToFrame (FrameBase *_frm_ptr)
Set link to Frame.
void addFeature (FeatureBase *_ft_ptr)
Adds a Feature to the down node list.
FrameBase * getFramePtr () const
Gets up_node_ptr_.
FeatureBaseList * getFeatureListPtr ()
Gets a pointer to feature list.
void getConstraintList (ConstraintBaseList &_ctr_list)
Fills the provided list with all constraints related to this capture.
TimeStamp getTimeStamp () const
SensorBase * getSensorPtr () const
SensorType getSensorType () const
void setTimeStamp (const TimeStamp &_ts)
void setTimeStampToNow ()
Eigen::VectorXs getData ()
Eigen::MatrixXs getDataCovariance ()
void setData (unsigned int _size, const WolfScalar *_data)
void setData (const Eigen::VectorXs &_data)
void setDataCovariance (const Eigen::MatrixXs &_data_cov)
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FrameBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
std::vector< float > ranges_
std::vector< float > intensities_
SensorLaser2D * laser_ptr_
Protected Attributes inherited from CaptureBase
TimeStamp time_stamp_
Time stamp.
SensorBase * sensor_ptr_
Pointer to sensor.
Eigen::VectorXs data_
raw data
Eigen::MatrixXs data_covariance_
Noise of the capture.
Eigen::Vector3s sensor_pose_global_
Sensor pose in world frame: composition of the frame pose and the sensor pose. TODO: use state units.
Eigen::Vector3s inverse_sensor_pose_
World pose in the sensor frame: inverse of the global_pose_. TODO: use state units.
Protected Attributes inherited from NodeLinked< FrameBase, FeatureBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef FrameBase * UpperNodePtr
typedef FeatureBase * LowerNodePtr
Protected Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 42 of file capture_laser_2D.h.
Constructor & Destructor Documentation
CaptureLaser2D::CaptureLaser2D (const TimeStamp & _ts, SensorBase * _sensor_ptr, const std::vector< float > & _ranges)
Constructor with ranges
Definition at line 17 of file capture_laser_2D.cpp.
References laser_ptr_, and CaptureBase::sensor_ptr_.
CaptureLaser2D::CaptureLaser2D (const TimeStamp & _ts, SensorBase * _sensor_ptr, const std::vector< float > & _ranges, const std::vector< float > & _intensities)
Constructor with ranges and intensities
Definition at line 35 of file capture_laser_2D.cpp.
References laser_ptr_, and CaptureBase::sensor_ptr_.
CaptureLaser2D::~CaptureLaser2D () virtual
Destructor
Definition at line 48 of file capture_laser_2D.cpp.
Member Function Documentation
void CaptureLaser2D::processCapture () virtual
Calls the necessary pipeline from raw scan to features.
Reimplemented from CaptureBase.
Definition at line 53 of file capture_laser_2D.cpp.
References createFeatures(), establishConstraintsMHTree(), and extractCorners().
unsigned int CaptureLaser2D::extractCorners (std::list< laserscanutils::Corner > & _corner_list) const virtual
Extract corners and push-back to Feature down list .
Definition at line 72 of file capture_laser_2D.cpp.
References SensorLaser2D::getCornerAlgParams(), SensorLaser2D::getScanParams(), laser_ptr_, and ranges_.
Referenced by main(), and processCapture().
unsigned int CaptureLaser2D::extractLines (std::list< laserscanutils::Line > & _line_list) const
Extract lines from the capture
Definition at line 81 of file capture_laser_2D.cpp.
References SensorLaser2D::getCornerAlgParams(), SensorLaser2D::getScanParams(), laser_ptr_, and ranges_.
void CaptureLaser2D::createFeatures (std::list< laserscanutils::Corner > & _corner_list) virtual
Get corners
Definition at line 86 of file capture_laser_2D.cpp.
References CaptureBase::addFeature().
Referenced by processCapture().
void CaptureLaser2D::establishConstraintsMHTree ()
Create constraints given current measured features and existing landmarks Uses a Multi-Hypothesis Tree
Definition at line 128 of file capture_laser_2D.cpp.
References FeatureBase::addConstraint(), computeExpectedFeature(), computeSquaredMahalanobisDistances(), CONTAINER_LENGTH, CONTAINER_WIDTH, createContainerLandmark(), createCornerLandmark(), fitNewContainer(), CaptureBase::getFeatureListPtr(), CaptureBase::getFramePtr(), MapBase::getLandmarkListPtr(), WolfProblem::getMapPtr(), SensorBase::getOPtr(), LandmarkBase::getOPtr(), FrameBase::getOPtr(), SensorBase::getPPtr(), LandmarkBase::getPPtr(), FrameBase::getPPtr(), StateOrientation::getRotationMatrix(), CaptureBase::getSensorPtr(), NodeLinked< FrameBase, FeatureBase >::getTop(), LandmarkBase::getType(), StateBase::getVector(), StatePoint< SIZE >::getVector(), StateOrientation::getYaw(), LANDMARK_CONTAINER, LANDMARK_CORNER, MAX_ACCEPTED_APERTURE_DIFF, AssociationSolver::numDetections(), AssociationSolver::numTargets(), pi2pi(), AssociationTree::resize(), AssociationSolver::setScore(), and AssociationTree::solve().
Referenced by processCapture().
void CaptureLaser2D::computeExpectedFeature (LandmarkBase * _landmark_ptr, Eigen::Vector4s & expected_feature_, Eigen::Matrix3s & expected_feature_cov_)
Definition at line 329 of file capture_laser_2D.cpp.
References WolfProblem::getCovarianceBlock(), CaptureBase::getFramePtr(), SensorBase::getOPtr(), LandmarkBase::getOPtr(), FrameBase::getOPtr(), SensorBase::getPPtr(), LandmarkBase::getPPtr(), FrameBase::getPPtr(), StateOrientation::getRotationMatrix(), CaptureBase::getSensorPtr(), NodeLinked< FrameBase, FeatureBase >::getTop(), LandmarkBase::getType(), StateBase::getVector(), StatePoint< SIZE >::getVector(), StateOrientation::getYaw(), LANDMARK_CONTAINER, LANDMARK_CORNER, and pi2pi().
Referenced by establishConstraintsMHTree().
Eigen::VectorXs CaptureLaser2D::computePrior (const TimeStamp & _now) const virtual
Implements CaptureBase.
Definition at line 324 of file capture_laser_2D.cpp.
Eigen::VectorXs CaptureLaser2D::computeSquaredMahalanobisDistances (const FeatureBase * _feature_ptr, const LandmarkBase * _landmark_ptr, const Eigen::MatrixXs & _mu)
Definition at line 386 of file capture_laser_2D.cpp.
References WolfProblem::getCovarianceBlock(), CaptureBase::getFramePtr(), FeatureBase::getMeasurement(), FeatureBase::getMeasurementCovariance(), SensorBase::getOPtr(), LandmarkBase::getOPtr(), SensorBase::getPPtr(), LandmarkBase::getPPtr(), StateOrientation::getRotationMatrix(), CaptureBase::getSensorPtr(), NodeLinked< FrameBase, FeatureBase >::getTop(), StateBase::getVector(), StatePoint< SIZE >::getVector(), StateOrientation::getYaw(), and pi2pi().
Referenced by establishConstraintsMHTree(), and fitNewContainer().
Eigen::VectorXs CaptureLaser2D::computeSquaredMahalanobisDistances (const FeatureBase * _feature_ptr, const Eigen::Vector4s & _expected_feature, const Eigen::Matrix3s & _expected_feature_cov, const Eigen::MatrixXs & _mu)
Definition at line 459 of file capture_laser_2D.cpp.
References FeatureBase::getMeasurement(), FeatureBase::getMeasurementCovariance(), and pi2pi().
bool CaptureLaser2D::fitNewContainer (FeatureCorner2D * _corner_ptr, LandmarkCorner2D *& old_corner_landmark_ptr, int & feature_idx, int & corner_idx)
Tries to fit a container given a feature and all existing landmarks. Returns false if not fitted and true otherwise. Returns via params feature_idx & corner_idx the index of the feature and the landmark respectively and in old_corner_landmark_ptr, the corresponding landmark:
1 ----------------------— 0
2 ----------------------— 3
Definition at line 485 of file capture_laser_2D.cpp.
References computeSquaredMahalanobisDistances(), CONTAINER_LENGTH, CONTAINER_WIDTH, MapBase::getLandmarkListPtr(), WolfProblem::getMapPtr(), FeatureBase::getMeasurement(), NodeLinked< FrameBase, FeatureBase >::getTop(), LANDMARK_CORNER, MAX_ACCEPTED_APERTURE_DIFF, and pi2pi().
Referenced by establishConstraintsMHTree().
void CaptureLaser2D::createCornerLandmark (FeatureCorner2D * _corner_ptr, const Eigen::Vector3s & _feature_global_pose)
Definition at line 570 of file capture_laser_2D.cpp.
References FeatureBase::addConstraint(), WolfProblem::addCovarianceBlock(), MapBase::addLandmark(), WolfProblem::addState(), WolfProblem::getCovarianceBlock(), CaptureBase::getFramePtr(), WolfProblem::getMapPtr(), FeatureBase::getMeasurement(), FeatureBase::getMeasurementCovariance(), LandmarkBase::getOPtr(), FrameBase::getOPtr(), LandmarkBase::getPPtr(), StateOrientation::getRotationMatrix(), and NodeLinked< FrameBase, FeatureBase >::getTop().
Referenced by establishConstraintsMHTree().
void CaptureLaser2D::createContainerLandmark (FeatureCorner2D * _corner_ptr, const Eigen::Vector3s & _feature_global_pose, LandmarkCorner2D * _old_corner_landmark_ptr, int & _feature_idx, int & _corner_idx)
Definition at line 603 of file capture_laser_2D.cpp.
References FeatureBase::addConstraint(), WolfProblem::addCovarianceBlock(), MapBase::addLandmark(), WolfProblem::addState(), CONTAINER_LENGTH, CONTAINER_WIDTH, LandmarkBase::getConstraints(), WolfProblem::getCovarianceBlock(), CaptureBase::getFramePtr(), WolfProblem::getMapPtr(), LandmarkBase::getOPtr(), LandmarkBase::getPPtr(), NodeLinked< FrameBase, FeatureBase >::getTop(), StateBase::getVector(), StateOrientation::getYaw(), and MapBase::removeLandmark().
Referenced by establishConstraintsMHTree().
Field Documentation
std::vector<float> CaptureLaser2D::ranges_ protected
Definition at line 54 of file capture_laser_2D.h.
Referenced by extractCorners(), and extractLines().
std::vector<float> CaptureLaser2D::intensities_ protected
Definition at line 56 of file capture_laser_2D.h.
SensorLaser2D* CaptureLaser2D::laser_ptr_ protected
Definition at line 57 of file capture_laser_2D.h.
Referenced by CaptureLaser2D(), extractCorners(), and extractLines().
The documentation for this class was generated from the following files:
capture_laser_2D.h
capture_laser_2D.cpp