WOLF: EpipolarConstraint Class Reference
EpipolarConstraint Class Reference
Epipolar constraint between two corresponding image point features.
#include <epipolar_constraint.h>
Public Member Functions
EpipolarConstraint (const FeatureShPtr &_ft_ptr, const FeatureShPtr &_ft_other_ptr)
void computeExpectation ()
Compute the expected epipolar line.
void computeError ()
Compute the epipolar constraint error.
void computeError (Eigen::VectorXs &_residuals, unsigned int &_idx)
Compute the epipolar constraint error.
void computeError (Eigen::Map< Eigen::VectorXs > &_residuals, unsigned int &_idx)
Compute the epipolar constraint error.
void computeError (WolfScalar *_residuals, unsigned int &_idx)
Compute the epipolar constraint error.
Public Member Functions inherited from CorrespondenceRelative
CorrespondenceRelative (const FeatureShPtr &_ft_ptr, const FeatureShPtr &_ft_other_ptr, unsigned int _dim_error, unsigned int _dim_expectation)
virtual ~CorrespondenceRelative ()
const StatePtr stateOtherPtr () const
const StatePose & stateOther () const
const CapturePtr captureOtherPtr () const
const Capture & captureOther () const
const SensorPtr sensorOtherPtr () const
const SensorBase & sensorOther () const
const FeaturePtr featureOtherPtr () const
const FeatureBase & featureOther () const
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from CorrespondenceBase
CorrespondenceBase (const unsigned int &_measurement_size)
virtual ~CorrespondenceBase ()
virtual void inventMeasurement (const VectorXs &_measurement, std::default_random_engine &_generator, std::normal_distribution< WolfScalar > &_distribution)
virtual correspondenceType getType () const =0
virtual WolfScalar ** getBlockPtrArray ()=0
virtual const std::vector
< WolfScalar * > getBlockPtrVector ()=0
CorrespondenceBase (const unsigned int &_measurement_size)
virtual ~CorrespondenceBase ()
virtual void inventMeasurement (const VectorXs &_measurement, std::default_random_engine &_generator, std::normal_distribution< WolfScalar > &_distribution)
void linkToFeature (const FeatureShPtr &_ft_ptr)
const FeaturePtr featurePtr () const
const FeatureBase & feature () const
const CapturePtr capturePtr () const
const Capture & capture () const
const SensorPtr sensorPtr () const
const SensorBase & sensor () const
const StatePtr statePtr () const
const StatePose & state () const
const Eigen::VectorXs & expectation () const
Public Member Functions inherited from NodeConstrainer< FeatureBase, NodeTerminus >
unsigned int computeDimError ()
Compute dim_error_ (recursive)
unsigned int dimError () const
Returns dim_error_.
unsigned int remap (Eigen::VectorXs &_storage, unsigned int _idx)
Remaps error_ vector recursively.
unsigned int remap (WolfScalar *_storage, unsigned int _idx)
Remaps error_ vector recursively.
virtual const Eigen::Map
< Eigen::VectorXs > & error () const
Gets a reference to the error of the node.
virtual void precomputeConstants ()
pre-compute constants affecting the current node.
Public Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Static Public Attributes
static const unsigned int DIM_ERROR_ = 1
Dimension of error.
static const unsigned int DIM_EXPECTATION_ = 3
Dimension of expectation.
Additional Inherited Members
Protected Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef FeatureBase * UpNodePtr
typedef NodeTerminus * DownNodePtr
typedef std::shared_ptr
< FeatureBase > UpNodeShPtr
typedef std::shared_ptr
< NodeTerminus > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Protected Member Functions inherited from CorrespondenceBase
CorrespondenceBase (const FeatureShPtr &_ft_ptr, unsigned int _dim_error, unsigned int _dim_expectation)
Constructor.
virtual ~CorrespondenceBase ()
Protected Member Functions inherited from NodeConstrainer< FeatureBase, NodeTerminus >
NodeConstrainer (const NodeLocation _loc, const std::string &_label)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< FeatureBase, NodeTerminus >::UpNodeShPtr &_up_node_ptr)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< FeatureBase, NodeTerminus >::UpNodeShPtr &_up_node_ptr, unsigned int _dim_error)
virtual ~NodeConstrainer ()
Protected Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const FeatureBase & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from CorrespondenceBase
VectorXs measurement_
Eigen::VectorXs expectation_
the expected measurement given the current state estimate
CapturePtr capture_ptr_
pointer to own capture
StatePtr state_ptr_
pointer to own state
SensorPtr sensor_ptr_
pointer to own's capture sensor
Protected Attributes inherited from NodeConstrainer< FeatureBase, NodeTerminus >
unsigned int dim_error_
Eigen::Map< Eigen::VectorXs > error_
Detailed Description
Epipolar constraint between two corresponding image point features.
This type of constraint takes two frames, two pin-hole cameras, and two point feature measurements, and computes the error of the epipolar constraint.
Notice that there are some possibilities:
Both frames are the same: it means we have two cameras on the robot.
Both cameras are the same: it means we have moved and are in another frame.
Frames and cameras are different: it means we observe from one camera a feature that was seen in the past by another camera.
The epipolar error is 1D, defined as the distance from the current measurement (2D) to the epipolar line (3D) defined by the old measure, the relative frame transformation, and the two sets of intrinsic parameters.
Definition at line 29 of file epipolar_constraint.h.
Constructor & Destructor Documentation
EpipolarConstraint::EpipolarConstraint (const FeatureShPtr & _ft_ptr, const FeatureShPtr & _ft_other_ptr)
Definition at line 123 of file epipolar_constraint.h.
Member Function Documentation
void EpipolarConstraint::computeExpectation () virtual
Compute the expected epipolar line.
The epipolar line is a homogeneous line representation, the result of projecting the visual line of the pixel seen from the "other" camera into this "own" camera.
Here is the algorithm:
Consider "other" the ref camera pose, and "own" the new camera pose.
Given the intrinsic matrices of both cameras
Given the detected pixel in the "other" camera,
Compute R, T the relative pose from "other" to "own" cameras,
Compute the Essential matrix,
Mind that the definitions in some literature (e.g. Wikipedia) state , but we need the transposed for consistency with our conventions.
Compute the Fundamental matrix,
Compute the epipolar line,
The epipolar constraint error can be computed by measuring the distance from the "own" measured pixel to this expected line. The computeError() function is therefore also overloaded.
Implements CorrespondenceBase.
Definition at line 130 of file epipolar_constraint.h.
References CorrespondenceRelative::captureOtherPtr(), CorrespondenceBase::capturePtr(), TransSensor::computeExpectation(), CorrespondenceBase::expectation_, CorrespondenceRelative::featureOtherPtr(), Capture::globalPose(), Capture::inverseGlobalPose(), PinHole::inverseIntrinsicMatrix(), FeatureBase::measurement(), Node::nodeId(), StatePose::p(), StatePose::q(), CorrespondenceRelative::sensorOtherPtr(), CorrespondenceBase::sensorPtr(), Wolf::skew(), and Capture::transSensorPtr().
Referenced by computeError().
void EpipolarConstraint::computeError () inline virtual
Compute the epipolar constraint error. This corresponds to the signed distance from the epipolar line to the measured pixel.
The formula for this distance is taken from SOLA-IJCV-11, eq. (64).
The algorithm for computing this signed distance is as follows:
Given line, the epipolar line computed in computeExpectation().
Given pix, the pixel measurement in the up node feature.
compute the signed distance, that is,
As such, this algorithm is a normalized version (into the pixel units) of the error in the epipolar constraint , as it can be seen by substituting the result given by computeExpectation(), :
where is the fundamental matrix between the two cameras, and the pixels are in homogeneous coordinates.
Reimplemented from CorrespondenceBase.
Definition at line 179 of file epipolar_constraint.h.
References computeExpectation(), Wolf::distPointToLine(), NodeConstrainer< FeatureBase, NodeTerminus >::error_, CorrespondenceBase::expectation(), and CorrespondenceBase::featurePtr().
void EpipolarConstraint::computeError (Eigen::VectorXs & _residuals, unsigned int & _idx) inline virtual
Compute the epipolar constraint error and place it at the given _residuals, starting at position _idx and spanning the dimension of the error of this node.
See Also
computeError() for more information.
Reimplemented from CorrespondenceBase.
Definition at line 193 of file epipolar_constraint.h.
References computeExpectation(), DIM_ERROR_, Wolf::distPointToLine(), CorrespondenceBase::expectation(), CorrespondenceBase::featurePtr(), and FeatureBase::measurement().
void EpipolarConstraint::computeError (Eigen::Map< Eigen::VectorXs > & _residuals, unsigned int & _idx) inline virtual
Compute the epipolar constraint error and place it at the given _residuals Map<VectorXs>, starting at position _idx and spanning the dimension of the error of this node.
See Also
computeError() for more information.
Reimplemented from CorrespondenceBase.
Definition at line 201 of file epipolar_constraint.h.
References computeExpectation(), DIM_ERROR_, Wolf::distPointToLine(), CorrespondenceBase::expectation(), CorrespondenceBase::featurePtr(), and FeatureBase::measurement().
void EpipolarConstraint::computeError (WolfScalar * _residuals, unsigned int & _idx) inline virtual
Compute the epipolar constraint error and place it at the given _residuals pointer, plus _idx, and spanning the dimension of the error of this node.
See Also
computeError() for more information.
Reimplemented from CorrespondenceBase.
Definition at line 208 of file epipolar_constraint.h.
References computeExpectation(), DIM_ERROR_, Wolf::distPointToLine(), CorrespondenceBase::expectation(), CorrespondenceBase::featurePtr(), and FeatureBase::measurement().
Field Documentation
const unsigned int EpipolarConstraint::DIM_ERROR_ = 1 static
Definition at line 33 of file epipolar_constraint.h.
Referenced by computeError().
const unsigned int EpipolarConstraint::DIM_EXPECTATION_ = 3 static
Definition at line 34 of file epipolar_constraint.h.
The documentation for this class was generated from the following file:
epipolar_constraint.h