WOLF: StatePQV Class Reference
StatePQV Class Reference
Class for 3D position, velocity and orientation states.
#include <state_pqv.h>
Public Member Functions
StatePQV ()
StatePQV (Eigen::VectorXs &_x)
StatePQV (Eigen::Vector3s &_p, Eigen::Quaternions &_q, Eigen::Vector3s &_v)
StatePQV (Eigen::VectorXs &_storage, unsigned int _idx)
StatePQV (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_x)
StatePQV (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::Vector3s &_p, Eigen::Quaternions &_q, Eigen::Vector3s &_v)
virtual ~StatePQV ()
void v (Eigen::Vector3s &_vel)
Eigen::Map< Eigen::Vector3s > & v ()
const Eigen::Map
< Eigen::Vector3s > & v () const
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Public Member Functions inherited from StatePose
StatePose ()
Default local constructor.
StatePose (unsigned int _size)
Local constructor from size.
StatePose (const Eigen::VectorXs &_x)
Local constructor from vector.
StatePose (const StatePose &_pose)
Local constructor from StatePose.
StatePose (unsigned int _size, Eigen::Vector3s &_p, Eigen::Quaternions &_q)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_x)
StatePose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size, Eigen::Vector3s &_p, Eigen::Quaternions &_q)
virtual ~StatePose ()
virtual void setToOrigin ()
Set to origin.
void p (Eigen::Vector3s &_pos)
Eigen::Map< Eigen::Vector3s > & p ()
const Eigen::Map
< Eigen::Vector3s > & p () const
void q (Eigen::Quaternions &_quat)
Eigen::Map< Eigen::Quaternions > & q ()
const Eigen::Map
< Eigen::Quaternions > & q () const
virtual StatePose composeWithLocal (const StatePose &_local_pose) const
compose this pose with a local pose
virtual void composeWithLocal (const StatePose &_local_pose, StatePose &_return_pose) const
virtual void composeWithLocal (const StatePose &_local_pose)
virtual StatePose composeOnTopOf (const StatePose &_base_pose) const
compose this pose with a base pose
virtual void composeOnTopOf (const StatePose &_base_pose, StatePose &_return_pose) const
virtual void composeOnTopOf (const StatePose &_base_pose)
virtual StatePose composeRelativeTo (const StatePose &_reference_pose) const
compose poses
virtual void composeRelativeTo (const StatePose &_reference_pose, StatePose &_return_pose) const
virtual void composeRelativeTo (const StatePose &_reference_pose)
virtual StatePose inverse () const
inverse pose
void inverse (StatePose &_result) const
Public Member Functions inherited from StateBase
StateBase (const unsigned int _size)
StateBase (const Eigen::VectorXs &_x)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateBase ()
Eigen::Map< Eigen::VectorXs > & x ()
const Eigen::Map
< Eigen::VectorXs > & x () const
void x (const Eigen::VectorXs &_x)
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
unsigned int size ()
Static Public Attributes
static const unsigned int SIZE_ = 10
Size of the overall PQV state.
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Class for 3D position, velocity and orientation states. Oreintation is represented with a quaternion. It inherits State (and StateBase, and StatePose), so it can be constructed as local or remote. P,V and Q parts are mapped over the StateBase map. Q part is a Quaternion Map, so when it is returned it can be used as a standard Eigen Quaternion. The class implements P,V,Q accessors, and also a method to integrate IMU (Inertial Measurement Units) measurements to such states.
Definition at line 30 of file state_pqv.h.
Constructor & Destructor Documentation
StatePQV::StatePQV ()
Default local constructor
Definition at line 12 of file state_pqv.cpp.
StatePQV::StatePQV (Eigen::VectorXs & _x)
Local constructor from vector
Parameters
_x the state vector
StatePQV::StatePQV (Eigen::Vector3s & _p, Eigen::Quaternions & _q, Eigen::Vector3s & _v)
Local constructor from vectors
Parameters
_p position
_q orientation quaternion (must be normalized)
_v velocity
Definition at line 24 of file state_pqv.cpp.
References v().
StatePQV::StatePQV (Eigen::VectorXs & _storage, unsigned int _idx)
Remote constructor
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
StatePQV::StatePQV (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _x)
Remote constructor from vector
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_x the state vector
StatePQV::StatePQV (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::Vector3s & _p, Eigen::Quaternions & _q, Eigen::Vector3s & _v)
Remote constructor from vectors
Parameters
_storage storage vector
_idx index where the state maps to the remote storage vector
_p position
_q orientation quaternion (must be normalized)
_v velocity
StatePQV::~StatePQV () virtual
Destructor
Definition at line 51 of file state_pqv.cpp.
Member Function Documentation
void StatePQV::v (Eigen::Vector3s & _vel) inline
Set velocity
Parameters
_vel velocity
Definition at line 116 of file state_pqv.h.
Eigen::Map< Eigen::Vector3s > & StatePQV::v () inline
Get reference to velocity
Definition at line 121 of file state_pqv.h.
Referenced by StatePQV().
const Eigen::Map< Eigen::Vector3s > & StatePQV::v () const inline
Get reference to velocity
Definition at line 126 of file state_pqv.h.
void StatePQV::remap (Eigen::VectorXs & _st_remote, const unsigned int _idx) inline virtual
Reimplemented from StatePose.
Definition at line 131 of file state_pqv.h.
References StatePose::remap(), and StateRootBase::state_estimated_map_.
Field Documentation
const unsigned int StatePQV::SIZE_ = 10 static
Definition at line 33 of file state_pqv.h.
The documentation for this class was generated from the following files:
state_pqv.h
state_pqv.cpp