WOLF: RawBase Class Reference
RawBase Class Reference
Base class for all kind of classes storing raw data.
#include <raw_base.h>
Public Member Functions
void timeStamp (const WolfScalar &_ts)
Sets time stamp.
WolfScalar timeStamp () const
Gets time stamp.
const Eigen::VectorXs & rawData () const
Gets the raw data.
void setTimeStampToNow ()
Sets time stamp to now.
void setData (unsigned int _size, const WolfScalar *_data)
Sets raw data.
virtual void print (std::ostream &ost=std::cout) const
Prints time stamp + data.
Protected Member Functions
RawBase ()
Constructor without arguments.
RawBase (const WolfScalar _ts)
Constructor with time stamp.
RawBase (const WolfScalar _ts, const Eigen::VectorXs &_data)
Constructor.
virtual ~RawBase ()
Destructor.
Detailed Description
This class is the base for all classes storing raw data.
Definition at line 23 of file raw_base.h.
Constructor & Destructor Documentation
RawBase::RawBase () inline protected
Constructor without arguments
Definition at line 110 of file raw_base.h.
RawBase::RawBase (const WolfScalar _ts) inline protected
Constructor from time stamp
Parameters
_ts time stamp
Definition at line 117 of file raw_base.h.
RawBase::RawBase (const WolfScalar _ts, const Eigen::VectorXs & _data) inline protected
Constructor from time stamp and data
Parameters
_ts time stamp
_data the raw data
Definition at line 124 of file raw_base.h.
RawBase::~RawBase () inline protected virtual
Destructor
Definition at line 131 of file raw_base.h.
Member Function Documentation
void RawBase::timeStamp (const WolfScalar & _ts) inline
Sets the time stamp
Definition at line 136 of file raw_base.h.
References TimeStamp::set().
WolfScalar RawBase::timeStamp () const inline
Returns the time stamp
Definition at line 141 of file raw_base.h.
References TimeStamp::get().
const Eigen::VectorXs & RawBase::rawData () const inline
Returns a reference to the raw data
Definition at line 146 of file raw_base.h.
void RawBase::setTimeStampToNow () inline
Sets time stamp to now
Definition at line 151 of file raw_base.h.
References TimeStamp::setToNow().
void RawBase::setData (unsigned int _size, const WolfScalar * _data) inline
Sets raw data
Definition at line 156 of file raw_base.h.
void RawBase::print (std::ostream & ost = std::cout) const inline virtual
Prints time stamp and data in a single row. By default at std::cout.
Reimplemented in RawLaser2D.
Definition at line 162 of file raw_base.h.
References TimeStamp::print().
Referenced by RawLaser2D::print().
The documentation for this class was generated from the following file:
raw_base.h