WOLF: SensorLaser2D Class Reference
SensorLaser2D Class Reference
#include <sensor_laser_2D.h>
Public Member Functions
SensorLaser2D (StatePoint3D *_p_ptr, StateOrientation *_o_ptr)
Constructor with arguments.
virtual ~SensorLaser2D ()
Destructor.
void setDefaultScanParams ()
void setScanParams (const laserscanutils::ScanParams &_params)
Set scanner intrinsic parameters.
void setDefaultCornerAlgParams ()
void setCornerAlgParams (const laserscanutils::ExtractCornerParams &_corner_alg_params)
Set corner detection algorithm parameters.
const laserscanutils::ScanParams & getScanParams () const
Get scanner intrinsic parameters.
const
laserscanutils::ExtractCornerParams & getCornerAlgParams () const
Get parameters for corner detection algorithm.
void printSensorParameters () const
Returns angle_min.
Public Member Functions inherited from SensorBase
SensorBase (const SensorType &_tp, StatePoint3D *_p_ptr, StateOrientation *_o_ptr, const Eigen::VectorXs &_params)
Constructor without parameters.
SensorBase (const SensorType &_tp, StatePoint3D *_p_ptr, StateOrientation *_o_ptr, unsigned int _params_size)
Constructor with parameter size.
~SensorBase ()
const SensorType getSensorType () const
StatePoint3D * getPPtr () const
StateOrientation * getOPtr () const
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Print node information.
Protected Attributes
laserscanutils::ScanParams scan_params_
laserscanutils::ExtractCornerParams corners_alg_params_
Protected Attributes inherited from SensorBase
SensorType type_
StatePoint3D * p_ptr_
StateOrientation * o_ptr_
Eigen::VectorXs params_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 13 of file sensor_laser_2D.h.
Constructor & Destructor Documentation
SensorLaser2D::SensorLaser2D (StatePoint3D * _p_ptr, StateOrientation * _o_ptr)
Constructor with arguments
Parameters
_p_ptr StateBase pointer to the sensor position
_o_ptr StateOrientation pointer to the sensor orientation
_params struct with scan parameters. See laser_scan_utils library API for reference
Definition at line 10 of file sensor_laser_2D.cpp.
References setDefaultCornerAlgParams(), and setDefaultScanParams().
SensorLaser2D::~SensorLaser2D () virtual
Destructor
Definition at line 24 of file sensor_laser_2D.cpp.
Member Function Documentation
void SensorLaser2D::setDefaultScanParams ()
Definition at line 29 of file sensor_laser_2D.cpp.
References SensorBase::params_, and scan_params_.
Referenced by SensorLaser2D().
void SensorLaser2D::setScanParams (const laserscanutils::ScanParams & _params)
Set scanner intrinsic parameters
Parameters
_params struct with scanner intrinsic parameters. See laser_scan_utils library API for reference.
Definition at line 47 of file sensor_laser_2D.cpp.
References SensorBase::params_, and scan_params_.
void SensorLaser2D::setDefaultCornerAlgParams ()
Definition at line 59 of file sensor_laser_2D.cpp.
References corners_alg_params_.
Referenced by SensorLaser2D().
void SensorLaser2D::setCornerAlgParams (const laserscanutils::ExtractCornerParams & _corner_alg_params)
Set corner detection algorithm parameters
Parameters
_params struct with corner detection algorithm parameters. See laser_scan_utils library API for reference.
Definition at line 72 of file sensor_laser_2D.cpp.
References corners_alg_params_.
const laserscanutils::ScanParams & SensorLaser2D::getScanParams () const
Get scanner intrinsic parameters
Definition at line 77 of file sensor_laser_2D.cpp.
References scan_params_.
Referenced by CaptureLaser2D::extractCorners(), and CaptureLaser2D::extractLines().
const laserscanutils::ExtractCornerParams & SensorLaser2D::getCornerAlgParams () const
Get parameters for corner detection algorithm
Definition at line 82 of file sensor_laser_2D.cpp.
References corners_alg_params_.
Referenced by CaptureLaser2D::extractCorners(), and CaptureLaser2D::extractLines().
void SensorLaser2D::printSensorParameters () const
Returns angle_minReturns angle_max
Returns angle_maxReturns angle_increment
Returns angle_incrementReturns range_min
Returns range_minReturns range_max
Returns range_maxReturns _range_stdev
Returns _range_stdevReturns time_increment
Returns time_incrementReturns scan_time
Returns scan_timePrints parameters
Prints parameters
Definition at line 127 of file sensor_laser_2D.cpp.
References corners_alg_params_, and scan_params_.
Referenced by main().
Field Documentation
laserscanutils::ScanParams SensorLaser2D::scan_params_ protected
Definition at line 20 of file sensor_laser_2D.h.
Referenced by getScanParams(), printSensorParameters(), setDefaultScanParams(), and setScanParams().
laserscanutils::ExtractCornerParams SensorLaser2D::corners_alg_params_ protected
Definition at line 21 of file sensor_laser_2D.h.
Referenced by getCornerAlgParams(), printSensorParameters(), setCornerAlgParams(), and setDefaultCornerAlgParams().
The documentation for this class was generated from the following files:
sensor_laser_2D.h
sensor_laser_2D.cpp