WOLF: Matrixx< T > Class Template Reference
Matrixx< T > Class Template Reference
#include <matrix.h>
Public Member Functions
Matrixx ()
Matrixx (unsigned int _rows, unsigned int _cols)
~Matrixx ()
void clear ()
void resize (unsigned int _rows, unsigned int _cols)
unsigned int size () const
T & operator() (unsigned int _i, unsigned int _j)
const T & operator() (unsigned int _i, unsigned int _j) const
void print () const
Protected Attributes
unsigned int rows_
unsigned int cols_
std::vector< T > inner_
Detailed Description
template<typename T>
class Matrixx< T >
Definition at line 12 of file matrix.h.
Constructor & Destructor Documentation
template<typename T> Matrixx< T >::Matrixx () inline
Definition at line 19 of file matrix.h.
template<typename T> Matrixx< T >::Matrixx (unsigned int _rows, unsigned int _cols) inline
Definition at line 26 of file matrix.h.
template<typename T> Matrixx< T >::~Matrixx () inline
Definition at line 34 of file matrix.h.
Member Function Documentation
template<typename T> void Matrixx< T >::clear () inline
Definition at line 39 of file matrix.h.
Referenced by AssociationTree::reset(), and AssociationNNLS::reset().
template<typename T> void Matrixx< T >::resize (unsigned int _rows, unsigned int _cols) inline
Definition at line 44 of file matrix.h.
Referenced by AssociationTree::resize(), and AssociationNNLS::resize().
template<typename T> unsigned int Matrixx< T >::size () const inline
Definition at line 52 of file matrix.h.
Referenced by AssociationTree::printTree().
template<typename T> T& Matrixx< T >::operator() (unsigned int _i, unsigned int _j) inline
Definition at line 57 of file matrix.h.
template<typename T> const T& Matrixx< T >::operator() (unsigned int _i, unsigned int _j) const inline
Definition at line 63 of file matrix.h.
template<typename T> void Matrixx< T >::print () const inline
Definition at line 69 of file matrix.h.
Referenced by AssociationSolver::printScoreTable().
Field Documentation
template<typename T> unsigned int Matrixx< T >::rows_ protected
Definition at line 15 of file matrix.h.
Referenced by Matrixx< double >::operator()(), Matrixx< double >::print(), Matrixx< double >::resize(), and Matrixx< double >::size().
template<typename T> unsigned int Matrixx< T >::cols_ protected
Definition at line 15 of file matrix.h.
Referenced by Matrixx< double >::operator()(), Matrixx< double >::print(), Matrixx< double >::resize(), and Matrixx< double >::size().
template<typename T> std::vector<T> Matrixx< T >::inner_ protected
Definition at line 16 of file matrix.h.
Referenced by Matrixx< double >::clear(), Matrixx< double >::operator()(), Matrixx< double >::print(), and Matrixx< double >::resize().
The documentation for this class was generated from the following file:
matrix.h