WOLF: TrajectoryBase Class Reference
TrajectoryBase Class Reference
#include <trajectory_base.h>
Public Member Functions
TrajectoryBase ()
Constructor.
~TrajectoryBase ()
Destructor.
void addFrame (FrameBase *_frame_ptr)
Add a frame to the trajectory.
void removeFrame (const FrameBaseIter &_frame_ptr)
Remove a frame to the trajectory.
FrameBaseList * getFrameListPtr ()
Returns a pointer to Frame list.
FrameBase * getLastFramePtr ()
Returns a pointer to last Frame.
void getConstraintList (ConstraintBaseList &_ctr_list)
Returns a list of all constraints in the trajectory thru reference.
Public Member Functions inherited from NodeLinked< WolfProblem, FrameBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const WolfProblem & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
unsigned int fixed_size_
Protected Attributes inherited from NodeLinked< WolfProblem, FrameBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< WolfProblem, FrameBase >
typedef WolfProblem * UpperNodePtr
typedef FrameBase * LowerNodePtr
Protected Types inherited from NodeLinked< WolfProblem, FrameBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< WolfProblem, FrameBase >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 24 of file trajectory_base.h.
Constructor & Destructor Documentation
TrajectoryBase::TrajectoryBase ()
Constructor
Definition at line 3 of file trajectory_base.cpp.
TrajectoryBase::~TrajectoryBase ()
Destructor
Definition at line 9 of file trajectory_base.cpp.
Member Function Documentation
void TrajectoryBase::addFrame (FrameBase * _frame_ptr)
Add a frame to the trajectory
Definition at line 14 of file trajectory_base.cpp.
References NodeLinked< WolfProblem, FrameBase >::addDownNode().
void TrajectoryBase::removeFrame (const FrameBaseIter & _frame_ptr)
Remove a frame to the trajectory
Definition at line 19 of file trajectory_base.cpp.
References NodeLinked< WolfProblem, FrameBase >::removeDownNode().
FrameBaseList * TrajectoryBase::getFrameListPtr ()
Returns a pointer to Frame list
Definition at line 24 of file trajectory_base.cpp.
References NodeLinked< WolfProblem, FrameBase >::getDownNodeListPtr().
Referenced by CeresManager::computeCovariances(), getConstraintList(), FrameBase::getNextFrame(), and FrameBase::getPreviousFrame().
FrameBase * TrajectoryBase::getLastFramePtr ()
Returns a pointer to last Frame
Definition at line 29 of file trajectory_base.cpp.
References NodeLinked< WolfProblem, FrameBase >::getDownNodeListPtr().
Referenced by WolfProblem::getLastFramePtr().
void TrajectoryBase::getConstraintList (ConstraintBaseList & _ctr_list)
Returns a list of all constraints in the trajectory thru reference
Definition at line 34 of file trajectory_base.cpp.
References getFrameListPtr().
Referenced by SolverManager::update(), CeresManager::update(), and SolverQR::update().
Field Documentation
unsigned int TrajectoryBase::fixed_size_ protected
Definition at line 28 of file trajectory_base.h.
The documentation for this class was generated from the following files:
trajectory_base.h
trajectory_base.cpp