WOLF: ConstraintBase Class Reference
ConstraintBase Class Reference abstract
#include <constraint_base.h>
Public Member Functions
ConstraintBase (FeatureBase *_ftr_ptr, ConstraintType _tp)
Constructor.
virtual ~ConstraintBase ()
Destructor.
ConstraintType getConstraintType () const
Returns the constraint type.
virtual const std::vector
< WolfScalar * > getStateBlockPtrVector ()=0
Returns a vector of scalar pointers to the first element of all state blocks involved in the constraint.
virtual const std::vector
< StateBase * > getStatePtrVector () const =0
Returns a vector of pointers to the states.
const Eigen::VectorXs & getMeasurement ()
Returns a pointer to the feature measurement.
FeatureBase * getFeaturePtr () const
Returns a pointer to its capture.
CaptureBase * getCapturePtr () const
Returns a pointer to its capture.
virtual unsigned int getSize () const =0
Returns the constraint residual size.
Public Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FeatureBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
ConstraintType type_
const Eigen::VectorXs & measurement_
const Eigen::MatrixXs & measurement_covariance_
Protected Attributes inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef FeatureBase * UpperNodePtr
typedef NodeTerminus * LowerNodePtr
Protected Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 19 of file constraint_base.h.
Constructor & Destructor Documentation
ConstraintBase::ConstraintBase (FeatureBase * _ftr_ptr, ConstraintType _tp)
Constructor
Definition at line 3 of file constraint_base.cpp.
ConstraintBase::~ConstraintBase () virtual
Destructor
Definition at line 12 of file constraint_base.cpp.
Member Function Documentation
ConstraintType ConstraintBase::getConstraintType () const
Returns the constraint type
Definition at line 17 of file constraint_base.cpp.
References type_.
Referenced by SolverManager::createCostFunction(), CeresManager::createCostFunction(), and SolverQR::createCostFunction().
virtual const std::vector<WolfScalar*> ConstraintBase::getStateBlockPtrVector () pure virtual
Returns a vector of scalar pointers to the first element of all state blocks involved in the constraint.
Implemented in ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >, ConstraintSparse< 2, 2 >, ConstraintSparse< 3, 2, 1 >, ConstraintSparse< 3, 2, 1, 2, 1, 2, 1 >, ConstraintSparse< 2, 2, 2, 2, 2 >, ConstraintSparse< 2, 2, 1, 2, 1 >, ConstraintSparse< 3, 2, 2, 2, 2 >, and ConstraintSparse< 3, 2, 1, 2, 1 >.
Referenced by CeresManager::addConstraint().
virtual const std::vector<StateBase*> ConstraintBase::getStatePtrVector () const pure virtual
Returns a vector of pointers to the state in which this constraint depends
Implemented in ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >, ConstraintSparse< 2, 2 >, ConstraintSparse< 3, 2, 1 >, ConstraintSparse< 3, 2, 1, 2, 1, 2, 1 >, ConstraintSparse< 2, 2, 2, 2, 2 >, ConstraintSparse< 2, 2, 1, 2, 1 >, ConstraintSparse< 3, 2, 2, 2, 2 >, and ConstraintSparse< 3, 2, 1, 2, 1 >.
Referenced by SolverQR::addConstraint(), and SolverQR::findFirstOrderedNode().
const Eigen::VectorXs & ConstraintBase::getMeasurement ()
Returns a pointer to the feature measurement
Definition at line 22 of file constraint_base.cpp.
References measurement_.
FeatureBase * ConstraintBase::getFeaturePtr () const
Returns a pointer to its capture
Definition at line 27 of file constraint_base.cpp.
References NodeLinked< FeatureBase, NodeTerminus >::upperNodePtr().
CaptureBase * ConstraintBase::getCapturePtr () const
Returns a pointer to its capture
Definition at line 32 of file constraint_base.cpp.
References NodeLinked< FeatureBase, NodeTerminus >::upperNodePtr(), and NodeLinked< UpperType, LowerType >::upperNodePtr().
Referenced by ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
virtual unsigned int ConstraintBase::getSize () const pure virtual
Returns the constraint residual size
Implemented in ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >, ConstraintSparse< 2, 2 >, ConstraintSparse< 3, 2, 1 >, ConstraintSparse< 3, 2, 1, 2, 1, 2, 1 >, ConstraintSparse< 2, 2, 2, 2, 2 >, ConstraintSparse< 2, 2, 1, 2, 1 >, ConstraintSparse< 3, 2, 2, 2, 2 >, and ConstraintSparse< 3, 2, 1, 2, 1 >.
Referenced by SolverQR::addConstraint().
Field Documentation
ConstraintType ConstraintBase::type_ protected
Definition at line 22 of file constraint_base.h.
Referenced by getConstraintType().
const Eigen::VectorXs& ConstraintBase::measurement_ protected
Definition at line 23 of file constraint_base.h.
Referenced by getMeasurement(), ConstraintTwist2DTheta::operator()(), ConstraintFix::operator()(), ConstraintOdom2DTheta::operator()(), ConstraintOdom2DComplexAngle::operator()(), ConstraintGPS2D::operator()(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
const Eigen::MatrixXs& ConstraintBase::measurement_covariance_ protected
Definition at line 24 of file constraint_base.h.
Referenced by ConstraintTwist2DTheta::operator()(), ConstraintFix::operator()(), ConstraintOdom2DComplexAngle::operator()(), ConstraintOdom2DTheta::operator()(), ConstraintGPS2D::operator()(), ConstraintContainer::operator()(), and ConstraintCorner2DTheta::operator()().
The documentation for this class was generated from the following files:
constraint_base.h
constraint_base.cpp