WOLF: Capture Class Reference
Capture Class Reference
Base class for raw data captures from sensors.
#include <capture.h>
Public Member Functions
void linkToFrame (const FrameShPtr &_frm_ptr)
Set link to Frame.
const FramePtr framePtr () const
Gets up_node_ptr_.
const Frame & frame () const
Gets a reference of Frame.
void addFeature (const FeatureShPtr &_f_ptr)
Adds a Feature to the down node list.
const FeatureList & featureList () const
Gets a const reference to feature list.
const RawShPtr & rawShPtr () const
Gets a const ref to Raw shared pointer.
const RawPtr rawPtr () const
Gets a const pointer to Raw.
void setRaw (const RawShPtr &_raw_sh_ptr)
Sets Raw pointer from a shared pointer.
SensorPtr sensorPtr ()
Gets a pointer to SensorBase.
SensorBase & sensor ()
const SensorPtr sensorPtr () const
const SensorBase & sensor () const
void precomputeConstants ()
pre-compute constants affecting the current node.
void precomputeGlobalPose ()
const StatePose & globalPose () const
const StatePose & inverseGlobalPose () const
bool existsTransSensor (unsigned int _capture_other_id) const
std::pair< TransSensorIter, bool > addTransSensor (unsigned int _capture_other_id, const TransSensorShPtr &_trans_senspr_sh_ptr)
const TransSensorPtr transSensorPtr (unsigned int _capture_other_id) const
Get the TransSensor pointer corresponding to an ID key.
unsigned int removeTransSensor (unsigned int _capture_other_id)
Erases elements according to the provided key.
virtual void processCapture ()
Generic processing from raw to features.
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeConstrainer< Frame, FeatureBase >
unsigned int computeDimError ()
Compute dim_error_ (recursive)
unsigned int dimError () const
Returns dim_error_.
unsigned int remap (Eigen::VectorXs &_storage, unsigned int _idx)
Remaps error_ vector recursively.
unsigned int remap (WolfScalar *_storage, unsigned int _idx)
Remaps error_ vector recursively.
virtual void computeError ()
Compute the error of the node (recursive)
virtual void computeError (Eigen::VectorXs &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (Eigen::Map< Eigen::VectorXs > &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (WolfScalar *_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual const Eigen::Map
< Eigen::VectorXs > & error () const
Gets a reference to the error of the node.
Public Member Functions inherited from NodeLinked< Frame, FeatureBase >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Protected Member Functions
Capture (const FrameShPtr &_frm_ptr, const SensorShPtr &_sen_ptr, const NodeLocation _loc=MID)
Constructor.
virtual ~Capture ()
Destructor.
Protected Member Functions inherited from NodeConstrainer< Frame, FeatureBase >
NodeConstrainer (const NodeLocation _loc, const std::string &_label)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< Frame, FeatureBase >::UpNodeShPtr &_up_node_ptr)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< Frame, FeatureBase >::UpNodeShPtr &_up_node_ptr, unsigned int _dim_error)
virtual ~NodeConstrainer ()
Protected Member Functions inherited from NodeLinked< Frame, FeatureBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const Frame & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes
RawShPtr raw_sh_ptr_
Pointer to raw data. This Capture is owner of raw data.
SensorPtr sensor_ptr_
Pointer to sensor.
StatePose global_pose_
Global sensor pose, the composition of the frame pose and the sensor pose.
StatePose inverse_global_pose_
inverse global sensor pose
Protected Attributes inherited from NodeConstrainer< Frame, FeatureBase >
unsigned int dim_error_
Eigen::Map< Eigen::VectorXs > error_
Additional Inherited Members
Protected Types inherited from NodeLinked< Frame, FeatureBase >
typedef Frame * UpNodePtr
typedef FeatureBase * DownNodePtr
typedef std::shared_ptr< Frame > UpNodeShPtr
typedef std::shared_ptr
< FeatureBase > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Detailed Description
Raw data captured by sensors, and links to the sensors parameters, are collected in this class.
The idea is to have an object Sensor for each physical sensor, several objects FeatureManager to process the captured data, and one Capture object for each actual raw data captured by the sensor. In the case of trajectories, a number of captures are active inside a sliding window of key-frames. In this context, usually each key-frame has at least one sensor capture, but it is allowed to have more than one (from different sensors fired at the same time-stamp of the Frame).
One object Capture has:
Raw data,
A pointer to the Sensor that captured the data
A pointer to the Frame owning it (one level up in the Wolf tree).
A std::list of features (points, lines, GPS pseudo-ranges, or whatsoever), the result of interpreting the raw data (one level down in the Wolf tree).
See RawBase for a rationale on raw data.
See SensorBase for a rationale on sensor devices.
See Frame for a rationale on frames and key-frames.
See FeatureBase for a rationale on features.
Definition at line 58 of file capture.h.
Constructor & Destructor Documentation
Capture::Capture (const FrameShPtr & _frm_ptr, const SensorShPtr & _sen_ptr, const NodeLocation _loc = MID) protected
Parameters
_frm_ptr a shared pointer to the Frame up node
_sen_ptr a shared pointer to the sensor that captured the data
_loc the location in the Wolf tree (TOP, MID or BOTTOM, it defaults to MID)
Definition at line 203 of file capture.h.
Capture::~Capture () protected virtual
Destructor
Definition at line 210 of file capture.h.
Member Function Documentation
void Capture::linkToFrame (const FrameShPtr & _frm_ptr) inline
Set link to Frame
Definition at line 215 of file capture.h.
References NodeLinked< Frame, FeatureBase >::linkToUpNode().
const FramePtr Capture::framePtr () const inline
Gets up_node_ptr_, which is a pointer to the Frame owning of this Capture
Definition at line 220 of file capture.h.
References NodeLinked< Frame, FeatureBase >::upNodePtr().
Referenced by frame(), and precomputeGlobalPose().
const Frame & Capture::frame () const inline
Gets a reference of the Frame owning of this Capture
Definition at line 225 of file capture.h.
References framePtr().
void Capture::addFeature (const FeatureShPtr & _f_ptr) inline
Adds a Feature to the down node list
Definition at line 230 of file capture.h.
References NodeLinked< Frame, FeatureBase >::addDownNode().
const FeatureList & Capture::featureList () const inline
Gets a const reference to feature list
Definition at line 235 of file capture.h.
References NodeLinked< Frame, FeatureBase >::downNodeList().
const RawShPtr & Capture::rawShPtr () const inline
Gets a const ref to Raw shared pointer
Definition at line 240 of file capture.h.
References raw_sh_ptr_.
const RawPtr Capture::rawPtr () const inline
Gets a const pointer to Raw
Definition at line 245 of file capture.h.
References raw_sh_ptr_.
void Capture::setRaw (const RawShPtr & _raw_sh_ptr) inline
Sets Raw pointer from a shared pointer
Definition at line 250 of file capture.h.
References raw_sh_ptr_.
SensorPtr Capture::sensorPtr () inline
Gets a pointer to SensorBase
Definition at line 255 of file capture.h.
References sensor_ptr_.
SensorBase & Capture::sensor () inline
Definition at line 260 of file capture.h.
References sensor_ptr_.
const SensorPtr Capture::sensorPtr () const inline
Definition at line 265 of file capture.h.
References sensor_ptr_.
const SensorBase & Capture::sensor () const inline
Definition at line 270 of file capture.h.
References sensor_ptr_.
void Capture::precomputeConstants () inline virtual
This function pre-computes a number of constants to be reused by all the children of the node. Usually, this pre-computation must be done each time the state vector changes, that is, at each iteration of the optimizer.
Reimplemented from NodeConstrainer< Frame, FeatureBase >.
Definition at line 275 of file capture.h.
References precomputeGlobalPose().
void Capture::precomputeGlobalPose () inline
Definition at line 282 of file capture.h.
References Wolf::composeFrames(), framePtr(), global_pose_, StatePose::inverse(), inverse_global_pose_, SensorBase::pose(), and sensor_ptr_.
Referenced by precomputeConstants().
const StatePose & Capture::globalPose () const inline
Definition at line 288 of file capture.h.
References global_pose_.
Referenced by EpipolarConstraint::computeExpectation(), and TransSensor::precomputePoseRelative().
const StatePose & Capture::inverseGlobalPose () const inline
Definition at line 293 of file capture.h.
References inverse_global_pose_.
Referenced by EpipolarConstraint::computeExpectation(), and TransSensor::precomputePoseRelative().
bool Capture::existsTransSensor (unsigned int _capture_other_id) const inline
Definition at line 298 of file capture.h.
std::pair< TransSensorIter, bool > Capture::addTransSensor (unsigned int _capture_other_id, const TransSensorShPtr & _trans_senspr_sh_ptr) inline
Definition at line 303 of file capture.h.
const TransSensorPtr Capture::transSensorPtr (unsigned int _capture_other_id) const inline
Parameters
_capture_other_id the TransSensor identifier
Returns
the TransSensor pointer. Return NULL if TransSensor ID is not found.
Get the TransSensor pointer corresponding to an ID key.
Definition at line 309 of file capture.h.
Referenced by EpipolarConstraint::computeExpectation().
unsigned int Capture::removeTransSensor (unsigned int _capture_other_id) inline
Parameters
_capture_other_id Key of element to be erased.
Returns
The number of elements erased.
This function erases all the elements located by the given key from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 323 of file capture.h.
void Capture::processCapture () inline virtual
Generic processing from raw to features.
Reimplemented in CaptureLaser2D.
Definition at line 328 of file capture.h.
void Capture::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from NodeConstrainer< Frame, FeatureBase >.
Definition at line 333 of file capture.h.
References SensorBase::intrinsic(), SensorBase::pose(), Node::printNTabs(), NodeConstrainer< UpperType, LowerType >::printSelf(), sensor_ptr_, and StateBase::x().
Field Documentation
RawShPtr Capture::raw_sh_ptr_ protected
Definition at line 62 of file capture.h.
Referenced by rawPtr(), rawShPtr(), and setRaw().
SensorPtr Capture::sensor_ptr_ protected
Definition at line 63 of file capture.h.
Referenced by precomputeGlobalPose(), printSelf(), sensor(), and sensorPtr().
StatePose Capture::global_pose_ protected
Definition at line 64 of file capture.h.
Referenced by globalPose(), and precomputeGlobalPose().
StatePose Capture::inverse_global_pose_ protected
Definition at line 65 of file capture.h.
Referenced by inverseGlobalPose(), and precomputeGlobalPose().
The documentation for this class was generated from the following file:
capture.h