WOLF: TransSensor Class Reference
TransSensor Class Reference abstract
#include <trans_sensor.h>
Public Member Functions
TransSensor (const CapturePtr &_capt_own_ptr, const CapturePtr &_capt_other_ptr)
virtual ~TransSensor ()
void precomputePoseRelative ()
const StatePose & poseRelative () const
virtual void precomputeConstants ()=0
virtual void computeExpectation (const Eigen::VectorXs &_measurement_other, Eigen::VectorXs &_expectation) const =0
Protected Attributes
CapturePtr capt_own_ptr_
Pointer to the Capture owning this.
CapturePtr capt_other_ptr_
Pointer to the other Capture.
StatePose pose_other_to_own_
The relative pose between captures, "other - to - this".
Detailed Description
Definition at line 13 of file trans_sensor.h.
Constructor & Destructor Documentation
TransSensor::TransSensor (const CapturePtr & _capt_own_ptr, const CapturePtr & _capt_other_ptr) inline
Definition at line 54 of file trans_sensor.h.
TransSensor::~TransSensor () inline virtual
Definition at line 62 of file trans_sensor.h.
Member Function Documentation
void TransSensor::precomputePoseRelative () inline
Definition at line 66 of file trans_sensor.h.
References capt_other_ptr_, capt_own_ptr_, Wolf::composeFrames(), Capture::globalPose(), Capture::inverseGlobalPose(), and pose_other_to_own_.
Referenced by TransPinHole::precomputeConstants().
const StatePose & TransSensor::poseRelative () const inline
Definition at line 71 of file trans_sensor.h.
References pose_other_to_own_.
Referenced by TransPinHole::precomputeConstants().
virtual void TransSensor::precomputeConstants () pure virtual
Compute reusable constant parameters forms from the set of parameters of both sensors.
These parameter forms remain constant as long as the relative pose between captures does not change.
Implemented in TransPinHole.
virtual void TransSensor::computeExpectation (const Eigen::VectorXs & _measurement_other, Eigen::VectorXs & _expectation) const pure virtual
Compute the expectation of a measurement in the own sensor of a feature that was observed in the other sensor.
Parameters
_measurement_other the measurement in the other sensor.
_expectation the expected measurement in the own sensor. This is the return value.
Implemented in TransPinHole.
Referenced by EpipolarConstraint::computeExpectation().
Field Documentation
CapturePtr TransSensor::capt_own_ptr_ protected
Definition at line 17 of file trans_sensor.h.
Referenced by precomputePoseRelative().
CapturePtr TransSensor::capt_other_ptr_ protected
Definition at line 18 of file trans_sensor.h.
Referenced by precomputePoseRelative().
StatePose TransSensor::pose_other_to_own_ protected
Definition at line 19 of file trans_sensor.h.
Referenced by poseRelative(), and precomputePoseRelative().
The documentation for this class was generated from the following file:
trans_sensor.h