WOLF: StateErrorPose Class Reference
StateErrorPose Class Reference
#include <state_error_pose.h>
Public Member Functions
StateErrorPose (unsigned int _size_nom, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_xn, unsigned int _size_err)
StateErrorPose (unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_xn, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n)
virtual ~StateErrorPose ()
void pn (Eigen::Vector3s &_p_n)
Eigen::Map< Eigen::Vector3s > & pn ()
void qn (Eigen::Quaternions &_q_n)
Eigen::Map< Eigen::Quaternions > & qn ()
Eigen::Map< Eigen::Vector3s > & pe ()
Eigen::Map< Eigen::Vector3s > & qe ()
Eigen::Map< Eigen::Vector3s > & pc ()
Eigen::Map< Eigen::Quaternions > & qc ()
void compose ()
Public Member Functions inherited from StateError
StateError (const unsigned int _size_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
virtual ~StateError ()
Eigen::VectorXs & xn ()
const Eigen::VectorXs & xn () const
Eigen::Map< Eigen::VectorXs > & xe ()
const Eigen::Map
< Eigen::VectorXs > & xe () const
Eigen::VectorXs & xc ()
const Eigen::VectorXs & xc () const
void clearError ()
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
virtual Eigen::Map
< Eigen::VectorXs > & x ()=0
Force implementation of a state getter and make this class Abstract.
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
unsigned int size ()
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Definition at line 13 of file state_error_pose.h.
Constructor & Destructor Documentation
StateErrorPose::StateErrorPose (unsigned int _size_nom, unsigned int _size_err)
Default Local constructor
All states initialized to zero.
Definition at line 13 of file state_error_pose.cpp.
References compose().
StateErrorPose::StateErrorPose (Eigen::VectorXs & _xn, unsigned int _size_err)
Local Constructor from nominal state.
Parameters
_xn the nominal state vector
_size_err The size of the error state
Error state always initialized to zero.
StateErrorPose::StateErrorPose (unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s & _p_n, Eigen::Quaternions & _q_n)
Local Constructor from nominal states.
Parameters
_size_nom the size of the nominal state
_size_err the size of the error state
_p_n the nominal position
_q_n the nominal quaternion
Error states always initialized to zero.
Definition at line 39 of file state_error_pose.cpp.
References compose().
StateErrorPose::StateErrorPose (Eigen::VectorXs & _storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err)
Default Remote constructor
Parameters
_size_nom the size of the nominal state
_size_err the size of the error state
_storage the remote storage vector
_idx index to the remote storage where the error state will map
All states initialized to zero.
StateErrorPose::StateErrorPose (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _xn, unsigned int _size_err)
Remote Constructor from nominal state.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_xn the nominal state vector
_size_err the size of the error state
Error state initialized to zero.
StateErrorPose::StateErrorPose (Eigen::VectorXs & _storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s & _p_n, Eigen::Quaternions & _q_n)
Remote Constructor from nominal states.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_size_nom the size of the nominal state
_size_err the size of the error state
_p_n the nominal position
_q_n the nominal quaternion
Error states initialized to zero.
StateErrorPose::~StateErrorPose () virtual
Default destructor
Definition at line 91 of file state_error_pose.cpp.
Member Function Documentation
void StateErrorPose::pn (Eigen::Vector3s & _p_n) inline
Set nominal position
Parameters
_p_n the nominal position
Definition at line 156 of file state_error_pose.h.
Eigen::Map< Eigen::Vector3s > & StateErrorPose::pn () inline
Get reference to nominal position
Definition at line 151 of file state_error_pose.h.
Referenced by StateErrorPQV::compose().
void StateErrorPose::qn (Eigen::Quaternions & _q_n) inline
Set nominal quaternion
Parameters
_q_n the nominal quaternion
Definition at line 166 of file state_error_pose.h.
Eigen::Map< Eigen::Quaternions > & StateErrorPose::qn () inline
Get reference to nominal quaternion
Definition at line 161 of file state_error_pose.h.
Referenced by StateErrorPQV::compose(), and StateErrorPQV::StateErrorPQV().
Eigen::Map< Eigen::Vector3s > & StateErrorPose::pe () inline
Get reference to position error
Definition at line 171 of file state_error_pose.h.
Referenced by StateErrorPQV::compose().
Eigen::Map< Eigen::Vector3s > & StateErrorPose::qe () inline
Get reference to orientation error
Definition at line 176 of file state_error_pose.h.
Referenced by StateErrorPQV::compose().
Eigen::Map< Eigen::Vector3s > & StateErrorPose::pc () inline
Get reference to composed position
Definition at line 181 of file state_error_pose.h.
References compose().
Referenced by StateErrorPQV::compose().
Eigen::Map< Eigen::Quaternions > & StateErrorPose::qc () inline
Get reference to composed quaternion
Definition at line 187 of file state_error_pose.h.
References compose().
Referenced by StateErrorPQV::compose().
void StateErrorPose::compose () virtual
Compose nominal and error states.
Implements StateError.
Reimplemented in StateErrorPQV.
Definition at line 95 of file state_error_pose.cpp.
References Wolf::quaternionFromVector().
Referenced by pc(), qc(), and StateErrorPose().
The documentation for this class was generated from the following files:
state_error_pose.h
state_error_pose.cpp