WOLF: Frame Class Reference
Frame Class Reference
#include <frame.h>
Public Member Functions
Frame (const VehicleShPtr &_vehicle_ptr, const StateShPtr &_state_ptr, const TimeStamp &_ts, FrameType _ft=KEY_FRAME, const NodeLocation _loc=MID)
Constructor.
virtual ~Frame ()
Destructor.
void addCapture (const CaptureShPtr &_sc_ptr)
const CaptureList & captureList () const
const StateShPtr & stateShPtr () const
const StatePtr statePtr () const
const StatePose & state () const
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeConstrainer< VehicleBase, Capture >
unsigned int computeDimError ()
Compute dim_error_ (recursive)
unsigned int dimError () const
Returns dim_error_.
unsigned int remap (Eigen::VectorXs &_storage, unsigned int _idx)
Remaps error_ vector recursively.
unsigned int remap (WolfScalar *_storage, unsigned int _idx)
Remaps error_ vector recursively.
virtual void computeError ()
Compute the error of the node (recursive)
virtual void computeError (Eigen::VectorXs &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (Eigen::Map< Eigen::VectorXs > &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (WolfScalar *_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual const Eigen::Map
< Eigen::VectorXs > & error () const
Gets a reference to the error of the node.
virtual void precomputeConstants ()
pre-compute constants affecting the current node.
Public Member Functions inherited from NodeLinked< VehicleBase, Capture >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Additional Inherited Members
Protected Types inherited from NodeLinked< VehicleBase, Capture >
typedef VehicleBase * UpNodePtr
typedef Capture * DownNodePtr
typedef std::shared_ptr
< VehicleBase > UpNodeShPtr
typedef std::shared_ptr< Capture > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Protected Member Functions inherited from NodeConstrainer< VehicleBase, Capture >
NodeConstrainer (const NodeLocation _loc, const std::string &_label)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< VehicleBase, Capture >::UpNodeShPtr &_up_node_ptr)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< VehicleBase, Capture >::UpNodeShPtr &_up_node_ptr, unsigned int _dim_error)
virtual ~NodeConstrainer ()
Protected Member Functions inherited from NodeLinked< VehicleBase, Capture >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const VehicleBase & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from NodeConstrainer< VehicleBase, Capture >
unsigned int dim_error_
Eigen::Map< Eigen::VectorXs > error_
Detailed Description
Definition at line 20 of file frame.h.
Constructor & Destructor Documentation
Frame::Frame (const VehicleShPtr & _vehicle_ptr, const StateShPtr & _state_ptr, const TimeStamp & _ts, FrameType _ft = KEY_FRAME, const NodeLocation _loc = MID)
Parameters
_vehicle_ptr a shared pointer to the Vehicle up node
_state_ptr a shared pointer to the state of the vehicle at the time of data capture
_ts The time stamp
_ft the frame type (KEY_FRAME or REGULAR_FRAME, it defaults to KEY_FRAME).
_loc the location in the Wolf tree (TOP, MID or BOTTOM, it defaults to MID)
Definition at line 66 of file frame.h.
Frame::~Frame () virtual
Destructor
Definition at line 75 of file frame.h.
Member Function Documentation
void Frame::addCapture (const CaptureShPtr & _sc_ptr) inline
Definition at line 80 of file frame.h.
References NodeLinked< VehicleBase, Capture >::addDownNode().
const CaptureList & Frame::captureList () const inline
Definition at line 85 of file frame.h.
References NodeLinked< VehicleBase, Capture >::downNodeList().
const StateShPtr & Frame::stateShPtr () const inline
Definition at line 90 of file frame.h.
const StatePtr Frame::statePtr () const inline
Definition at line 95 of file frame.h.
const StatePose & Frame::state () const inline
Definition at line 100 of file frame.h.
void Frame::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from NodeConstrainer< VehicleBase, Capture >.
Definition at line 105 of file frame.h.
References Node::printNTabs(), and NodeConstrainer< UpperType, LowerType >::printSelf().
The documentation for this class was generated from the following file:
frame.h