WOLF: NodeConstrainer< UpperType, LowerType > Class Template Reference
NodeConstrainer< UpperType, LowerType > Class Template Reference
Node Constrainer of the Wolf Tree.
#include <node_constrainer.h>
Public Member Functions
unsigned int computeDimError ()
Compute dim_error_ (recursive)
unsigned int dimError () const
Returns dim_error_.
unsigned int remap (Eigen::VectorXs &_storage, unsigned int _idx)
Remaps error_ vector recursively.
unsigned int remap (WolfScalar *_storage, unsigned int _idx)
Remaps error_ vector recursively.
virtual void computeError ()
Compute the error of the node (recursive)
virtual void computeError (Eigen::VectorXs &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (Eigen::Map< Eigen::VectorXs > &_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual void computeError (WolfScalar *_residuals, unsigned int &_idx)
Compute the error of the node (recursive)
virtual const Eigen::Map
< Eigen::VectorXs > & error () const
Gets a reference to the error of the node.
virtual void precomputeConstants ()
pre-compute constants affecting the current node.
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeLinked< UpperType, LowerType >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Protected Member Functions
NodeConstrainer (const NodeLocation _loc, const std::string &_label)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< UpperType, LowerType >::UpNodeShPtr &_up_node_ptr)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< UpperType, LowerType >::UpNodeShPtr &_up_node_ptr, unsigned int _dim_error)
virtual ~NodeConstrainer ()
Protected Member Functions inherited from NodeLinked< UpperType, LowerType >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const UpperType & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes
unsigned int dim_error_
Eigen::Map< Eigen::VectorXs > error_
Additional Inherited Members
Protected Types inherited from NodeLinked< UpperType, LowerType >
typedef UpperType * UpNodePtr
typedef LowerType * DownNodePtr
typedef std::shared_ptr
< UpperType > UpNodeShPtr
typedef std::shared_ptr
< LowerType > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Detailed Description
template<class UpperType, class LowerType>
class NodeConstrainer< UpperType, LowerType >
Parameters
UpperType the type of node one level up in the Wolf tree.
LowerType the type of node one level down in the Wolf tree.
Node Constrainer of the Wolf Tree.
The vector error_ is the target vector to minimize by an optimizer. It is stored remotely through an Eigen::Map
Definition at line 23 of file node_constrainer.h.
Constructor & Destructor Documentation
template<class UpperType , class LowerType > NodeConstrainer< UpperType, LowerType >::NodeConstrainer (const NodeLocation _loc, const std::string & _label) protected
Definition at line 202 of file node_constrainer.h.
template<class UpperType, class LowerType> NodeConstrainer< UpperType, LowerType >::NodeConstrainer (const NodeLocation _loc, const std::string & _label, const typename NodeConstrainer< UpperType, LowerType >::UpNodeShPtr & _up_node_ptr) protected
Definition at line 191 of file node_constrainer.h.
template<class UpperType, class LowerType> NodeConstrainer< UpperType, LowerType >::NodeConstrainer (const NodeLocation _loc, const std::string & _label, const typename NodeConstrainer< UpperType, LowerType >::UpNodeShPtr & _up_node_ptr, unsigned int _dim_error) protected
Definition at line 179 of file node_constrainer.h.
template<class UpperType , class LowerType > NodeConstrainer< UpperType, LowerType >::~NodeConstrainer () protected virtual
Definition at line 213 of file node_constrainer.h.
Member Function Documentation
template<class UpperType , class LowerType > unsigned int NodeConstrainer< UpperType, LowerType >::computeDimError ()
Recursively traverses all the tree below the current node to compute the total error dim of the node.
Definition at line 219 of file node_constrainer.h.
template<class UpperType , class LowerType > unsigned int NodeConstrainer< UpperType, LowerType >::dimError () const inline
Returns dim_error_
Definition at line 235 of file node_constrainer.h.
template<class UpperType , class LowerType > unsigned int NodeConstrainer< UpperType, LowerType >::remap (Eigen::VectorXs & _storage, unsigned int _idx)
Remaps error_ vector recursively. It will be called when a new node is added to down_node_list_ or recursively by an up node
Parameters
_storage actual vector where data is stored
_idx index from which this map starts
Returns
the new index, pointing to the location next to the last mapped so far (this is to be input to the next remap()).
Definition at line 241 of file node_constrainer.h.
template<class UpperType , class LowerType > unsigned int NodeConstrainer< UpperType, LowerType >::remap (WolfScalar * _storage, unsigned int _idx)
Remaps error_ vector recursively. It will be called when a new node is added to down_node_list_ or recursively by an up node
Parameters
_storage pointer to the actual vector where data is stored
_idx index, after the pointer, from which map starts
Returns
the new index, pointing to the location next to the last mapped so far (this is to be input to the next remap()).
Definition at line 262 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::computeError () inline virtual
Calls computeError() recursively to down nodes, until reaching BOTTOM node, where computeError() is overloaded with the actual computation of its error.
For nodes TOP and MID, this method recursively calls computeError() of down nodes.
For nodes placed at the BOTTOM of the tree, this method needs to be overloaded (see e.g. CorrespondenceBase::computeError()).
The result of this call is placed at the member vector error_, which is an Eigen::Map to an external, contiguous, error_storage vector.
Reimplemented in CorrespondenceBase, and EpipolarConstraint.
Definition at line 285 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::computeError (Eigen::VectorXs & _residuals, unsigned int & _idx) inline virtual
Calls computeError() recursively to down nodes, until reaching BOTTOM node, where computeError() is overloaded with the actual computation of its error.
For nodes TOP and MID, this method recursively calls computeError() of down nodes.
For nodes placed at the BOTTOM of the tree, this method needs to be overloaded (see e.g. CorrespondenceBase::computeError()).
The result of this call is placed at the provided vector _residuals, starting at position _idx and ranging as far as the dimension of the error for the node. The index _idx in incremented by this function to serve as the new index for the following call.
Reimplemented in CorrespondenceBase, and EpipolarConstraint.
Definition at line 294 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::computeError (Eigen::Map< Eigen::VectorXs > & _residuals, unsigned int & _idx) inline virtual
Calls computeError() recursively to down nodes, until reaching BOTTOM node, where computeError() is overloaded with the actual computation of its error.
For nodes TOP and MID, this method recursively calls computeError() of down nodes.
For nodes placed at the BOTTOM of the tree, this method needs to be overloaded (see e.g. CorrespondenceBase::computeError()).
The result of this call is placed at the provided Map<VectorXs> _residuals, starting at position _idx and ranging as far as the dimension of the error for the node. The index _idx in incremented by this function to serve as the new index for the following call.
Reimplemented in CorrespondenceBase, and EpipolarConstraint.
Definition at line 304 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::computeError (WolfScalar * _residuals, unsigned int & _idx) inline virtual
Calls computeError() recursively to down nodes, until reaching BOTTOM node, where computeError() is overloaded with the actual computation of its error.
For nodes TOP and MID, this method recursively calls computeError() of down nodes.
For nodes placed at the BOTTOM of the tree, this method needs to be overloaded (see e.g. CorrespondenceBase::computeError()).
The result of this call is placed at the provided pointer _residuals plus _idx, and ranging as far as the dimension of the error for the node. The index _idx is incremented by this function to serve as the new index for the following call.
Reimplemented in CorrespondenceBase, and EpipolarConstraint.
Definition at line 314 of file node_constrainer.h.
template<class UpperType , class LowerType > const Eigen::Map< Eigen::VectorXs > & NodeConstrainer< UpperType, LowerType >::error () const inline virtual
Gets a reference to the error of the node.
Definition at line 325 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::precomputeConstants () inline virtual
This function pre-computes a number of constants to be reused by all the children of the node. Usually, this pre-computation must be done each time the state vector changes, that is, at each iteration of the optimizer.
Reimplemented in Capture.
Definition at line 331 of file node_constrainer.h.
template<class UpperType , class LowerType > void NodeConstrainer< UpperType, LowerType >::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const inline virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from NodeLinked< UpperType, LowerType >.
Reimplemented in Capture, CorrespondenceBase, FeatureBase, CorrespondenceRelative, and Frame.
Definition at line 340 of file node_constrainer.h.
References Node::printNTabs(), and NodeLinked< UpperType, LowerType >::printSelf().
Referenced by Frame::printSelf(), FeatureBase::printSelf(), CorrespondenceBase::printSelf(), and Capture::printSelf().
Field Documentation
template<class UpperType, class LowerType> unsigned int NodeConstrainer< UpperType, LowerType >::dim_error_ protected
Definition at line 27 of file node_constrainer.h.
template<class UpperType, class LowerType> Eigen::Map<Eigen::VectorXs> NodeConstrainer< UpperType, LowerType >::error_ protected
Definition at line 28 of file node_constrainer.h.
The documentation for this class was generated from the following file:
node_constrainer.h