WOLF: StateErrorPQV Class Reference
StateErrorPQV Class Reference
Error state class for position-velocity-quaternion states.
#include <state_error_pqv.h>
Public Member Functions
StateErrorPQV ()
StateErrorPQV (Eigen::VectorXs &_xn)
StateErrorPQV (Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n, Eigen::Vector3s &_v_n)
StateErrorPQV (Eigen::VectorXs &_storage, unsigned int _idx)
StateErrorPQV (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_xn)
StateErrorPQV (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n, Eigen::Vector3s &_v_n)
virtual ~StateErrorPQV ()
void vn (Eigen::Vector3s &_v_n)
Eigen::Map< Eigen::Vector3s > & vn ()
Eigen::Map< Eigen::Vector3s > & ve ()
Eigen::Map< Eigen::Vector3s > & vc ()
void compose ()
Public Member Functions inherited from StateErrorPose
StateErrorPose (unsigned int _size_nom, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_xn, unsigned int _size_err)
StateErrorPose (unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_xn, unsigned int _size_err)
StateErrorPose (Eigen::VectorXs &_storage, unsigned int _idx, unsigned int _size_nom, unsigned int _size_err, Eigen::Vector3s &_p_n, Eigen::Quaternions &_q_n)
virtual ~StateErrorPose ()
void pn (Eigen::Vector3s &_p_n)
Eigen::Map< Eigen::Vector3s > & pn ()
void qn (Eigen::Quaternions &_q_n)
Eigen::Map< Eigen::Quaternions > & qn ()
Eigen::Map< Eigen::Vector3s > & pe ()
Eigen::Map< Eigen::Vector3s > & qe ()
Eigen::Map< Eigen::Vector3s > & pc ()
Eigen::Map< Eigen::Quaternions > & qc ()
Public Member Functions inherited from StateError
StateError (const unsigned int _size_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
virtual ~StateError ()
Eigen::VectorXs & xn ()
const Eigen::VectorXs & xn () const
Eigen::Map< Eigen::VectorXs > & xe ()
const Eigen::Map
< Eigen::VectorXs > & xe () const
Eigen::VectorXs & xc ()
const Eigen::VectorXs & xc () const
void clearError ()
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
virtual Eigen::Map
< Eigen::VectorXs > & x ()=0
Force implementation of a state getter and make this class Abstract.
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
unsigned int size ()
Static Public Attributes
static const unsigned int SIZE_NOMINAL_ = 10
Size of the nominal state.
static const unsigned int SIZE_ERROR_ = 9
Size of the error state.
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Definition at line 17 of file state_error_pqv.h.
Constructor & Destructor Documentation
StateErrorPQV::StateErrorPQV ()
Default Local constructor
All states initialized to zero.
Definition at line 61 of file state_error_pqv.cpp.
References compose().
StateErrorPQV::StateErrorPQV (Eigen::VectorXs & _xn)
Local Constructor from nominal state.
Parameters
_xn the nominal state vector
Error state always initialized to zero.
Definition at line 52 of file state_error_pqv.cpp.
References compose().
StateErrorPQV::StateErrorPQV (Eigen::Vector3s & _p_n, Eigen::Quaternions & _q_n, Eigen::Vector3s & _v_n)
Local Constructor from nominal states.
Parameters
_p_n the nominal position
_q_n the nominal quaternion
_v_n the nominal velocity
Error states always initialized to zero.
Definition at line 42 of file state_error_pqv.cpp.
References compose(), and StateErrorPose::qn().
StateErrorPQV::StateErrorPQV (Eigen::VectorXs & _storage, unsigned int _idx)
Default Remote constructor
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
All states initialized to zero.
Definition at line 33 of file state_error_pqv.cpp.
References compose().
StateErrorPQV::StateErrorPQV (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _xn)
Remote Constructor from nominal state.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_xn the nominal state vector
Error state initialized to zero.
Definition at line 24 of file state_error_pqv.cpp.
References compose().
StateErrorPQV::StateErrorPQV (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::Vector3s & _p_n, Eigen::Quaternions & _q_n, Eigen::Vector3s & _v_n)
Remote Constructor from nominal states.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_p_n the nominal position
_q_n the nominal quaternion
_v_n the nominal velocity
Error states initialized to zero.
Definition at line 13 of file state_error_pqv.cpp.
References compose().
StateErrorPQV::~StateErrorPQV () inline virtual
Default destructor
Definition at line 129 of file state_error_pqv.h.
Member Function Documentation
void StateErrorPQV::vn (Eigen::Vector3s & _v_n) inline
Set nominal velocity
Parameters
_v_n the nominal velocity
Definition at line 138 of file state_error_pqv.h.
Eigen::Map< Eigen::Vector3s > & StateErrorPQV::vn () inline
Get reference to nominal velocity
Definition at line 133 of file state_error_pqv.h.
Eigen::Map< Eigen::Vector3s > & StateErrorPQV::ve () inline
Get reference to velocity error
Definition at line 143 of file state_error_pqv.h.
Eigen::Map< Eigen::Vector3s > & StateErrorPQV::vc () inline
Get reference to composed velocity
Definition at line 148 of file state_error_pqv.h.
References compose().
void StateErrorPQV::compose () virtual
Compose nominal and error states.
Reimplemented from StateErrorPose.
Definition at line 71 of file state_error_pqv.cpp.
References StateErrorPose::pc(), StateErrorPose::pe(), StateErrorPose::pn(), StateErrorPose::qc(), StateErrorPose::qe(), StateErrorPose::qn(), and Wolf::quaternionFromVector().
Referenced by StateErrorPQV(), and vc().
Field Documentation
const unsigned int StateErrorPQV::SIZE_NOMINAL_ = 10 static
Definition at line 21 of file state_error_pqv.h.
const unsigned int StateErrorPQV::SIZE_ERROR_ = 9 static
Definition at line 22 of file state_error_pqv.h.
The documentation for this class was generated from the following files:
state_error_pqv.h
state_error_pqv.cpp