WOLF: StateError Class Reference
StateError Class Reference abstract
Base class for error states.
#include <state_error.h>
Public Member Functions
StateError (const unsigned int _size_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
virtual ~StateError ()
Eigen::VectorXs & xn ()
const Eigen::VectorXs & xn () const
Eigen::Map< Eigen::VectorXs > & xe ()
const Eigen::Map
< Eigen::VectorXs > & xe () const
Eigen::VectorXs & xc ()
const Eigen::VectorXs & xc () const
void clearError ()
virtual void compose ()=0
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
virtual Eigen::Map
< Eigen::VectorXs > & x ()=0
Force implementation of a state getter and make this class Abstract.
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
unsigned int size ()
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Base class for error states. It implements set/get methods to the nominal, error and composed states. Error states involve implicitly three states:
nominal: the state point from which the error is estimated. It is an Eigen Vector member of this class.
error: the error part, which is usually estimated or optimized. It is the inherited Eigen Map of StateBase class.
composed: It is the composition of both nominal and error, so it is usually the state point to publish. It is an Eigen Vector member of this class.
Definition at line 22 of file state_error.h.
Constructor & Destructor Documentation
StateError::StateError (const unsigned int _size_nominal, const unsigned int _size_error)
Local constructor from sizes
Parameters
_size_nominal size of the nominal state vector
_size_error size of the error state vector
Nominal and error states initialized to zero
Definition at line 12 of file state_error.cpp.
References clearError().
StateError::StateError (const Eigen::VectorXs & _x_nominal, const unsigned int _size_error)
Local constructor from vector and size
Parameters
_x_nominal the nominal state
_size_error the size of the error state
The error state is initialized to zero
StateError::StateError (const Eigen::VectorXs & _x_nominal, const Eigen::VectorXs & _x_error)
Local constructor from vectors
Parameters
_x_nominal the nominal state
_x_error the error state
StateError::StateError (Eigen::VectorXs & _st_remote, const unsigned int _idx, const unsigned int _size_nominal, const unsigned int _size_error)
Remote constructor from sizes
Parameters
_st_remote storage vector
_idx index where the state maps to the remote storage vector
_size_nominal size of the nominal state vector
_size_error size of the error state vector
StateError::StateError (Eigen::VectorXs & _st_remote, const unsigned int _idx, const Eigen::VectorXs & _x_nominal, const unsigned int _size_error)
Remote constructor from vector and size
Parameters
_st_remote storage vector
_idx index where the state maps to the remote storage vector
_x_nominal the nominal state vector
_size_error size of the error state vector
The error state is initialized to zero
StateError::StateError (Eigen::VectorXs & _st_remote, const unsigned int _idx, const Eigen::VectorXs & _x_nominal, const Eigen::VectorXs & _x_error)
Remote constructor from vectors
Parameters
_st_remote storage vector
_idx index where the state maps to the remote storage vector
_x_nominal the nominal state
_x_error the error state
StateError::~StateError () virtual
Definition at line 60 of file state_error.cpp.
Member Function Documentation
Eigen::VectorXs & StateError::xn () inline
Get reference to nominal state
Definition at line 143 of file state_error.h.
const Eigen::VectorXs & StateError::xn () const inline
Get reference to nominal state
Definition at line 138 of file state_error.h.
Eigen::Map< Eigen::VectorXs > & StateError::xe () inline
Get reference to error state
Definition at line 153 of file state_error.h.
References StateRootBase::state_estimated_map_.
const Eigen::Map< Eigen::VectorXs > & StateError::xe () const inline
Get reference to error state
Definition at line 148 of file state_error.h.
References StateRootBase::state_estimated_map_.
Eigen::VectorXs & StateError::xc () inline
Get reference to composed state
Definition at line 163 of file state_error.h.
References compose().
const Eigen::VectorXs & StateError::xc () const inline
Get reference to composed state
Definition at line 158 of file state_error.h.
void StateError::clearError () inline
Clear error. Set it to 0.
Definition at line 169 of file state_error.h.
References StateRootBase::state_estimated_map_.
Referenced by StateError().
virtual void StateError::compose () pure virtual
Compose nominal and error states
Implemented in StateErrorPose, StateErrorIMU, and StateErrorPQV.
Referenced by xc().
The documentation for this class was generated from the following files:
state_error.h
state_error.cpp