WOLF: CaptureTwist2D Class Reference
CaptureTwist2D Class Reference
#include <capture_twist_2D.h>
Public Member Functions
CaptureTwist2D (const TimeStamp &_init_ts, SensorTwist2D *_sensor_ptr)
CaptureTwist2D (const TimeStamp &_init_ts, SensorTwist2D *_sensor_ptr, const Eigen::Vector3s &_data)
CaptureTwist2D (const TimeStamp &_init_ts, SensorTwist2D *_sensor_ptr, const Eigen::Vector3s &_data, const Eigen::Matrix3s &_data_covariance)
virtual ~CaptureTwist2D ()
virtual void processCapture ()
virtual Eigen::VectorXs computePrior (const TimeStamp &_now) const
virtual void addConstraints ()
virtual void integrateCapture (CaptureRelative *_new_capture)
virtual CaptureTwist2D * interpolateCapture (const TimeStamp &_ts)
Public Member Functions inherited from CaptureRelative
CaptureRelative (const TimeStamp &_init_ts, const TimeStamp &_final_ts, SensorBase *_sensor_ptr)
CaptureRelative (const TimeStamp &_init_ts, const TimeStamp &_final_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data)
CaptureRelative (const TimeStamp &_init_ts, const TimeStamp &_final_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data, const Eigen::MatrixXs &_data_covariance)
virtual ~CaptureRelative ()
TimeStamp getInitTimeStamp () const
TimeStamp getFinalTimeStamp () const
void setInitTimeStamp (const TimeStamp &_ts)
void setFinalTimeStamp (const TimeStamp &_ts)
Public Member Functions inherited from CaptureBase
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data)
CaptureBase (const TimeStamp &_ts, SensorBase *_sensor_ptr, const Eigen::VectorXs &_data, const Eigen::MatrixXs &_data_covariance)
virtual ~CaptureBase ()
void linkToFrame (FrameBase *_frm_ptr)
Set link to Frame.
void addFeature (FeatureBase *_ft_ptr)
Adds a Feature to the down node list.
FrameBase * getFramePtr () const
Gets up_node_ptr_.
FeatureBaseList * getFeatureListPtr ()
Gets a pointer to feature list.
void getConstraintList (ConstraintBaseList &_ctr_list)
Fills the provided list with all constraints related to this capture.
TimeStamp getTimeStamp () const
SensorBase * getSensorPtr () const
SensorType getSensorType () const
void setTimeStamp (const TimeStamp &_ts)
void setTimeStampToNow ()
Eigen::VectorXs getData ()
Eigen::MatrixXs getDataCovariance ()
void setData (unsigned int _size, const WolfScalar *_data)
void setData (const Eigen::VectorXs &_data)
void setDataCovariance (const Eigen::MatrixXs &_data_cov)
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FrameBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Additional Inherited Members
Public Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef FrameBase * UpperNodePtr
typedef FeatureBase * LowerNodePtr
Protected Types inherited from NodeLinked< FrameBase, FeatureBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FrameBase, FeatureBase >
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from CaptureRelative
TimeStamp final_time_stamp_
Final Time stamp.
Protected Attributes inherited from CaptureBase
TimeStamp time_stamp_
Time stamp.
SensorBase * sensor_ptr_
Pointer to sensor.
Eigen::VectorXs data_
raw data
Eigen::MatrixXs data_covariance_
Noise of the capture.
Eigen::Vector3s sensor_pose_global_
Sensor pose in world frame: composition of the frame pose and the sensor pose. TODO: use state units.
Eigen::Vector3s inverse_sensor_pose_
World pose in the sensor frame: inverse of the global_pose_. TODO: use state units.
Protected Attributes inherited from NodeLinked< FrameBase, FeatureBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 13 of file capture_twist_2D.h.
Constructor & Destructor Documentation
CaptureTwist2D::CaptureTwist2D (const TimeStamp & _init_ts, SensorTwist2D * _sensor_ptr)
CaptureTwist2D::CaptureTwist2D (const TimeStamp & _init_ts, SensorTwist2D * _sensor_ptr, const Eigen::Vector3s & _data)
CaptureTwist2D::CaptureTwist2D (const TimeStamp & _init_ts, SensorTwist2D * _sensor_ptr, const Eigen::Vector3s & _data, const Eigen::Matrix3s & _data_covariance)
CaptureTwist2D::~CaptureTwist2D () virtual
Definition at line 25 of file capture_twist_2D.cpp.
Member Function Documentation
void CaptureTwist2D::processCapture () inline virtual
Reimplemented from CaptureBase.
Definition at line 30 of file capture_twist_2D.cpp.
References addConstraints(), CaptureBase::addFeature(), CaptureBase::data_, and CaptureBase::data_covariance_.
Eigen::VectorXs CaptureTwist2D::computePrior (const TimeStamp & _now) const virtual
Implements CaptureBase.
Definition at line 39 of file capture_twist_2D.cpp.
References CaptureBase::data_, CaptureBase::getFramePtr(), FrameBase::getOPtr(), StateBase::getStateType(), ST_COMPLEX_ANGLE, CaptureBase::time_stamp_, and NodeLinked< FrameBase, FeatureBase >::up_node_ptr_.
void CaptureTwist2D::addConstraints () virtual
Definition at line 76 of file capture_twist_2D.cpp.
References CaptureBase::getFeatureListPtr(), CaptureBase::getFramePtr(), FrameBase::getNextFrame(), and ST_COMPLEX_ANGLE.
Referenced by processCapture().
void CaptureTwist2D::integrateCapture (CaptureRelative * _new_capture) virtual
Implements CaptureRelative.
Definition at line 100 of file capture_twist_2D.cpp.
References CaptureBase::data_, CaptureBase::data_covariance_, CaptureRelative::final_time_stamp_, CaptureBase::getData(), CaptureBase::getDataCovariance(), and CaptureBase::getFeatureListPtr().
CaptureOdom2D * CaptureTwist2D::interpolateCapture (const TimeStamp & _ts) virtual
Implements CaptureRelative.
Definition at line 119 of file capture_twist_2D.cpp.
References CaptureBase::data_, CaptureBase::data_covariance_, CaptureRelative::final_time_stamp_, TimeStamp::get(), and CaptureBase::sensor_ptr_.
The documentation for this class was generated from the following files:
capture_twist_2D.h
capture_twist_2D.cpp