WOLF: CorrespondenceRelative Class Reference
CorrespondenceRelative Class Reference
Relative constraint between two corresponding features.
#include <correspondence_relative.h>
Public Member Functions
CorrespondenceRelative (const FeatureShPtr &_ft_ptr, const FeatureShPtr &_ft_other_ptr, unsigned int _dim_error, unsigned int _dim_expectation)
virtual ~CorrespondenceRelative ()
const StatePtr stateOtherPtr () const
const StatePose & stateOther () const
const CapturePtr captureOtherPtr () const
const Capture & captureOther () const
const SensorPtr sensorOtherPtr () const
const SensorBase & sensorOther () const
const FeaturePtr featureOtherPtr () const
const FeatureBase & featureOther () const
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from CorrespondenceBase
CorrespondenceBase (const unsigned int &_measurement_size)
virtual ~CorrespondenceBase ()
virtual void inventMeasurement (const VectorXs &_measurement, std::default_random_engine &_generator, std::normal_distribution< WolfScalar > &_distribution)
virtual correspondenceType getType () const =0
virtual WolfScalar ** getBlockPtrArray ()=0
virtual const std::vector
< WolfScalar * > getBlockPtrVector ()=0
CorrespondenceBase (const unsigned int &_measurement_size)
virtual ~CorrespondenceBase ()
virtual void inventMeasurement (const VectorXs &_measurement, std::default_random_engine &_generator, std::normal_distribution< WolfScalar > &_distribution)
void linkToFeature (const FeatureShPtr &_ft_ptr)
const FeaturePtr featurePtr () const
const FeatureBase & feature () const
const CapturePtr capturePtr () const
const Capture & capture () const
const SensorPtr sensorPtr () const
const SensorBase & sensor () const
const StatePtr statePtr () const
const StatePose & state () const
const Eigen::VectorXs & expectation () const
virtual void computeExpectation ()=0
Compute measurement expectation.
virtual void computeError ()
Compute error of this correspondence (non recursive)
virtual void computeError (Eigen::VectorXs &_residuals, unsigned int &_idx)
Compute error of this correspondence (non recursive)
virtual void computeError (Eigen::Map< Eigen::VectorXs > &_residuals, unsigned int &_idx)
Compute error of this correspondence (non recursive)
virtual void computeError (WolfScalar *_residuals, unsigned int &_idx)
Compute error of this correspondence (non recursive)
Public Member Functions inherited from NodeConstrainer< FeatureBase, NodeTerminus >
unsigned int computeDimError ()
Compute dim_error_ (recursive)
unsigned int dimError () const
Returns dim_error_.
unsigned int remap (Eigen::VectorXs &_storage, unsigned int _idx)
Remaps error_ vector recursively.
unsigned int remap (WolfScalar *_storage, unsigned int _idx)
Remaps error_ vector recursively.
virtual const Eigen::Map
< Eigen::VectorXs > & error () const
Gets a reference to the error of the node.
virtual void precomputeConstants ()
pre-compute constants affecting the current node.
Public Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Additional Inherited Members
Protected Types inherited from NodeLinked< FeatureBase, NodeTerminus >
typedef FeatureBase * UpNodePtr
typedef NodeTerminus * DownNodePtr
typedef std::shared_ptr
< FeatureBase > UpNodeShPtr
typedef std::shared_ptr
< NodeTerminus > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Protected Member Functions inherited from CorrespondenceBase
CorrespondenceBase (const FeatureShPtr &_ft_ptr, unsigned int _dim_error, unsigned int _dim_expectation)
Constructor.
virtual ~CorrespondenceBase ()
Protected Member Functions inherited from NodeConstrainer< FeatureBase, NodeTerminus >
NodeConstrainer (const NodeLocation _loc, const std::string &_label)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< FeatureBase, NodeTerminus >::UpNodeShPtr &_up_node_ptr)
NodeConstrainer (const NodeLocation _loc, const std::string &_label, const typename NodeConstrainer< FeatureBase, NodeTerminus >::UpNodeShPtr &_up_node_ptr, unsigned int _dim_error)
virtual ~NodeConstrainer ()
Protected Member Functions inherited from NodeLinked< FeatureBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const FeatureBase & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from CorrespondenceBase
VectorXs measurement_
Eigen::VectorXs expectation_
the expected measurement given the current state estimate
CapturePtr capture_ptr_
pointer to own capture
StatePtr state_ptr_
pointer to own state
SensorPtr sensor_ptr_
pointer to own's capture sensor
Protected Attributes inherited from NodeConstrainer< FeatureBase, NodeTerminus >
unsigned int dim_error_
Eigen::Map< Eigen::VectorXs > error_
Detailed Description
Relative constraint between two corresponding features.
This type of constraint takes two frames, two sensors, and two feature measurements, and computes the error of a relative constraint.
Notice that there are some possibilities:
Both frames are the same: it means we have two sensors on the robot from which we have seen the feature.
Both sensors are the same: it means we have moved and are in another frame seeing the same feature.
Frames and sensors are different: it means we observe from one sensor a feature that was seen in the past by another sensor.
The constraint error is the disagreement between the expected measurement and the current measurement. This disagreement is often defined by pure subtraction (and this class implements this default behavior), but this is not mandatory and can be reimplemented in derived classes.
Definition at line 31 of file correspondence_relative.h.
Constructor & Destructor Documentation
CorrespondenceRelative::CorrespondenceRelative (const FeatureShPtr & _ft_ptr, const FeatureShPtr & _ft_other_ptr, unsigned int _dim_error, unsigned int _dim_expectation)
Definition at line 70 of file correspondence_relative.h.
CorrespondenceRelative::~CorrespondenceRelative () virtual
Definition at line 81 of file correspondence_relative.h.
Member Function Documentation
const StatePtr CorrespondenceRelative::stateOtherPtr () const inline
Definition at line 86 of file correspondence_relative.h.
const StatePose & CorrespondenceRelative::stateOther () const inline
Definition at line 91 of file correspondence_relative.h.
const CapturePtr CorrespondenceRelative::captureOtherPtr () const inline
Definition at line 96 of file correspondence_relative.h.
Referenced by EpipolarConstraint::computeExpectation().
const Capture & CorrespondenceRelative::captureOther () const inline
Definition at line 101 of file correspondence_relative.h.
const SensorPtr CorrespondenceRelative::sensorOtherPtr () const inline
Definition at line 106 of file correspondence_relative.h.
Referenced by EpipolarConstraint::computeExpectation().
const SensorBase & CorrespondenceRelative::sensorOther () const inline
Definition at line 111 of file correspondence_relative.h.
const FeaturePtr CorrespondenceRelative::featureOtherPtr () const inline
Definition at line 116 of file correspondence_relative.h.
Referenced by EpipolarConstraint::computeExpectation().
const FeatureBase & CorrespondenceRelative::featureOther () const inline
Definition at line 121 of file correspondence_relative.h.
void CorrespondenceRelative::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from CorrespondenceBase.
Definition at line 126 of file correspondence_relative.h.
References Node::nodeId(), Node::printNTabs(), and CorrespondenceBase::printSelf().
The documentation for this class was generated from the following file:
correspondence_relative.h