WOLF: NodeLinked< UpperType, LowerType > Class Template Reference
NodeLinked< UpperType, LowerType > Class Template Reference
Linked node element in the Wolf Tree.
#include <node_linked.h>
Public Types
typedef UpperType * UpperNodePtr
typedef LowerType * LowerNodePtr
Public Member Functions
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const UpperType & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Types
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
template<class UpperType, class LowerType>
class NodeLinked< UpperType, LowerType >
Parameters
UpperType the type of node one level up in the Wolf tree.
LowerType the type of node one level down in the Wolf tree.
Inherit from this class to implement a node element to be placed somewhere in the Wolf Tree. A node has five main data members:
An unique ID to identify it over the whole Wolf Tree (inherited from Node)
A label indicating the node nature (inherited from Node)
An enum indicating tree location (see NodeLocation enum at wolf.h)
down_node_list_: A list of shared pointers to derived node objects, specified by the template parameter LowerType.
up_node_: A regular pointer to a derived node object, specified by the template parameter UpperType.
Definition at line 36 of file node_linked.h.
Member Typedef Documentation
template<class UpperType, class LowerType> typedef UpperType* NodeLinked< UpperType, LowerType >::UpperNodePtr
Definition at line 39 of file node_linked.h.
template<class UpperType, class LowerType> typedef LowerType* NodeLinked< UpperType, LowerType >::LowerNodePtr
Definition at line 40 of file node_linked.h.
template<class UpperType, class LowerType> typedef std::list<LowerNodePtr> NodeLinked< UpperType, LowerType >::LowerNodeList protected
Definition at line 43 of file node_linked.h.
template<class UpperType, class LowerType> typedef LowerNodeList::iterator NodeLinked< UpperType, LowerType >::LowerNodeIter protected
Definition at line 44 of file node_linked.h.
Constructor & Destructor Documentation
template<class UpperType , class LowerType > NodeLinked< UpperType, LowerType >::NodeLinked (const NodeLocation _loc, const std::string & _label)
Constructor without specify up node
Definition at line 227 of file node_linked.h.
template<class UpperType , class LowerType > NodeLinked< UpperType, LowerType >::~NodeLinked () virtual
Constructor specifying up nodeDefault destructor
Default destructor
Definition at line 245 of file node_linked.h.
Member Function Documentation
template<class UpperType , class LowerType > bool NodeLinked< UpperType, LowerType >::isTop () const inline
Check if node is on the top of Wolf tree
Definition at line 254 of file node_linked.h.
References TOP.
template<class UpperType , class LowerType > bool NodeLinked< UpperType, LowerType >::isBottom () const inline
Check if node is at the bottom of Wolf tree
Definition at line 263 of file node_linked.h.
References BOTTOM.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::linkToUpperNode (UpperNodePtr _pptr) inline
Sets link to up node
Definition at line 272 of file node_linked.h.
Referenced by WolfProblem::addMap(), WolfProblem::addTrajectory(), and WolfProblem::WolfProblem().
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::unlinkFromUpperNode () inline
Sets link to up node
Definition at line 285 of file node_linked.h.
template<class UpperType , class LowerType > const NodeLinked< UpperType, LowerType >::UpperNodePtr NodeLinked< UpperType, LowerType >::upperNodePtr () const inline
Access the pointer to parent. Throw if parent nullptr.
Definition at line 291 of file node_linked.h.
Referenced by ConstraintBase::getCapturePtr(), and FeatureBase::getFramePtr().
template<class UpperType , class LowerType > const UpperType & NodeLinked< UpperType, LowerType >::upperNode () const inline
Get a reference to parent. Throw if parent is nullptr.
Definition at line 298 of file node_linked.h.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::addDownNode (LowerNodePtr _ptr) inline
Adds a down node
Definition at line 305 of file node_linked.h.
template<class UpperType , class LowerType > NodeLinked< UpperType, LowerType >::LowerNodeList & NodeLinked< UpperType, LowerType >::downNodeList () const inline
Gets a reference to down node list
Definition at line 314 of file node_linked.h.
template<class UpperType , class LowerType > NodeLinked< UpperType, LowerType >::LowerNodeList * NodeLinked< UpperType, LowerType >::getDownNodeListPtr () inline
Gets constant reference to down node listGets a pointer to down node list
Gets a pointer to down node list
Definition at line 326 of file node_linked.h.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::removeDownNode (const LowerNodeIter & _iter) inline
Gets a const pointer to down node listRemoves a down node from list, given an iterator
Removes a down node from the list
Parameters
_iter an iterator to the particular down node in the list that will be removed
Definition at line 358 of file node_linked.h.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::removeDownNode (const LowerNodePtr _ptr) inline
Removes a down node from the list
Parameters
_ptr a pointer to the particular down node in the list that will be removed
Definition at line 351 of file node_linked.h.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::removeDownNode (const unsigned int _id) inline
Removes a down node from the multimap
Parameters
_id node id of the node that will nbe removed
Definition at line 338 of file node_linked.h.
template<class UpperType , class LowerType > WolfProblem * NodeLinked< UpperType, LowerType >::getTop () virtual
Gets a pointer to the tree top node TODO: Review if it could return a pointer to a derived class instead of NodeBase JVN: I tried to do so...
Definition at line 367 of file node_linked.h.
References WolfProblem::getTop().
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints node information.
Parameters
_ntabs number of tabulations to print at the left of the printed information
_ost output stream
Overload this function in derived classes to adapt the printed output to each object's relevant info.
Reimplemented from NodeBase.
Reimplemented in ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >, ConstraintSparse< 2, 2 >, ConstraintSparse< 3, 2, 1 >, ConstraintSparse< 3, 2, 1, 2, 1, 2, 1 >, ConstraintSparse< 2, 2, 2, 2, 2 >, ConstraintSparse< 2, 2, 1, 2, 1 >, ConstraintSparse< 3, 2, 2, 2, 2 >, and ConstraintSparse< 3, 2, 1, 2, 1 >.
Definition at line 385 of file node_linked.h.
References BOTTOM, and TOP.
Referenced by WolfProblem::printLower().
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented in FrameBase, CaptureBase, and FeatureBase.
Definition at line 400 of file node_linked.h.
References BOTTOM, MID, and TOP.
Referenced by ConstraintSparse< 3, 2, 1, 2, 1 >::print(), FeatureBase::printSelf(), CaptureBase::printSelf(), and FrameBase::printSelf().
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::printUpper (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected
Prints upper node info
Definition at line 422 of file node_linked.h.
template<class UpperType , class LowerType > void NodeLinked< UpperType, LowerType >::printLower (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const protected
Prints recursively lower node info
Definition at line 429 of file node_linked.h.
Field Documentation
template<class UpperType, class LowerType> NodeLocation NodeLinked< UpperType, LowerType >::location_ protected
Definition at line 47 of file node_linked.h.
template<class UpperType, class LowerType> UpperNodePtr NodeLinked< UpperType, LowerType >::up_node_ptr_ protected
Definition at line 48 of file node_linked.h.
template<class UpperType, class LowerType> LowerNodeList NodeLinked< UpperType, LowerType >::down_node_list_ protected
Definition at line 49 of file node_linked.h.
The documentation for this class was generated from the following file:
node_linked.h