WOLF: StateErrorIMU Class Reference
StateErrorIMU Class Reference
Error-state class for IMU biases states.
#include <state_error_imu.h>
Public Member Functions
StateErrorIMU ()
StateErrorIMU (Eigen::VectorXs &_xn)
StateErrorIMU (Eigen::Vector3s &_abias_n, Eigen::Vector3s &_wbias_n)
StateErrorIMU (Eigen::VectorXs &_storage, unsigned int _idx)
StateErrorIMU (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::VectorXs &_xn)
StateErrorIMU (Eigen::VectorXs &_storage, unsigned int _idx, Eigen::Vector3s &_abias_n, Eigen::Vector3s &_wbias_n)
virtual ~StateErrorIMU ()
void abn (Eigen::Vector3s &_abias_n)
Eigen::Map< Eigen::Vector3s > & abn ()
void wbn (Eigen::Vector3s &_wbias_n)
Eigen::Map< Eigen::Vector3s > & wbn ()
Eigen::Map< Eigen::Vector3s > & abe ()
Eigen::Map< Eigen::Vector3s > & wbe ()
Eigen::Map< Eigen::Vector3s > & abc ()
Eigen::Map< Eigen::Vector3s > & wbc ()
void compose ()
Public Member Functions inherited from StateError
StateError (const unsigned int _size_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const unsigned int _size_error)
StateError (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x_nominal, const Eigen::VectorXs &_x_error)
virtual ~StateError ()
Eigen::VectorXs & xn ()
const Eigen::VectorXs & xn () const
Eigen::Map< Eigen::VectorXs > & xe ()
const Eigen::Map
< Eigen::VectorXs > & xe () const
Eigen::VectorXs & xc ()
const Eigen::VectorXs & xc () const
void clearError ()
Public Member Functions inherited from StateRootBase
Eigen::VectorXs & stateEstimatedLocal ()
const Eigen::VectorXs & stateEstimatedLocal () const
Eigen::Map< Eigen::VectorXs > & stateEstimatedMap ()
const Eigen::Map
< Eigen::VectorXs > & stateEstimatedMap () const
virtual Eigen::Map
< Eigen::VectorXs > & x ()=0
Force implementation of a state getter and make this class Abstract.
virtual void remap (Eigen::VectorXs &_st_remote, const unsigned int _idx)
unsigned int size ()
Static Public Attributes
static const unsigned int SIZE_NOMINAL_ = 6
size of the nominal state
static const unsigned int SIZE_ERROR_ = 6
size of the error state
Additional Inherited Members
Protected Member Functions inherited from StateRootBase
StateRootBase (const unsigned int _size)
StateRootBase (const Eigen::VectorXs &_x)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const unsigned int _size)
StateRootBase (Eigen::VectorXs &_st_remote, const unsigned int _idx, const Eigen::VectorXs &_x)
virtual ~StateRootBase ()
Protected Attributes inherited from StateRootBase
Eigen::VectorXs state_estimated_local_
Local storage.
Eigen::Map< Eigen::VectorXs > state_estimated_map_
mapped vector, to remote storage
Detailed Description
Definition at line 17 of file state_error_imu.h.
Constructor & Destructor Documentation
StateErrorIMU::StateErrorIMU ()
Default Local constructor
Definition at line 12 of file state_error_imu.cpp.
References compose().
StateErrorIMU::StateErrorIMU (Eigen::VectorXs & _xn)
Local Constructor from nominal state.
Parameters
_xn the nominal state vector
Error state always initialized to zero.
Definition at line 26 of file state_error_imu.cpp.
References compose().
StateErrorIMU::StateErrorIMU (Eigen::Vector3s & _abias_n, Eigen::Vector3s & _wbias_n)
Local Constructor from nominal biases.
Parameters
_abias_n nominal acc bias
_wbias_n nominal gyro bias
Error state always initialized to zero.
Definition at line 38 of file state_error_imu.cpp.
References compose().
StateErrorIMU::StateErrorIMU (Eigen::VectorXs & _storage, unsigned int _idx)
Default Remote constructor
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
All states initialized to zero.
StateErrorIMU::StateErrorIMU (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::VectorXs & _xn)
Remote Constructor from nominal state.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_xn the nominal state vector
Error state initialized to zero.
StateErrorIMU::StateErrorIMU (Eigen::VectorXs & _storage, unsigned int _idx, Eigen::Vector3s & _abias_n, Eigen::Vector3s & _wbias_n)
Remote Constructor from nominal biases.
Parameters
_storage the remote storage vector
_idx index to the remote storage where the error state will map
_abias_n the nominal acc bias
_wbias_n the nominal gyro bias
Error state initialized to zero.
StateErrorIMU::~StateErrorIMU () virtual
Definition at line 91 of file state_error_imu.cpp.
Member Function Documentation
void StateErrorIMU::abn (Eigen::Vector3s & _abias_n) inline
Set nominal acc bias
Parameters
_abias_n nominal acc bias
Definition at line 150 of file state_error_imu.h.
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::abn () inline
Get reference to nominal acc bias
Definition at line 145 of file state_error_imu.h.
void StateErrorIMU::wbn (Eigen::Vector3s & _wbias_n) inline
Set nominal gyro bias
Parameters
_wbias_n nominal gyro bias
Definition at line 160 of file state_error_imu.h.
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::wbn () inline
Get reference to nominal gyro bias
Definition at line 155 of file state_error_imu.h.
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::abe () inline
Get reference to acc bias error
Definition at line 165 of file state_error_imu.h.
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::wbe () inline
Get reference to gyro bias error
Definition at line 170 of file state_error_imu.h.
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::abc () inline
Get reference to composed acc bias
Definition at line 175 of file state_error_imu.h.
References compose().
Eigen::Map< Eigen::Vector3s > & StateErrorIMU::wbc () inline
Get reference to composed gyro bias
Definition at line 181 of file state_error_imu.h.
References compose().
void StateErrorIMU::compose () inline virtual
Compose nominal and error states.
Implements StateError.
Definition at line 133 of file state_error_imu.h.
References StateRootBase::state_estimated_map_.
Referenced by abc(), StateErrorIMU(), and wbc().
Field Documentation
const unsigned int StateErrorIMU::SIZE_NOMINAL_ = 6 static
Definition at line 20 of file state_error_imu.h.
const unsigned int StateErrorIMU::SIZE_ERROR_ = 6 static
Definition at line 21 of file state_error_imu.h.
The documentation for this class was generated from the following files:
state_error_imu.h
state_error_imu.cpp