WOLF: SolverQR Class Reference
SolverQR Class Reference
#include <qr_solver.h>
Public Member Functions
SolverQR (const std::string &_name)
virtual ~SolverQR ()
void add_state_unit (const int node_dim, const int node_idx)
void addConstraint (const measurement &_meas)
void ordering (const int &_first_ordered_node)
bool solve (const int mode)
void nodePermutation2VariablesPermutation (const PermutationMatrix< Dynamic, Dynamic, int > &_perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > &perm_variables)
ArrayXi perm_nodes_2_locations (const PermutationMatrix< Dynamic, Dynamic, int > &_perm_nodes)
void augment_permutation (PermutationMatrix< Dynamic, Dynamic, int > &perm, const int new_size)
void accumulatePermutation (const PermutationMatrix< Dynamic, Dynamic, int > &perm)
void printName ()
void printResults ()
void printProblem ()
SolverQR ()
virtual ~SolverQR ()
void update (WolfProblem *_problem_ptr)
void addStateUnit (StateBase *_state_ptr)
void updateStateUnitStatus (StateBase *_state_ptr)
void addConstraint (ConstraintBase *_constraint_ptr)
void ordering (const int &_first_ordered_idx)
unsigned int findFirstOrderedNode ()
bool solve (const unsigned int mode)
void nodePermutation2VariablesPermutation (const PermutationMatrix< Dynamic, Dynamic, int > &_perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > &perm_variables)
void nodePermutation2nodeLocations (const PermutationMatrix< Dynamic, Dynamic, int > &_perm_nodes, ArrayXi &locations)
void augmentPermutation (PermutationMatrix< Dynamic, Dynamic, int > &perm, const unsigned int new_size)
void accumulatePermutation (const PermutationMatrix< Dynamic, Dynamic, int > &perm)
unsigned int nodeDim (const unsigned int _idx)
unsigned int nodeOrder (const unsigned int _idx)
unsigned int nodeLocation (const unsigned int _idx)
unsigned int nNodes ()
CostFunctionBase * createCostFunction (ConstraintBase *_corrPtr)
void printResults ()
void printProblem ()
Protected Attributes
std::string name_
SparseQR< SparseMatrix< double >
, NaturalOrdering< int > > solver_
SparseMatrix< double > A_
SparseMatrix< double > R_
VectorXd b_
VectorXd x_incr_
int n_measurements = 0
int n_nodes_
std::vector< node > nodes_
std::vector< measurement > measurements_
SparseMatrix< int > A_nodes_
PermutationMatrix< Dynamic,
Dynamic, int > acc_node_permutation_
CCOLAMDOrdering< int > orderer_
VectorXi node_ordering_restrictions_
int first_ordered_node_
clock_t t_ordering_
clock_t t_solving_
clock_t t_managing_
double time_ordering_
double time_solving_
double time_managing_
std::vector< StateBase * > nodes_
std::vector< ConstraintBase * > constraints_
std::vector< CostFunctionBase * > cost_functions_
std::map< unsigned int,
unsigned int > id_2_idx_
ArrayXi node_locations_
std::vector< unsigned int > constraint_locations_
unsigned int n_new_constraints_
SparseMatrix< double > A
SparseMatrix< double > A_ordered
SparseMatrix< double > R
VectorXd b
VectorXd x
VectorXd x_ordered
VectorXd x_ordered_partial
int n_nodes = 0
SparseMatrix< int > A_nodes_ordered
PermutationMatrix< Dynamic,
Dynamic, int > acc_permutation_nodes_matrix
CCOLAMDOrdering< int > ordering
CCOLAMDOrdering< int > partial_ordering
VectorXi nodes_ordering_constraints
Detailed Description
Definition at line 123 of file test_iQR_wolf.cpp.
Constructor & Destructor Documentation
SolverQR::SolverQR (const std::string & _name) inline
Definition at line 148 of file test_iQR_wolf.cpp.
virtual SolverQR::~SolverQR () inline virtual
Definition at line 167 of file test_iQR_wolf.cpp.
SolverQR::SolverQR () inline
Definition at line 57 of file qr_solver.h.
virtual SolverQR::~SolverQR () inline virtual
Definition at line 71 of file qr_solver.h.
Member Function Documentation
void SolverQR::add_state_unit (const int node_dim, const int node_idx) inline
Definition at line 172 of file test_iQR_wolf.cpp.
References augment_permutation().
Referenced by main().
void SolverQR::addConstraint (const measurement & _meas) inline
Definition at line 193 of file test_iQR_wolf.cpp.
References addSparseBlock(), measurement::dim, measurement::error, measurement::jacobians, and measurement::nodes_idx.
Referenced by main().
void SolverQR::ordering (const int & _first_ordered_node) inline
Definition at line 236 of file test_iQR_wolf.cpp.
bool SolverQR::solve (const int mode) inline
Definition at line 301 of file test_iQR_wolf.cpp.
References addSparseBlock(), and eraseSparseBlock().
Referenced by main().
void SolverQR::nodePermutation2VariablesPermutation (const PermutationMatrix< Dynamic, Dynamic, int > & _perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > & perm_variables) inline
Definition at line 396 of file test_iQR_wolf.cpp.
ArrayXi SolverQR::perm_nodes_2_locations (const PermutationMatrix< Dynamic, Dynamic, int > & _perm_nodes) inline
Definition at line 408 of file test_iQR_wolf.cpp.
void SolverQR::augment_permutation (PermutationMatrix< Dynamic, Dynamic, int > & perm, const int new_size) inline
Definition at line 418 of file test_iQR_wolf.cpp.
void SolverQR::accumulatePermutation (const PermutationMatrix< Dynamic, Dynamic, int > & perm) inline
Definition at line 429 of file test_iQR_wolf.cpp.
void SolverQR::printName () inline
Definition at line 456 of file test_iQR_wolf.cpp.
void SolverQR::printResults () inline
Definition at line 461 of file test_iQR_wolf.cpp.
Referenced by main().
void SolverQR::printProblem () inline
Definition at line 468 of file test_iQR_wolf.cpp.
Referenced by main().
void SolverQR::update (WolfProblem * _problem_ptr) inline
Definition at line 76 of file qr_solver.h.
References ADD_PENDING, TrajectoryBase::getConstraintList(), WolfProblem::getRemovedStateListPtr(), WolfProblem::getStateListPtr(), WolfProblem::getTrajectoryPtr(), and UPDATE_PENDING.
Referenced by main().
void SolverQR::addStateUnit (StateBase * _state_ptr) inline
Definition at line 108 of file qr_solver.h.
References StateBase::getStateSize(), StateBase::getStateStatus(), NodeBase::nodeId(), NOT_PENDING, NodeBase::setPendingStatus(), and ST_ESTIMATED.
void SolverQR::updateStateUnitStatus (StateBase * _state_ptr) inline
Definition at line 135 of file qr_solver.h.
void SolverQR::addConstraint (ConstraintBase * _constraint_ptr) inline
Definition at line 140 of file qr_solver.h.
References addSparseBlock(), ConstraintBase::getSize(), ConstraintBase::getStatePtrVector(), NodeBase::nodeId(), NOT_PENDING, NodeBase::setPendingStatus(), and ST_ESTIMATED.
void SolverQR::ordering (const int & _first_ordered_idx) inline
Definition at line 190 of file qr_solver.h.
unsigned int SolverQR::findFirstOrderedNode () inline
Definition at line 261 of file qr_solver.h.
References ConstraintBase::getStatePtrVector(), and ST_ESTIMATED.
bool SolverQR::solve (const unsigned int mode) inline
Definition at line 293 of file qr_solver.h.
References addSparseBlock(), and eraseSparseBlock().
void SolverQR::nodePermutation2VariablesPermutation (const PermutationMatrix< Dynamic, Dynamic, int > & _perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > & perm_variables) inline
Definition at line 419 of file qr_solver.h.
void SolverQR::nodePermutation2nodeLocations (const PermutationMatrix< Dynamic, Dynamic, int > & _perm_nodes, ArrayXi & locations) inline
Definition at line 436 of file qr_solver.h.
void SolverQR::augmentPermutation (PermutationMatrix< Dynamic, Dynamic, int > & perm, const unsigned int new_size) inline
Definition at line 444 of file qr_solver.h.
void SolverQR::accumulatePermutation (const PermutationMatrix< Dynamic, Dynamic, int > & perm) inline
Definition at line 462 of file qr_solver.h.
unsigned int SolverQR::nodeDim (const unsigned int _idx) inline
Definition at line 483 of file qr_solver.h.
unsigned int SolverQR::nodeOrder (const unsigned int _idx) inline
Definition at line 489 of file qr_solver.h.
unsigned int SolverQR::nodeLocation (const unsigned int _idx) inline
Definition at line 496 of file qr_solver.h.
unsigned int SolverQR::nNodes () inline
Definition at line 503 of file qr_solver.h.
CostFunctionBase* SolverQR::createCostFunction (ConstraintBase * _corrPtr) inline
Definition at line 508 of file qr_solver.h.
References ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block0Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block1Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block2Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block3Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block4Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block5Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block6Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block7Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block8Size, ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::block9Size, CTR_CORNER_2D_THETA, CTR_GPS_FIX_2D, CTR_ODOM_2D_COMPLEX_ANGLE, CTR_ODOM_2D_THETA, ConstraintBase::getConstraintType(), and ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >::measurementSize.
void SolverQR::printResults () inline
Definition at line 590 of file qr_solver.h.
void SolverQR::printProblem () inline
Definition at line 596 of file qr_solver.h.
Field Documentation
std::string SolverQR::name_ protected
Definition at line 126 of file test_iQR_wolf.cpp.
SparseQR< SparseMatrix< double >, NaturalOrdering< int > > SolverQR::solver_ protected
Definition at line 127 of file test_iQR_wolf.cpp.
SparseMatrix< double > SolverQR::A_ protected
Definition at line 128 of file test_iQR_wolf.cpp.
SparseMatrix< double > SolverQR::R_ protected
Definition at line 128 of file test_iQR_wolf.cpp.
VectorXd SolverQR::b_ protected
Definition at line 129 of file test_iQR_wolf.cpp.
VectorXd SolverQR::x_incr_ protected
Definition at line 129 of file test_iQR_wolf.cpp.
int SolverQR::n_measurements = 0 protected
Definition at line 130 of file test_iQR_wolf.cpp.
int SolverQR::n_nodes_ protected
Definition at line 131 of file test_iQR_wolf.cpp.
std::vector<node> SolverQR::nodes_ protected
Definition at line 132 of file test_iQR_wolf.cpp.
std::vector<measurement> SolverQR::measurements_ protected
Definition at line 133 of file test_iQR_wolf.cpp.
SparseMatrix< int > SolverQR::A_nodes_ protected
Definition at line 136 of file test_iQR_wolf.cpp.
PermutationMatrix< Dynamic, Dynamic, int > SolverQR::acc_node_permutation_ protected
Definition at line 137 of file test_iQR_wolf.cpp.
CCOLAMDOrdering< int > SolverQR::orderer_ protected
Definition at line 139 of file test_iQR_wolf.cpp.
VectorXi SolverQR::node_ordering_restrictions_ protected
Definition at line 140 of file test_iQR_wolf.cpp.
int SolverQR::first_ordered_node_ protected
Definition at line 141 of file test_iQR_wolf.cpp.
clock_t SolverQR::t_ordering_ protected
Definition at line 144 of file test_iQR_wolf.cpp.
clock_t SolverQR::t_solving_ protected
Definition at line 144 of file test_iQR_wolf.cpp.
clock_t SolverQR::t_managing_ protected
Definition at line 144 of file test_iQR_wolf.cpp.
double SolverQR::time_ordering_ protected
Definition at line 145 of file test_iQR_wolf.cpp.
double SolverQR::time_solving_ protected
Definition at line 145 of file test_iQR_wolf.cpp.
double SolverQR::time_managing_ protected
Definition at line 145 of file test_iQR_wolf.cpp.
std::vector<StateBase*> SolverQR::nodes_ protected
Definition at line 37 of file qr_solver.h.
std::vector<ConstraintBase*> SolverQR::constraints_ protected
Definition at line 38 of file qr_solver.h.
std::vector<CostFunctionBase*> SolverQR::cost_functions_ protected
Definition at line 39 of file qr_solver.h.
std::map<unsigned int, unsigned int> SolverQR::id_2_idx_ protected
Definition at line 44 of file qr_solver.h.
ArrayXi SolverQR::node_locations_ protected
Definition at line 47 of file qr_solver.h.
std::vector<unsigned int> SolverQR::constraint_locations_ protected
Definition at line 48 of file qr_solver.h.
unsigned int SolverQR::n_new_constraints_ protected
Definition at line 49 of file qr_solver.h.
SparseMatrix<double> SolverQR::A protected
Definition at line 17 of file solver_QR.h.
SparseMatrix<double> SolverQR::A_ordered protected
Definition at line 17 of file solver_QR.h.
SparseMatrix<double> SolverQR::R protected
Definition at line 17 of file solver_QR.h.
VectorXd SolverQR::b protected
Definition at line 18 of file solver_QR.h.
VectorXd SolverQR::x protected
Definition at line 18 of file solver_QR.h.
VectorXd SolverQR::x_ordered protected
Definition at line 18 of file solver_QR.h.
VectorXd SolverQR::x_ordered_partial protected
Definition at line 18 of file solver_QR.h.
int SolverQR::n_nodes = 0 protected
Definition at line 20 of file solver_QR.h.
SparseMatrix<int> SolverQR::A_nodes_ordered protected
Definition at line 23 of file solver_QR.h.
PermutationMatrix<Dynamic, Dynamic, int> SolverQR::acc_permutation_nodes_matrix protected
Definition at line 24 of file solver_QR.h.
CCOLAMDOrdering<int> SolverQR::ordering protected
Definition at line 26 of file solver_QR.h.
CCOLAMDOrdering<int> SolverQR::partial_ordering protected
Definition at line 26 of file solver_QR.h.
VectorXi SolverQR::nodes_ordering_constraints protected
Definition at line 27 of file solver_QR.h.
The documentation for this class was generated from the following files:
test_iQR_wolf.cpp
qr_solver.h
solver_QR.h