WOLF: TimeStamp Class Reference
TimeStamp Class Reference
TimeStamp implements basic functionalities for time stamps.
#include <time_stamp.h>
Public Member Functions
TimeStamp ()
Constructor.
TimeStamp (const WolfScalar _ts)
Constructor with argument.
TimeStamp (const unsigned long int _sec, const unsigned long int _nsec)
Constructor from sec and nsec.
virtual ~TimeStamp ()
Destructor.
void setToNow ()
Time stamp to now.
void set (const timeval &ts)
Set time stamp.
void set (const unsigned long int sec, const unsigned long int nanosec)
Set time stamp.
void set (const WolfScalar ts)
Set time stamp.
WolfScalar get () const
Get time stamp.
unsigned long int getSeconds () const
Get time stamp (only seconds)
unsigned long int getNanoSeconds () const
Get time stamp (only nano seconds)
void print (std::ostream &ost=std::cout) const
Prints time stamp to a given ostream.
void operator= (const WolfScalar &ts)
Assignement operator.
void operator= (const TimeStamp &ts)
Assignement operator.
bool operator< (const TimeStamp &ts) const
comparison operator
bool operator<= (const TimeStamp &ts) const
comparison operator
WolfScalar operator- (const TimeStamp &ts) const
difference operator
Detailed Description
TimeStamp implements basic functionalities for time stamps
Definition at line 22 of file time_stamp.h.
Constructor & Destructor Documentation
TimeStamp::TimeStamp ()
Constructor without arguments. Sets time stamp to now.
Definition at line 4 of file time_stamp.cpp.
References setToNow().
TimeStamp::TimeStamp (const WolfScalar _ts)
Constructor with arguments
Definition at line 10 of file time_stamp.cpp.
TimeStamp::TimeStamp (const unsigned long int _sec, const unsigned long int _nsec)
Constructor from sec and nsec
Definition at line 16 of file time_stamp.cpp.
TimeStamp::~TimeStamp () virtual
Destructor
Definition at line 22 of file time_stamp.cpp.
Member Function Documentation
void TimeStamp::setToNow ()
Sets time stamp to now
Definition at line 27 of file time_stamp.cpp.
Referenced by main(), CaptureBase::setTimeStampToNow(), and TimeStamp().
void TimeStamp::set (const timeval & ts)
Sets time stamp to a given value passed as a timeval struct
Definition at line 34 of file time_stamp.cpp.
void TimeStamp::set (const unsigned long int sec, const unsigned long int nanosec)
Sets time stamp to a given value passed as a two-integer (seconds and nanoseconds)
Definition at line 39 of file time_stamp.cpp.
void TimeStamp::set (const WolfScalar ts)
Sets time stamp to a given value passed as a scalar_t (seconds)
Definition at line 44 of file time_stamp.cpp.
WolfScalar TimeStamp::get () const
Returns time stamp
Definition at line 49 of file time_stamp.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::checkNewFrame(), FrameBase::getTimeStamp(), CaptureTwist2D::interpolateCapture(), CaptureOdom2D::interpolateCapture(), operator-(), operator<(), operator<=(), operator=(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
unsigned long int TimeStamp::getSeconds () const
Returns seconds of time stamp
Definition at line 54 of file time_stamp.cpp.
unsigned long int TimeStamp::getNanoSeconds () const
Returns nanoseconds part of time stamp
Definition at line 61 of file time_stamp.cpp.
void TimeStamp::print (std::ostream & ost = std::cout) const
Prints time stamp to a given ostream
Definition at line 68 of file time_stamp.cpp.
void TimeStamp::operator= (const WolfScalar & ts)
Assignement operator
Definition at line 86 of file time_stamp.cpp.
void TimeStamp::operator= (const TimeStamp & ts)
Assignement operator
Definition at line 91 of file time_stamp.cpp.
References get().
bool TimeStamp::operator< (const TimeStamp & ts) const
Comparison operator
Definition at line 96 of file time_stamp.cpp.
References get().
bool TimeStamp::operator<= (const TimeStamp & ts) const
Comparison operator
Definition at line 104 of file time_stamp.cpp.
References get().
WolfScalar TimeStamp::operator- (const TimeStamp & ts) const
difference operator
Definition at line 112 of file time_stamp.cpp.
References get().
The documentation for this class was generated from the following files:
time_stamp.h
time_stamp.cpp