WOLF: StateComplexAngle Class Reference
StateComplexAngle Class Reference
#include <state_complex_angle.h>
Public Member Functions
StateComplexAngle (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StateComplexAngle (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StateComplexAngle ()
Destructor.
virtual StateType getStateType () const
Returns the parametrization of the state unit.
virtual unsigned int getStateSize () const
Returns the state unit size.
void rotationMatrix (Eigen::Matrix3s &R) const
Returns the 3x3 rotation matrix of the orientation.
virtual WolfScalar getYaw () const
Returns the yaw angle.
virtual Eigen::Map< const
Eigen::VectorXs > getVector () const
Returns a (mapped) vector of the state unit.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints all the elements of the state unit.
Public Member Functions inherited from StateOrientation
StateOrientation (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StateOrientation (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StateOrientation ()
Destructor.
Eigen::Matrix3s getRotationMatrix () const
Returns the 3x3 rotation matrix of the orientation.
Public Member Functions inherited from StateBase
StateBase (WolfScalar *_st_ptr)
Constructor with scalar pointer.
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
virtual ~StateBase ()
Destructor.
virtual WolfScalar * getPtr ()
Returns the pointer to the first element of the state.
virtual void setPtr (WolfScalar *_new_ptr)
Set the pointer of the first element of the state.
StateStatus getStateStatus () const
Returns the status of the state unit.
void setStateStatus (const StateStatus &_status)
Set the status of the state unit.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Static Public Attributes
static const unsigned int BLOCK_SIZE = 2
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from StateBase
WolfScalar * state_ptr_
StateStatus status_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 15 of file state_complex_angle.h.
Constructor & Destructor Documentation
StateComplexAngle::StateComplexAngle (Eigen::VectorXs & _st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit
Parameters
_st_remote is the whole state vector
_idx is the index of the first element of the state in the whole state vector
Definition at line 4 of file state_complex_angle.cpp.
StateComplexAngle::StateComplexAngle (WolfScalar * _st_ptr)
Constructor with scalar pointer
Parameters
_st_ptr is the pointer of the first element of the state unit
Definition at line 10 of file state_complex_angle.cpp.
StateComplexAngle::~StateComplexAngle () virtual
Destructor
Definition at line 16 of file state_complex_angle.cpp.
Member Function Documentation
StateType StateComplexAngle::getStateType () const virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 21 of file state_complex_angle.cpp.
References ST_COMPLEX_ANGLE.
unsigned int StateComplexAngle::getStateSize () const virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 26 of file state_complex_angle.cpp.
References BLOCK_SIZE.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame().
void StateComplexAngle::rotationMatrix (Eigen::Matrix3s & R) const virtual
Returns the 3x3 rotation matrix of the orientation
Implements StateOrientation.
Definition at line 31 of file state_complex_angle.cpp.
References StateBase::state_ptr_.
WolfScalar StateComplexAngle::getYaw () const virtual
Returns the yaw angle
Implements StateOrientation.
Definition at line 47 of file state_complex_angle.cpp.
References StateBase::state_ptr_.
Eigen::Map< const Eigen::VectorXs > StateComplexAngle::getVector () const virtual
Returns a (mapped) vector of the state unit
Implements StateOrientation.
Definition at line 42 of file state_complex_angle.cpp.
References BLOCK_SIZE, and StateBase::state_ptr_.
void StateComplexAngle::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints all the elements of the state unit
Implements StateBase.
Definition at line 52 of file state_complex_angle.cpp.
References NodeBase::nodeId(), NodeBase::nodeLabel(), NodeBase::printTabs(), and StateBase::state_ptr_.
Field Documentation
const unsigned int StateComplexAngle::BLOCK_SIZE = 2 static
Definition at line 18 of file state_complex_angle.h.
Referenced by getStateSize(), and getVector().
The documentation for this class was generated from the following files:
state_complex_angle.h
state_complex_angle.cpp