WOLF: FrameBase Class Reference
FrameBase Class Reference
#include <frame_base.h>
Public Member Functions
FrameBase (const TimeStamp &_ts, StateBase *_p_ptr, StateOrientation *_o_ptr=nullptr, StateBase *_v_ptr=nullptr, StateBase *_w_ptr=nullptr)
Constructor with only time stamp.
FrameBase (const FrameType &_tp, const TimeStamp &_ts, StateBase *_p_ptr, StateOrientation *_o_ptr=nullptr, StateBase *_v_ptr=nullptr, StateBase *_w_ptr=nullptr)
Constructor with type, time stamp and state pointer.
virtual ~FrameBase ()
Destructor.
bool isKey () const
Checks if this frame is KEY_FRAME.
void setType (FrameType _ft)
void fix ()
void unfix ()
void setTimeStamp (const TimeStamp &_ts)
TimeStamp getTimeStamp () const
void getTimeStamp (TimeStamp &_ts) const
void setStatus (const StateStatus &_status)
StateStatus getStatus () const
void setState (const Eigen::VectorXs &_st)
void addCapture (CaptureBase *_capt_ptr)
Eigen::Map< Eigen::VectorXs > getState () const
void removeCapture (CaptureBaseIter &_capt_ptr)
TrajectoryBase * getTrajectoryPtr () const
CaptureBaseList * getCaptureListPtr ()
void getConstraintList (ConstraintBaseList &_ctr_list)
FrameBase * getPreviousFrame () const
FrameBase * getNextFrame () const
StateBase * getPPtr () const
StateOrientation * getOPtr () const
StateBase * getVPtr () const
StateBase * getWPtr () const
const Eigen::Matrix4s * getTransformationMatrix () const
CaptureBaseIter hasCaptureOf (const SensorBase *_sensor_ptr)
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
Public Member Functions inherited from NodeLinked< TrajectoryBase, CaptureBase >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const TrajectoryBase & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
FrameType type_
TimeStamp time_stamp_
StateStatus status_
StateBase * p_ptr_
StateOrientation * o_ptr_
StateBase * v_ptr_
StateBase * w_ptr_
Protected Attributes inherited from NodeLinked< TrajectoryBase, CaptureBase >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< TrajectoryBase, CaptureBase >
typedef TrajectoryBase * UpperNodePtr
typedef CaptureBase * LowerNodePtr
Protected Types inherited from NodeLinked< TrajectoryBase, CaptureBase >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< TrajectoryBase, CaptureBase >
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 24 of file frame_base.h.
Constructor & Destructor Documentation
FrameBase::FrameBase (const TimeStamp & _ts, StateBase * _p_ptr, StateOrientation * _o_ptr = nullptr, StateBase * _v_ptr = nullptr, StateBase * _w_ptr = nullptr)
Constructor with only time stamp
Parameters
_traj_ptr a pointer to the Trajectory up node
_tp indicates frame type. Generally either REGULAR_FRAME or KEY_FRAME. (types defined at wolf.h)
_p_ptr StateBase pointer to the position (default: nullptr)
_o_ptr StateBase pointer to the orientation (default: nullptr)
_v_ptr StateBase pointer to the velocity (default: nullptr)
_w_ptr StateBase pointer to the angular velocity (default: nullptr)
Definition at line 4 of file frame_base.cpp.
FrameBase::FrameBase (const FrameType & _tp, const TimeStamp & _ts, StateBase * _p_ptr, StateOrientation * _o_ptr = nullptr, StateBase * _v_ptr = nullptr, StateBase * _w_ptr = nullptr)
Constructor with type, time stamp and state pointer
Parameters
_traj_ptr a pointer to the Trajectory up node
_tp indicates frame type. Generally either REGULAR_FRAME or KEY_FRAME. (types defined at wolf.h)
_ts is the time stamp associated to this frame, provided in seconds
_p_ptr StateBase pointer to the position (default: nullptr)
_o_ptr StateBase pointer to the orientation (default: nullptr)
_v_ptr StateBase pointer to the velocity (default: nullptr)
_w_ptr StateBase pointer to the angular velocity (default: nullptr)
Definition at line 18 of file frame_base.cpp.
FrameBase::~FrameBase () virtual
Destructor
Definition at line 32 of file frame_base.cpp.
References NodeLinked< TrajectoryBase, CaptureBase >::getTop(), o_ptr_, p_ptr_, WolfProblem::removeState(), v_ptr_, and w_ptr_.
Member Function Documentation
bool FrameBase::isKey () const
Returns true if type_ is KEY_FRAME. Oterwise returns false.
Definition at line 47 of file frame_base.cpp.
References KEY_FRAME, and type_.
void FrameBase::setType (FrameType _ft)
Definition at line 53 of file frame_base.cpp.
References type_.
void FrameBase::fix ()
Definition at line 58 of file frame_base.cpp.
References o_ptr_, p_ptr_, StateBase::setStateStatus(), ST_FIXED, status_, v_ptr_, and w_ptr_.
void FrameBase::unfix ()
Definition at line 74 of file frame_base.cpp.
References o_ptr_, p_ptr_, StateBase::setStateStatus(), ST_ESTIMATED, status_, v_ptr_, and w_ptr_.
void FrameBase::setTimeStamp (const TimeStamp & _ts)
Definition at line 90 of file frame_base.cpp.
References time_stamp_.
TimeStamp FrameBase::getTimeStamp () const
Definition at line 95 of file frame_base.cpp.
References TimeStamp::get(), and time_stamp_.
void FrameBase::getTimeStamp (TimeStamp & _ts) const
Definition at line 100 of file frame_base.cpp.
References TimeStamp::get(), and time_stamp_.
void FrameBase::setStatus (const StateStatus & _status)
Definition at line 105 of file frame_base.cpp.
References status_.
StateStatus FrameBase::getStatus () const
Definition at line 110 of file frame_base.cpp.
References status_.
void FrameBase::setState (const Eigen::VectorXs & _st)
Definition at line 115 of file frame_base.cpp.
References StateBase::getPtr(), StateBase::getStateSize(), o_ptr_, p_ptr_, v_ptr_, and w_ptr_.
void FrameBase::addCapture (CaptureBase * _capt_ptr)
Definition at line 137 of file frame_base.cpp.
References NodeLinked< TrajectoryBase, CaptureBase >::addDownNode().
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager().
Eigen::Map< Eigen::VectorXs > FrameBase::getState () const
Definition at line 131 of file frame_base.cpp.
References StateBase::getPtr(), StateBase::getStateSize(), o_ptr_, p_ptr_, v_ptr_, and w_ptr_.
void FrameBase::removeCapture (CaptureBaseIter & _capt_ptr)
Definition at line 142 of file frame_base.cpp.
References NodeLinked< TrajectoryBase, CaptureBase >::removeDownNode().
TrajectoryBase * FrameBase::getTrajectoryPtr () const
Definition at line 148 of file frame_base.cpp.
References NodeLinked< TrajectoryBase, CaptureBase >::upperNodePtr().
Referenced by getNextFrame(), and getPreviousFrame().
CaptureBaseList * FrameBase::getCaptureListPtr ()
Definition at line 153 of file frame_base.cpp.
References NodeLinked< TrajectoryBase, CaptureBase >::getDownNodeListPtr().
Referenced by getConstraintList(), and hasCaptureOf().
void FrameBase::getConstraintList (ConstraintBaseList & _ctr_list)
Definition at line 158 of file frame_base.cpp.
References getCaptureListPtr().
FrameBase * FrameBase::getPreviousFrame () const
Definition at line 164 of file frame_base.cpp.
References TrajectoryBase::getFrameListPtr(), getTrajectoryPtr(), and NodeBase::node_id_.
FrameBase * FrameBase::getNextFrame () const
Definition at line 181 of file frame_base.cpp.
References TrajectoryBase::getFrameListPtr(), getTrajectoryPtr(), and NodeBase::node_id_.
Referenced by CaptureTwist2D::addConstraints().
StateBase * FrameBase::getPPtr () const
Definition at line 201 of file frame_base.cpp.
References p_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::computeOdomCapture(), and CaptureLaser2D::establishConstraintsMHTree().
StateOrientation * FrameBase::getOPtr () const
Definition at line 206 of file frame_base.cpp.
References o_ptr_.
Referenced by CaptureLaser2D::computeExpectedFeature(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::computeOdomCapture(), CaptureTwist2D::computePrior(), CaptureLaser2D::createCornerLandmark(), and CaptureLaser2D::establishConstraintsMHTree().
StateBase * FrameBase::getVPtr () const
Definition at line 211 of file frame_base.cpp.
References v_ptr_.
StateBase * FrameBase::getWPtr () const
Definition at line 216 of file frame_base.cpp.
References w_ptr_.
const Eigen::Matrix4s* FrameBase::getTransformationMatrix () const
CaptureBaseIter FrameBase::hasCaptureOf (const SensorBase * _sensor_ptr)
Definition at line 221 of file frame_base.cpp.
References getCaptureListPtr().
void FrameBase::printSelf (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints information about this node. It adds a number of tabs given by _ntabs.
Parameters
_ntabs the number of tabs.
_ost the stream it prints to
Reimplemented from NodeLinked< TrajectoryBase, CaptureBase >.
Definition at line 230 of file frame_base.cpp.
References o_ptr_, p_ptr_, StateBase::print(), NodeLinked< UpperType, LowerType >::printSelf(), NodeBase::printTabs(), v_ptr_, and w_ptr_.
Field Documentation
FrameType FrameBase::type_ protected
Definition at line 27 of file frame_base.h.
Referenced by isKey(), and setType().
TimeStamp FrameBase::time_stamp_ protected
Definition at line 28 of file frame_base.h.
Referenced by getTimeStamp(), and setTimeStamp().
StateStatus FrameBase::status_ protected
Definition at line 29 of file frame_base.h.
Referenced by fix(), getStatus(), setStatus(), and unfix().
StateBase* FrameBase::p_ptr_ protected
Definition at line 30 of file frame_base.h.
Referenced by fix(), getPPtr(), getState(), printSelf(), setState(), unfix(), and ~FrameBase().
StateOrientation* FrameBase::o_ptr_ protected
Definition at line 31 of file frame_base.h.
Referenced by fix(), getOPtr(), getState(), printSelf(), setState(), unfix(), and ~FrameBase().
StateBase* FrameBase::v_ptr_ protected
Definition at line 32 of file frame_base.h.
Referenced by fix(), getState(), getVPtr(), printSelf(), setState(), unfix(), and ~FrameBase().
StateBase* FrameBase::w_ptr_ protected
Definition at line 33 of file frame_base.h.
Referenced by fix(), getState(), getWPtr(), printSelf(), setState(), unfix(), and ~FrameBase().
The documentation for this class was generated from the following files:
frame_base.h
frame_base.cpp