WOLF: StateQuaternion Class Reference
StateQuaternion Class Reference
#include <state_quaternion.h>
Public Member Functions
StateQuaternion (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StateQuaternion (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StateQuaternion ()
Destructor.
virtual StateType getStateType () const
Returns the parametrization of the state unit.
virtual unsigned int getStateSize () const
Returns the state unit size.
virtual void rotationMatrix (Eigen::Matrix3s &R) const
Returns the 3x3 rotation matrix of the orientation.
virtual WolfScalar getYaw () const
Returns the yaw angle.
virtual Eigen::Map< const
Eigen::VectorXs > getVector () const
Returns a (mapped) vector of the state unit.
virtual Eigen::Map< const
Eigen::Quaternions > getQuaternion () const
Returns a (mapped) quaternion of the state unit.
void normalize ()
Normalizes the quaternion.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints all the elements of the state unit.
Public Member Functions inherited from StateOrientation
StateOrientation (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
StateOrientation (WolfScalar *_st_ptr)
Constructor with scalar pointer.
virtual ~StateOrientation ()
Destructor.
Eigen::Matrix3s getRotationMatrix () const
Returns the 3x3 rotation matrix of the orientation.
Public Member Functions inherited from StateBase
StateBase (WolfScalar *_st_ptr)
Constructor with scalar pointer.
StateBase (Eigen::VectorXs &_st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit.
virtual ~StateBase ()
Destructor.
virtual WolfScalar * getPtr ()
Returns the pointer to the first element of the state.
virtual void setPtr (WolfScalar *_new_ptr)
Set the pointer of the first element of the state.
StateStatus getStateStatus () const
Returns the status of the state unit.
void setStateStatus (const StateStatus &_status)
Set the status of the state unit.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Static Public Attributes
static const unsigned int BLOCK_SIZE = 4
Additional Inherited Members
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Protected Attributes inherited from StateBase
WolfScalar * state_ptr_
StateStatus status_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 15 of file state_quaternion.h.
Constructor & Destructor Documentation
StateQuaternion::StateQuaternion (Eigen::VectorXs & _st_remote, const unsigned int _idx)
Constructor with whole state storage and index where starts the state unit
Parameters
_st_remote is the whole state vector
_idx is the index of the first element of the state in the whole state vector
Definition at line 3 of file state_quaternion.cpp.
StateQuaternion::StateQuaternion (WolfScalar * _st_ptr)
Constructor with scalar pointer
Parameters
_st_ptr is the pointer of the first element of the state unit
Definition at line 9 of file state_quaternion.cpp.
StateQuaternion::~StateQuaternion () virtual
Destructor
Definition at line 15 of file state_quaternion.cpp.
Member Function Documentation
StateType StateQuaternion::getStateType () const virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 20 of file state_quaternion.cpp.
References ST_QUATERNION.
unsigned int StateQuaternion::getStateSize () const virtual
Returns the parametrizationType (see wolf.h) of the state unit
Implements StateBase.
Definition at line 25 of file state_quaternion.cpp.
References BLOCK_SIZE.
void StateQuaternion::rotationMatrix (Eigen::Matrix3s & R) const virtual
Returns the 3x3 rotation matrix of the orientation
Implements StateOrientation.
Definition at line 37 of file state_quaternion.cpp.
References StateBase::state_ptr_.
WolfScalar StateQuaternion::getYaw () const virtual
Returns the yaw angle
Implements StateOrientation.
Definition at line 62 of file state_quaternion.cpp.
References StateBase::state_ptr_.
Eigen::Map< const Eigen::VectorXs > StateQuaternion::getVector () const virtual
Returns a (mapped) vector of the state unit
Implements StateOrientation.
Definition at line 71 of file state_quaternion.cpp.
References StateBase::state_ptr_.
Eigen::Map< const Eigen::Quaternions > StateQuaternion::getQuaternion () const virtual
Returns a (mapped) quaternion of the state unit
Definition at line 76 of file state_quaternion.cpp.
References StateBase::state_ptr_.
void StateQuaternion::normalize ()
Normalizes the quaternion
Definition at line 81 of file state_quaternion.cpp.
References StateBase::state_ptr_.
Referenced by main().
void StateQuaternion::print (unsigned int _ntabs = 0, std::ostream & _ost = std::cout) const virtual
Prints all the elements of the state unit
Implements StateBase.
Definition at line 87 of file state_quaternion.cpp.
References BLOCK_SIZE, NodeBase::nodeId(), NodeBase::nodeLabel(), NodeBase::printTabs(), and StateBase::state_ptr_.
Field Documentation
const unsigned int StateQuaternion::BLOCK_SIZE = 4 static
Definition at line 18 of file state_quaternion.h.
Referenced by getStateSize(), and print().
The documentation for this class was generated from the following files:
state_quaternion.h
state_quaternion.cpp