WOLF: WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT > Class Template Reference
WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT > Class Template Reference
#include <wolf_manager.h>
Public Member Functions
WolfManager (SensorBase *_sensor_prior, const bool _complex_angle, const unsigned int &_state_length, const unsigned int &_w_size=10)
virtual ~WolfManager ()
void createFrame (const Eigen::VectorXs &_frame_state, const TimeStamp &_time_stamp)
void addCapture (CaptureBase *_capture)
void update ()
const Eigen::VectorXs getState () const
StateBaseList * getStateListPtr ()
void getConstraintsList (ConstraintBaseList &corr_list)
RadarOdom * getProblemPtr ()
void printTree ()
WolfManager (const unsigned int &_state_length=1000, const bool _complex_angle=false)
virtual ~WolfManager ()
unsigned int getConstraintsSize ()
void createFrame (const VectorXs &_frame_state, const TimeStamp &_time_stamp)
void addCapture (const VectorXs &_odom_capture, const WolfScalar &_time_stamp, SensorBase *_sensor_ptr)
void computeOdomCapture (CaptureXBase *_odom_capture)
void computeGPSCapture (CaptureXBase *_gps_capture)
void update (std::queue< StateBase * > &new_state_units, std::queue< ConstraintXBase * > &new_constraints)
VectorXs getState ()
ConstraintXBase * getConstraintPrt (unsigned int i)
std::queue< StateBase * > getStateUnitsPtrs (unsigned int i)
WolfManager (SensorBase *_sensor_prior, const bool _complex_angle, const unsigned int &_state_length=1000)
virtual ~WolfManager ()
void createFrame (const VectorXs &_frame_state, const TimeStamp &_time_stamp)
void addCapture (CaptureBase *_capture)
void update (std::list< StateBase * > &new_state_units, std::list< ConstraintBase * > &new_constraints)
VectorXs getState ()
std::list< StateBase * > getStateList ()
std::list< ConstraintBase * > getConstraintsList ()
void printTree ()
WolfManager (const unsigned int &_state_length, SensorBase *_sensor_prior, const Eigen::VectorXs &_init_frame, const Eigen::MatrixXs &_init_frame_cov, const unsigned int &_w_size=10, const WolfScalar &_new_frame_elapsed_time=0.1)
virtual ~WolfManager ()
void createFrame (const Eigen::VectorXs &_frame_state, const TimeStamp &_time_stamp)
void createFrame (const TimeStamp &_time_stamp)
void addCapture (CaptureBase *_capture)
void manageWindow ()
bool checkNewFrame (CaptureBase *new_capture)
void update ()
Eigen::VectorXs getVehiclePose (const TimeStamp &_now=0)
WolfProblem * getProblemPtr ()
void setWindowSize (const unsigned int &_size)
void setNewFrameElapsedTime (const WolfScalar &_dt)
Protected Attributes
bool use_complex_angles_
RadarOdom * problem_
std::queue< CaptureBase * > new_captures_
SensorBase * sensor_prior_
unsigned int window_size_
FrameBaseIter first_window_frame_
VectorXs state_
unsigned int first_empty_state_
std::vector< FrameBase * > frames_
std::vector< ConstraintXBase * > constraints_
std::vector< VectorXs > odom_captures_
std::vector< VectorXs > gps_captures_
std::queue< CaptureXBase * > new_captures_
std::vector< CaptureXBase * > captures_
TrajectoryBase * trajectory_
WolfProblem * problem_
FrameBase * current_frame_
FrameBase * previous_frame_
CaptureRelative * last_capture_relative_
CaptureRelative * second_last_capture_relative_
WolfScalar new_frame_elapsed_time_
Detailed Description
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState>
class WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >
Definition at line 110 of file test_ceres_laser.cpp.
Constructor & Destructor Documentation
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager (SensorBase * _sensor_prior, const bool _complex_angle, const unsigned int & _state_length, const unsigned int & _w_size = 10) inline
Definition at line 121 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::use_complex_angles_.
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::~WolfManager () inline virtual
Definition at line 135 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager (const unsigned int & _state_length = 1000, const bool _complex_angle = false) inline
Definition at line 314 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> virtual WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::~WolfManager () inline virtual
Definition at line 329 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager (SensorBase * _sensor_prior, const bool _complex_angle, const unsigned int & _state_length = 1000) inline
Definition at line 60 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> virtual WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::~WolfManager () inline virtual
Definition at line 75 of file test_ceres_manager_tree.cpp.
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager (const unsigned int & _state_length, SensorBase * _sensor_prior, const Eigen::VectorXs & _init_frame, const Eigen::MatrixXs & _init_frame_cov, const unsigned int & _w_size = 10, const WolfScalar & _new_frame_elapsed_time = 0.1)
Definition at line 102 of file wolf_manager.h.
References FrameBase::addCapture(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::current_frame_, WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::first_window_frame_, WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_, and CaptureFix::processCapture().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> virtual WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::~WolfManager () virtual
Member Function Documentation
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame (const Eigen::VectorXs & _frame_state, const TimeStamp & _time_stamp) inline
Definition at line 140 of file test_ceres_laser.cpp.
References StateComplexAngle::getStateSize(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_, WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::sensor_prior_, and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::use_complex_angles_.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager().
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture (CaptureBase * _capture) inline
Definition at line 163 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::new_captures_, and NodeBase::nodeId().
Referenced by main().
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update () inline
Definition at line 169 of file test_ceres_laser.cpp.
References CaptureBase::computePrior(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::first_window_frame_, TimeStamp::get(), CaptureBase::getSensorPtr(), CaptureBase::getTimeStamp(), CaptureRelative::integrateCapture(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::new_captures_, NodeBase::nodeId(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_, WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::sensor_prior_, and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::window_size_.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> const Eigen::VectorXs WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState () const inline
Definition at line 240 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> StateBaseList* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateListPtr () inline
Definition at line 245 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getConstraintsList (ConstraintBaseList & corr_list) inline
Definition at line 250 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > WolfProblem * WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr () inline
Definition at line 255 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::printTree () inline
Definition at line 260 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> unsigned int WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getConstraintsSize () inline
Definition at line 345 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame (const VectorXs & _frame_state, const TimeStamp & _time_stamp) inline
Definition at line 350 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture (const VectorXs & _odom_capture, const WolfScalar & _time_stamp, SensorBase * _sensor_ptr) inline
Definition at line 375 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::computeOdomCapture (CaptureXBase * _odom_capture) inline
Definition at line 380 of file test_ceres_manager.cpp.
References CaptureXBase::capture, FrameBase::getOPtr(), FrameBase::getPPtr(), StateBase::getPtr(), CaptureXBase::getPtr(), and CaptureXBase::time_stamp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::computeGPSCapture (CaptureXBase * _gps_capture) inline
Definition at line 426 of file test_ceres_manager.cpp.
References CaptureXBase::getPtr().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update (std::queue< StateBase * > & new_state_units, std::queue< ConstraintXBase * > & new_constraints) inline
Definition at line 435 of file test_ceres_manager.cpp.
References GPS_FIX, and ODOM_2D.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> VectorXs WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState () inline
Definition at line 458 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> ConstraintXBase* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getConstraintPrt (unsigned int i) inline
Definition at line 463 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::queue<StateBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateUnitsPtrs (unsigned int i) inline
Definition at line 468 of file test_ceres_manager.cpp.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame (const VectorXs & _frame_state, const TimeStamp & _time_stamp) inline
Definition at line 80 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture (CaptureBase * _capture) inline
Definition at line 105 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update (std::list< StateBase * > & new_state_units, std::list< ConstraintBase * > & new_constraints) inline
Definition at line 110 of file test_ceres_manager_tree.cpp.
References CaptureBase::computePrior(), CaptureBase::getFeatureListPtr(), CaptureBase::getSensorPtr(), CaptureBase::getTimeStamp(), and CaptureBase::processCapture().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> VectorXs WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState () inline
Definition at line 157 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::list<StateBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateList () inline
Definition at line 162 of file test_ceres_manager_tree.cpp.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::list<ConstraintBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getConstraintsList () inline
Definition at line 176 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::printTree () inline
Definition at line 193 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame (const Eigen::VectorXs & _frame_state, const TimeStamp & _time_stamp)
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame (const TimeStamp & _time_stamp)
Definition at line 214 of file wolf_manager.h.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture (CaptureBase * _capture)
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::manageWindow ()
Definition at line 230 of file wolf_manager.h.
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > bool WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::checkNewFrame (CaptureBase * new_capture)
Definition at line 245 of file wolf_manager.h.
References TimeStamp::get(), and CaptureBase::getTimeStamp().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update ()
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > Eigen::VectorXs WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getVehiclePose (const TimeStamp & _now = 0)
Definition at line 311 of file wolf_manager.h.
Referenced by main().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfProblem* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr ()
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::setWindowSize (const unsigned int & _size)
Definition at line 326 of file wolf_manager.h.
template<class StatePositionT , class StateOrientationT , class StateVelocityT , class StateOmegaT > void WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::setNewFrameElapsedTime (const WolfScalar & _dt)
Definition at line 332 of file wolf_manager.h.
Field Documentation
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> bool WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::use_complex_angles_ protected
Definition at line 113 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> RadarOdom* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_ protected
Definition at line 114 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getConstraintsList(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateListPtr(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::printTree(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::~WolfManager().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::queue< CaptureBase * > WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::new_captures_ protected
Definition at line 115 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> SensorBase * WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::sensor_prior_ protected
Definition at line 116 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::createFrame(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> unsigned int WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::window_size_ protected
Definition at line 117 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> FrameBaseIter WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::first_window_frame_ protected
Definition at line 118 of file test_ceres_laser.cpp.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> VectorXs WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::state_ protected
Definition at line 303 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> unsigned int WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::first_empty_state_ protected
Definition at line 304 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::vector<FrameBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::frames_ protected
Definition at line 306 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::vector<ConstraintXBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::constraints_ protected
Definition at line 307 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::vector< VectorXs > WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::odom_captures_ protected
Definition at line 308 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::vector< VectorXs > WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::gps_captures_ protected
Definition at line 309 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::queue<CaptureXBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::new_captures_ protected
Definition at line 310 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> std::vector<CaptureXBase*> WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::captures_ protected
Definition at line 311 of file test_ceres_manager.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> TrajectoryBase* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::trajectory_ protected
Definition at line 53 of file test_ceres_manager_tree.cpp.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfProblem* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::problem_ protected
Definition at line 49 of file wolf_manager.h.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> FrameBase* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::current_frame_ protected
Definition at line 56 of file wolf_manager.h.
Referenced by WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::WolfManager().
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> FrameBase* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::previous_frame_ protected
Definition at line 57 of file wolf_manager.h.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> CaptureRelative* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::last_capture_relative_ protected
Definition at line 58 of file wolf_manager.h.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> CaptureRelative* WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::second_last_capture_relative_ protected
Definition at line 59 of file wolf_manager.h.
template<class StatePositionT, class StateOrientationT, class StateVelocityT = NoState, class StateOmegaT = NoState> WolfScalar WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::new_frame_elapsed_time_ protected
Definition at line 64 of file wolf_manager.h.
The documentation for this class was generated from the following files:
test_ceres_laser.cpp
test_ceres_manager.cpp
test_ceres_manager_tree.cpp
wolf_manager.h