WOLF: PinHole Class Reference
PinHole Class Reference
#include <pin_hole.h>
Public Member Functions
PinHole (StatePose &_sp, Eigen::VectorXs _intrinsic, const NodeLocation _loc=MID)
virtual ~PinHole ()
const Eigen::Matrix3s & intrinsiMatrix () const
const Eigen::Matrix3s & inverseIntrinsicMatrix () const
virtual void precomputeConstants ()
Public Member Functions inherited from SensorBase
const Eigen::Map
< Eigen::VectorXs > & intrinsic () const
const StatePose & pose () const
Public Member Functions inherited from NodeLinked< VehicleBase, NodeTerminus >
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from Node
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
Additional Inherited Members
Protected Types inherited from NodeLinked< VehicleBase, NodeTerminus >
typedef VehicleBase * UpNodePtr
typedef NodeTerminus * DownNodePtr
typedef std::shared_ptr
< VehicleBase > UpNodeShPtr
typedef std::shared_ptr
< NodeTerminus > DownNodeShPtr
typedef std::list< DownNodeShPtr > DownNodeList
typedef DownNodeList::iterator DownNodeIter
Protected Member Functions inherited from SensorBase
SensorBase (const StatePose &_local_pose, const NodeLocation _loc=MID)
SensorBase (const StatePose &_local_pose, const Eigen::VectorXs _intrinsic, const NodeLocation _loc=MID)
virtual ~SensorBase ()
Protected Member Functions inherited from NodeLinked< VehicleBase, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
NodeLinked (const NodeLocation _loc, const std::string &_label, const UpNodeShPtr &_up_node_ptr)
Constructor specifying up node.
~NodeLinked ()
Default destructor.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpNode (const UpNodeShPtr &_pptr)
Sets link to up node.
void unlinkFromUpNode ()
Clears link to up node.
const UpNodePtr upNodePtr () const
Access the pointer to parent.
const VehicleBase & upNode () const
Gets a reference to parent.
void addDownNode (const DownNodeShPtr &_ptr)
Adds a down node.
DownNodeList & downNodeList ()
Gets a reference to down node list.
const DownNodeList & downNodeList () const
Gets a constant reference to down node list.
void removeDownNode (const DownNodeIter &_iter)
Removes a down node from list, given an iterator.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUp (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
void printDown (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Protected Member Functions inherited from Node
Node (std::string _label)
Constructor from label.
virtual ~Node ()
Default destructor.
void printNTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Detailed Description
Definition at line 13 of file pin_hole.h.
Constructor & Destructor Documentation
PinHole::PinHole (StatePose & _sp, Eigen::VectorXs _intrinsic, const NodeLocation _loc = MID) inline
Definition at line 39 of file pin_hole.h.
References precomputeConstants().
PinHole::~PinHole () inline virtual
Definition at line 45 of file pin_hole.h.
Member Function Documentation
const Eigen::Matrix3s & PinHole::intrinsiMatrix () const inline
Definition at line 50 of file pin_hole.h.
const Eigen::Matrix3s & PinHole::inverseIntrinsicMatrix () const inline
Definition at line 55 of file pin_hole.h.
Referenced by EpipolarConstraint::computeExpectation(), and TransPinHole::precomputeConstants().
void PinHole::precomputeConstants () inline virtual
Definition at line 60 of file pin_hole.h.
Referenced by PinHole().
The documentation for this class was generated from the following file:
pin_hole.h