WOLF: CorrespondenceOdom2D Class Reference
CorrespondenceOdom2D Class Reference
Public Member Functions
CorrespondenceOdom2D (WolfScalar *_st, const Eigen::Vector2s &_odom)
virtual ~CorrespondenceOdom2D ()
double * getPosePreviousPtr ()
double * getPoseCurrentPtr ()
virtual void display () const
CorrespondenceOdom2D (WolfScalar *_st_prev, WolfScalar *_st_curr, const Eigen::Vector2s &_odom)
pose_previous_ (_st_prev)
pose_current_ (_st_curr)
odom_inc_ (_odom.data())
virtual ~CorrespondenceOdom2D ()
virtual void addToProblem (ceres::Problem &_problem)
virtual void display () const
Public Member Functions inherited from CorrespondenceBaseX
CorrespondenceBaseX (const unsigned int _nb, const std::vector< unsigned int > &_bindexes, const std::vector< unsigned int > &_bsizes)
virtual ~CorrespondenceBaseX ()
ceres::CostFunction * getCostFunctionPtr ()
CorrespondenceBaseX (const unsigned int _nb, const std::vector< unsigned int > &_bsizes)
virtual ~CorrespondenceBaseX ()
virtual void removeFromProblem (ceres::Problem &_problem)
Public Member Functions inherited from NodeLinked< FeatureBaseX, NodeTerminus >
NodeLinked (const NodeLocation _loc, const std::string &_label)
Constructor without specify up node.
virtual ~NodeLinked ()
Constructor specifying up node.
bool isTop () const
Checks if node is on the top of Wolf tree.
bool isBottom () const
Checks if node is at the bottom of Wolf tree.
void linkToUpperNode (UpperNodePtr _pptr)
Sets link to up node.
void unlinkFromUpperNode ()
Clears link to up node.
const UpperNodePtr upperNodePtr () const
Access the pointer to parent.
const FeatureBaseX & upperNode () const
Gets a reference to parent.
void addDownNode (LowerNodePtr _ptr)
Adds a down node.
LowerNodeList & downNodeList () const
Gets a reference to down node list.
LowerNodeList * getDownNodeListPtr ()
Gets a constant reference to down node list.
void removeDownNode (const LowerNodeIter &_iter)
Gets a const pointer to down node list.
void removeDownNode (const LowerNodePtr _ptr)
Removes a down node from list, given a pointer.
void removeDownNode (const unsigned int _id)
Removes a down node from the list, given a node id.
virtual WolfProblem * getTop ()
Gets a pointer to the tree top node.
virtual void print (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints node information.
Public Member Functions inherited from NodeBase
NodeBase (std::string _label, bool _verbose=false)
Constructor from label.
virtual ~NodeBase ()
Default destructor.
unsigned int nodeId () const
Gets node ID.
std::string nodeLabel () const
Gets node label.
PendingStatus getPendingStatus () const
Gets the node pending status (pending or not to be added/updated in the filter or optimizer)
void setPendingStatus (PendingStatus _pending)
Sets the node pending status (pending or not to be added/updated in the filter or optimizer)
Protected Attributes
Eigen::Map< Eigen::Vector3s > pose_previous_
Eigen::Map< Eigen::Vector3s > pose_current_
Eigen::Map< const Eigen::Vector2s > odom_inc_
Protected Attributes inherited from CorrespondenceBaseX
unsigned int nblocks_
std::vector< unsigned int > block_indexes_
std::vector< unsigned int > block_sizes_
ceres::CostFunction * cost_function_ptr_
ceres::ResidualBlockId ceres_residual_block_id_
Protected Attributes inherited from NodeLinked< FeatureBaseX, NodeTerminus >
NodeLocation location_
UpperNodePtr up_node_ptr_
LowerNodeList down_node_list_
Protected Attributes inherited from NodeBase
std::string label_
Text label identifying the node.
unsigned int node_id_
Node id. It is unique over the whole Wolf Tree.
PendingStatus node_pending_
Pending to be added/updated in the filter or optimizer.
bool verbose_
Additional Inherited Members
Public Types inherited from NodeLinked< FeatureBaseX, NodeTerminus >
typedef FeatureBaseX * UpperNodePtr
typedef NodeTerminus * LowerNodePtr
Protected Types inherited from NodeLinked< FeatureBaseX, NodeTerminus >
typedef std::list< LowerNodePtr > LowerNodeList
typedef LowerNodeList::iterator LowerNodeIter
Protected Member Functions inherited from NodeLinked< FeatureBaseX, NodeTerminus >
virtual void printSelf (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints tabulated information about this node.
void printUpper (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints upper node info.
void printLower (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
Prints recursively lower node info.
Protected Member Functions inherited from NodeBase
void printTabs (unsigned int _ntabs=0, std::ostream &_ost=std::cout) const
prints a number of tabulations.
Static Protected Attributes inherited from NodeBase
static unsigned int node_id_count_ = 0
Object counter (acts as simple ID factory)
Detailed Description
Definition at line 191 of file test_ceres_odom_batch.cpp.
Constructor & Destructor Documentation
CorrespondenceOdom2D::CorrespondenceOdom2D (WolfScalar * _st, const Eigen::Vector2s & _odom) inline
Definition at line 199 of file test_ceres_odom_batch.cpp.
virtual CorrespondenceOdom2D::~CorrespondenceOdom2D () inline virtual
Definition at line 208 of file test_ceres_odom_batch.cpp.
CorrespondenceOdom2D::CorrespondenceOdom2D (WolfScalar * _st_prev, WolfScalar * _st_curr, const Eigen::Vector2s & _odom) inline
Definition at line 209 of file test_ceres_odom_iterative.cpp.
virtual CorrespondenceOdom2D::~CorrespondenceOdom2D () inline virtual
Definition at line 218 of file test_ceres_odom_iterative.cpp.
Member Function Documentation
double* CorrespondenceOdom2D::getPosePreviousPtr () inline
Definition at line 213 of file test_ceres_odom_batch.cpp.
References pose_previous_.
Referenced by main().
double* CorrespondenceOdom2D::getPoseCurrentPtr () inline
Definition at line 218 of file test_ceres_odom_batch.cpp.
References pose_current_.
Referenced by main().
virtual void CorrespondenceOdom2D::display () const inline virtual
Reimplemented from CorrespondenceBaseX.
Definition at line 223 of file test_ceres_odom_batch.cpp.
References CorrespondenceBaseX::display(), odom_inc_, pose_current_, and pose_previous_.
CorrespondenceOdom2D::pose_previous_ (_st_prev)
CorrespondenceOdom2D::pose_current_ (_st_curr)
CorrespondenceOdom2D::odom_inc_ (_odom. data()) inline
Definition at line 213 of file test_ceres_odom_iterative.cpp.
References CorrespondenceBaseX::cost_function_ptr_.
virtual void CorrespondenceOdom2D::addToProblem (ceres::Problem & _problem) inline virtual
Implements CorrespondenceBaseX.
Definition at line 233 of file test_ceres_odom_iterative.cpp.
References CorrespondenceBaseX::ceres_residual_block_id_, CorrespondenceBaseX::cost_function_ptr_, pose_current_, and pose_previous_.
Referenced by main().
virtual void CorrespondenceOdom2D::display () const inline virtual
Reimplemented from CorrespondenceBaseX.
Definition at line 238 of file test_ceres_odom_iterative.cpp.
References CorrespondenceBaseX::display(), odom_inc_, pose_current_, and pose_previous_.
Field Documentation
Eigen::Map< Eigen::Vector3s > CorrespondenceOdom2D::pose_previous_ protected
Definition at line 194 of file test_ceres_odom_batch.cpp.
Referenced by addToProblem(), display(), and getPosePreviousPtr().
Eigen::Map< Eigen::Vector3s > CorrespondenceOdom2D::pose_current_ protected
Definition at line 195 of file test_ceres_odom_batch.cpp.
Referenced by addToProblem(), display(), and getPoseCurrentPtr().
Eigen::Map< const Eigen::Vector2s > CorrespondenceOdom2D::odom_inc_ protected
Definition at line 196 of file test_ceres_odom_batch.cpp.
Referenced by display().
The documentation for this class was generated from the following files:
test_ceres_odom_batch.cpp
test_ceres_odom_iterative.cpp