WOLF: Wolf Namespace Reference
Wolf Namespace Reference
Namespace for diverse helper functions within Wolf.
Functions
template<class V3 >
Quaternions quaternionFromVector (const V3 &rvec)
template<class Vin >
Eigen::Vector2s lineRhothetaFromHmg (const Vin &_hmglin)
rho-theta line specification from homogeneous specification
template<class Vin , class Mout >
void skew (const Vin &v, Mout &V_x)
Build 3x3 skey symmetric matrix.
template<class Vin >
Eigen::Matrix3s skew (const Vin &v)
Build 3x3 skey symmetric matrix.
template<class P , class L >
WolfScalar distPointToLine (const P &_point, const L &_line)
Signed distance from homogeneous 2d point to homogeneous 2d line.
template<class BaseType , class LocalType , class ResultType >
StatePose composeFrames (const BaseType &_base_pose, const LocalType &_local_pose)
compose frames
template<class BaseType , class LocalType , class ResultType >
void composeFrames (const BaseType &_base_pose, const LocalType &_local_pose, ResultType &_result_pose)
compose frames
Detailed Description
Namespace for diverse helper functions within Wolf.
All these functions should be somewhere appropriate. Then, a good namespace for the project would be Wolf, but for everything in Wolf and not just helper functions.
Function Documentation
template<class V3 > Quaternions Wolf::quaternionFromVector (const V3 & rvec)
Quaternion from rotation vector
Definition at line 27 of file quaternion_tools.h.
Referenced by StateErrorPQV::compose(), and StateErrorPose::compose().
template<class Vin > Eigen::Vector2s Wolf::lineRhothetaFromHmg (const Vin & _hmglin)
Parameters
_hmglin a homogeneous line
Returns
the rho-theta line (rho, theta)
Definition at line 31 of file wolf_tools.h.
template<class Vin , class Mout > void Wolf::skew (const Vin & v, Mout & V_x) inline
Parameters
v a 3-vector
V_x the skew-symmetric matrix. This is the return value.
The skew-symmetric matrix is defined by
[v]_x = [ [   0 , -v(2),  v(1) ] [ v(2),    0 , -v(0) ] [-v(1),  v(0),    0  ] ]
Definition at line 57 of file wolf_tools.h.
Referenced by EpipolarConstraint::computeExpectation(), TransPinHole::precomputeConstants(), and skew().
template<class Vin > Eigen::Matrix3s Wolf::skew (const Vin & v) inline
Parameters
v a 3-vector
Returns
the skew-symmetric matrix
The skew-symmetric matrix is defined by
[v]_x = [ [   0 , -v(2),  v(1) ] [ v(2),    0 , -v(0) ] [-v(1),  v(0),    0  ] ]
Definition at line 90 of file wolf_tools.h.
References skew().
template<class P , class L > WolfScalar Wolf::distPointToLine (const P & _point, const L & _line) inline
Signed distance from homogeneous 2d point to homogeneous 2d line. This is computed as
Note: Although we'll want to minimize absolute distance, the sign is necessary to correctly generate signed Jacobians and guide the optimizer towards the correct direction.
Definition at line 108 of file wolf_tools.h.
Referenced by EpipolarConstraint::computeError().
template<class BaseType , class LocalType , class ResultType > StatePose Wolf::composeFrames (const BaseType & _base_pose, const LocalType & _local_pose) inline
Parameters
_base_pose base frame to compose. Acts as global wrt _local_pose.
_local_pose local frame to compose with. Acts as local wrt _base_pose.
Returns
a composed frame, _base_pose * _local_pose
Composes a local frame on top of a base frame.
Definition at line 126 of file wolf_tools.h.
Referenced by Capture::precomputeGlobalPose(), and TransSensor::precomputePoseRelative().
template<class BaseType , class LocalType , class ResultType > void Wolf::composeFrames (const BaseType & _base_pose, const LocalType & _local_pose, ResultType & _result_pose) inline
Parameters
_base_pose base frame to compose. Acts as global wrt _local_pose.
_local_pose local frame to compose with. Acts as local wrt _base_pose.
_result_pose the composed frame, _base_pose * _local_pose. This is the return value.
Composes a local frame on top of a base frame.
Definition at line 140 of file wolf_tools.h.
References StatePose::p().