WOLF: test_ceres_2_lasers.cpp File Reference
test_ceres_2_lasers.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include "glog/logging.h"
#include "wolf_manager.h"
#include "ceres_wrapper/ceres_manager.h"
#include "unistd.h"
#include "faramotics/dynamicSceneRender.h"
#include "faramotics/rangeScan2D.h"
#include "btr-headers/pose3d.h"
#include "iri-algorithms/laser_scan_utils/corner_detector.h"
#include "iri-algorithms/laser_scan_utils/entities.h"
Functions
void motionCampus (unsigned int ii, Cpose3d &pose, double &displacement_, double &rotation_)
int main (int argc, char **argv)
Function Documentation
void motionCampus (unsigned int ii, Cpose3d & pose, double & displacement_, double & rotation_)
Definition at line 35 of file test_ceres_2_lasers.cpp.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 87 of file test_ceres_2_lasers.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), CeresManager::computeCovariances(), CaptureLaser2D::extractCorners(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getVehiclePose(), motionCampus(), CeresManager::solve(), CeresManager::update(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().