WOLF: test_ceres_manager_tree.cpp File Reference
test_ceres_manager_tree.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include "ceres/ceres.h"
#include "glog/logging.h"
#include "wolf.h"
#include "sensor_base.h"
#include "sensor_odom_2D.h"
#include "sensor_gps_fix.h"
#include "frame_base.h"
#include "state_point.h"
#include "state_complex_angle.h"
#include "capture_base.h"
#include "capture_relative.h"
#include "capture_odom_2D.h"
#include "capture_gps_fix.h"
#include "state_base.h"
#include "constraint_sparse.h"
#include "constraint_gps_2D.h"
#include "constraint_odom_2D_theta.h"
#include "constraint_odom_2D_complex_angle.h"
#include "ceres_wrapper/ceres_manager.h"
Data Structures
class WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 199 of file test_ceres_manager_tree.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), CeresManager::addConstraints(), CeresManager::addStateUnits(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateList(), CeresManager::solve(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().