WOLF: test_ceres_wrapper_jet.cpp File Reference
test_ceres_wrapper_jet.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include "ceres/jet.h"
#include "ceres/ceres.h"
#include "glog/logging.h"
#include "sensor_base.h"
#include "frame_base.h"
#include "state_point.h"
#include "state_complex_angle.h"
#include "capture_base.h"
#include "state_base.h"
#include "wolf.h"
#include "ceres_wrapper/complex_angle_parametrization.h"
#include "node_terminus.h"
#include "node_linked.h"
Data Structures
class WolfVehicle
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 155 of file test_ceres_wrapper_jet.cpp.
References WolfVehicle::computePrior(), WolfVehicle::getPrior(), WolfVehicle::inventMeasurements(), WolfVehicle::print(), and WolfVehicle::resizeState().