WOLF: test_incremental_ccolamd_blocks.cpp File Reference
test_incremental_ccolamd_blocks.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/OrderingMethods>
#include <eigen3/Eigen/CholmodSupport>
#include <eigen3/Eigen/SparseLU>
#include "solver/ccolamd_ordering.h"
Functions
void eraseSparseBlock (SparseMatrix< double > &original, const unsigned int &row, const unsigned int &Nrows, const unsigned int &col, const unsigned int &Ncols)
void addSparseBlock (const MatrixXd &ins, SparseMatrix< double > &original, const unsigned int &row, const unsigned int &col)
void permutation_2_block_permutation (const PermutationMatrix< Dynamic, Dynamic, int > &perm, PermutationMatrix< Dynamic, Dynamic, int > &perm_blocks, const int dim, const int size)
int main (int argc, char *argv[])
Function Documentation
void eraseSparseBlock (SparseMatrix< double > & original, const unsigned int & row, const unsigned int & Nrows, const unsigned int & col, const unsigned int & Ncols)
Definition at line 29 of file test_incremental_ccolamd_blocks.cpp.
void addSparseBlock (const MatrixXd & ins, SparseMatrix< double > & original, const unsigned int & row, const unsigned int & col)
Definition at line 38 of file test_incremental_ccolamd_blocks.cpp.
Referenced by main().
void permutation_2_block_permutation (const PermutationMatrix< Dynamic, Dynamic, int > & perm, PermutationMatrix< Dynamic, Dynamic, int > & perm_blocks, const int dim, const int size)
Definition at line 46 of file test_incremental_ccolamd_blocks.cpp.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 59 of file test_incremental_ccolamd_blocks.cpp.
References addSparseBlock(), and permutation_2_block_permutation().