WOLF: test_iQR.cpp File Reference
test_iQR.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/OrderingMethods>
#include <eigen3/Eigen/SparseQR>
#include <Eigen/SPQRSupport>
#include "solver/ccolamd_ordering.h"
Data Structures
class block_pruning
Functions
void eraseSparseBlock (SparseMatrix< double > &original, const unsigned int &row, const unsigned int &col, const unsigned int &Nrows, const unsigned int &Ncols)
void addSparseBlock (const MatrixXd &ins, SparseMatrix< double > &original, const unsigned int &row, const unsigned int &col)
void permutation_2_block_permutation (const PermutationMatrix< Dynamic, Dynamic, int > &perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > &perm_variables, const int dim)
void augment_permutation (PermutationMatrix< Dynamic, Dynamic, int > &perm, const int new_size)
int main (int argc, char *argv[])
Function Documentation
void eraseSparseBlock (SparseMatrix< double > & original, const unsigned int & row, const unsigned int & col, const unsigned int & Nrows, const unsigned int & Ncols)
Definition at line 54 of file test_iQR.cpp.
Referenced by main().
void addSparseBlock (const MatrixXd & ins, SparseMatrix< double > & original, const unsigned int & row, const unsigned int & col)
Definition at line 70 of file test_iQR.cpp.
Referenced by main().
void permutation_2_block_permutation (const PermutationMatrix< Dynamic, Dynamic, int > & perm_nodes, PermutationMatrix< Dynamic, Dynamic, int > & perm_variables, const int dim)
Definition at line 78 of file test_iQR.cpp.
Referenced by main().
void augment_permutation (PermutationMatrix< Dynamic, Dynamic, int > & perm, const int new_size)
Definition at line 89 of file test_iQR.cpp.
Referenced by SolverQR::add_state_unit(), and main().
int main (int argc, char * argv[])
Definition at line 102 of file test_iQR.cpp.
References addSparseBlock(), augment_permutation(), eraseSparseBlock(), and permutation_2_block_permutation().