WOLF: test_iQR_wolf2.cpp File Reference
test_iQR_wolf2.cpp File Reference
#include <cstdlib>
#include <string>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include "state_base.h"
#include "constraint_base.h"
#include "wolf_manager.h"
#include "solver/qr_solver.h"
#include "unistd.h"
#include "faramotics/dynamicSceneRender.h"
#include "faramotics/rangeScan2D.h"
#include "btr-headers/pose3d.h"
#include "glog/logging.h"
#include "ceres_wrapper/ceres_manager.h"
#include "iri-algorithms/laser_scan_utils/corner_detector.h"
#include "iri-algorithms/laser_scan_utils/entities.h"
Functions
void motionCampus (unsigned int ii, Cpose3d &pose, double &displacement_, double &rotation_)
int main (int argc, char *argv[])
Function Documentation
void motionCampus (unsigned int ii, Cpose3d & pose, double & displacement_, double & rotation_)
Definition at line 46 of file test_iQR_wolf2.cpp.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 100 of file test_iQR_wolf2.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), CaptureLaser2D::extractCorners(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getVehiclePose(), motionCampus(), CeresManager::solve(), SolverQR::solve(), CeresManager::update(), SolverQR::update(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().