WOLF: test_ceres_laser.cpp File Reference
test_ceres_laser.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include "ceres/ceres.h"
#include "glog/logging.h"
#include "wolf.h"
#include "sensor_base.h"
#include "sensor_odom_2D.h"
#include "sensor_gps_fix.h"
#include "feature_base.h"
#include "frame_base.h"
#include "state_point.h"
#include "state_complex_angle.h"
#include "capture_base.h"
#include "capture_relative.h"
#include "capture_odom_2D.h"
#include "capture_gps_fix.h"
#include "capture_laser_2D.h"
#include "state_base.h"
#include "constraint_sparse.h"
#include "constraint_gps_2D.h"
#include "constraint_odom_2D_theta.h"
#include "constraint_odom_2D_complex_angle.h"
#include "trajectory_base.h"
#include "map_base.h"
#include "wolf_problem.h"
#include "ceres_wrapper/ceres_manager.h"
#include "unistd.h"
#include "faramotics/dynamicSceneRender.h"
#include "faramotics/rangeScan2D.h"
#include "btr-headers/pose3d.h"
#include "iri-algorithms/laser_scan_utils/corner_detector.h"
#include "iri-algorithms/laser_scan_utils/entities.h"
Data Structures
class WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >
Functions
void motionCampus (unsigned int ii, Cpose3d &pose, double &displacement_, double &rotation_)
int main (int argc, char **argv)
Function Documentation
void motionCampus (unsigned int ii, Cpose3d & pose, double & displacement_, double & rotation_)
Definition at line 58 of file test_ceres_laser.cpp.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 266 of file test_ceres_laser.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), CaptureLaser2D::extractCorners(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getProblemPtr(), motionCampus(), TimeStamp::setToNow(), CeresManager::solve(), CeresManager::update(), and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().