WOLF: test_ceres_manager.cpp File Reference
test_ceres_manager.cpp File Reference
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <memory>
#include <random>
#include <typeinfo>
#include <ctime>
#include <queue>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include "ceres/jet.h"
#include "ceres/ceres.h"
#include "glog/logging.h"
#include "sensor_base.h"
#include "frame_base.h"
#include "state_point.h"
#include "state_complex_angle.h"
#include "state_theta.h"
#include "capture_base.h"
#include "state_base.h"
#include "wolf.h"
#include "ceres_wrapper/complex_angle_parametrization.h"
Data Structures
class ConstraintXBase
class ConstraintSparse< MEASUREMENT_SIZE, BLOCK_0_SIZE, BLOCK_1_SIZE, BLOCK_2_SIZE, BLOCK_3_SIZE, BLOCK_4_SIZE, BLOCK_5_SIZE, BLOCK_6_SIZE, BLOCK_7_SIZE, BLOCK_8_SIZE, BLOCK_9_SIZE >
class ConstraintGPS2D
class Constraint2DOdometry
class Constraint2DOdometryTheta
class CaptureXBase
class WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >
class CeresManager
Ceres manager for WOLF.
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 685 of file test_ceres_manager.cpp.
References WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::addCapture(), CeresManager::addConstraints(), CeresManager::addStateUnits(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getState(), WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::getStateUnitsPtrs(), GPS_FIX, ODOM_2D, CeresManager::solve(), TOP, and WolfManager< StatePositionT, StateOrientationT, StateVelocityT, StateOmegaT >::update().