WOLF: wolf.h File Reference
wolf.h File Reference
General typedefs for the Wolf project.
#include <memory>
#include <list>
#include <map>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Geometry>
#include <eigen3/Eigen/Sparse>
Data Structures
class StatePoint< SIZE >
Namespaces
Eigen
Namespace extending Eigen definitions.
Typedefs
typedef double WolfScalar
scalar type for the Wolf project
typedef Matrix< WolfScalar, 2, 2 > Eigen::Matrix2s
2x2 matrix of real scalar_t type
typedef Matrix< WolfScalar, 3, 3 > Eigen::Matrix3s
3x3 matrix of real scalar_t type
typedef Matrix< WolfScalar, 4, 4 > Eigen::Matrix4s
4x4 matrix of real scalar_t type
typedef Matrix< WolfScalar,
Dynamic, Dynamic > Eigen::MatrixXs
variable size matrix of real scalar_t type
typedef Matrix< WolfScalar, 1, 1 > Eigen::Vector1s
1-vector of real scalar_t type
typedef Matrix< WolfScalar, 2, 1 > Eigen::Vector2s
2-vector of real scalar_t type
typedef Matrix< WolfScalar, 3, 1 > Eigen::Vector3s
3-vector of real scalar_t type
typedef Matrix< WolfScalar, 4, 1 > Eigen::Vector4s
4-vector of real scalar_t type
typedef Matrix< WolfScalar, 6, 1 > Eigen::Vector6s
6-vector of real scalar_t type
typedef Matrix< WolfScalar, 7, 1 > Eigen::Vector7s
7-vector of real scalar_t type
typedef Matrix< WolfScalar,
Dynamic, 1 > Eigen::VectorXs
variable size vector of real scalar_t type
typedef Matrix< WolfScalar, 1, 2 > Eigen::RowVector2s
2-row-vector of real scalar_t type
typedef Matrix< WolfScalar, 1, 3 > Eigen::RowVector3s
3-row-vector of real scalar_t type
typedef Matrix< WolfScalar, 1, 4 > Eigen::RowVector4s
4-row-vector of real scalar_t type
typedef Matrix< WolfScalar,
1, Dynamic > Eigen::RowVectorXs
variable size row-vector of real scalar_t type
typedef Quaternion< WolfScalar > Eigen::Quaternions
Quaternion of real scalar_t type.
typedef AngleAxis< WolfScalar > Eigen::AngleAxiss
Angle-Axis of real scalar_t type.
typedef WolfProblem * WolfProblemPtr
typedef std::list< MapBase * > MapBaseList
typedef MapBaseList::iterator MapBaseIter
typedef std::list< LandmarkBase * > LandmarkBaseList
typedef LandmarkBaseList::iterator LandmarkBaseIter
typedef std::list
< LandmarkCorner2D * > LandmarkCorner2DList
typedef
LandmarkCorner2DList::iterator LandmarkCorner2DIter
typedef std::list< FrameBase * > FrameBaseList
typedef FrameBaseList::iterator FrameBaseIter
typedef std::list< CaptureBase * > CaptureBaseList
typedef CaptureBaseList::iterator CaptureBaseIter
typedef std::list
< CaptureRelative * > CaptureRelativeList
typedef
CaptureRelativeList::iterator CaptureRelativeIter
typedef std::list< FeatureBase * > FeatureBaseList
typedef FeatureBaseList::iterator FeatureBaseIter
typedef std::list
< FeatureCorner2D * > FeatureCorner2DList
typedef
FeatureCorner2DList::iterator FeatureCorner2DIter
typedef std::list
< ConstraintBase * > ConstraintBaseList
typedef
ConstraintBaseList::iterator ConstraintBaseIter
typedef std::map< unsigned int,
TransSensor * > TransSensorMap
typedef TransSensorMap::iterator TransSensorIter
typedef std::list< StateBase * > StateBaseList
typedef StateBaseList::iterator StateBaseIter
typedef StatePoint< 1 > StatePoint1D
typedef StatePoint< 2 > StatePoint2D
typedef StatePoint< 3 > StatePoint3D
typedef StatePoint< 2 > StateVelocity2D
typedef StatePoint< 1 > StateOmega2D
typedef StatePoint< 0 > NoState
Enumerations
enum NodeLocation { TOP, MID, BOTTOM }
Enumeration of node locations at Wolf Tree.
enum FrameType { KEY_FRAME, REGULAR_FRAME }
Enumeration of all possible frames.
enum ConstraintType {
CTR_GPS_FIX_2D, CTR_FIX, CTR_ODOM_2D_COMPLEX_ANGLE, CTR_ODOM_2D_THETA,
CTR_TWIST_2D_THETA, CTR_CORNER_2D_THETA, CTR_CONTAINER
}
Enumeration of all possible constraints.
enum StateType {
ST_POINT_1D, ST_POINT_2D, ST_POINT_3D, ST_THETA,
ST_COMPLEX_ANGLE, ST_QUATERNION
}
Enumeration of all possible state parametrizations.
enum StateStatus { ST_ESTIMATED, ST_FIXED, ST_REMOVED }
Enumeration of all possible state status.
enum SensorType {
ODOM_2D, TWIST_2D, IMU, CAMERA,
GPS_FIX, GPS_RAW, LIDAR, RADAR,
ABSOLUTE_POSE
}
Enumeration of all possible sensor types.
enum LandmarkType { LANDMARK_POINT, LANDMARK_CORNER, LANDMARK_CONTAINER }
Enumeration of all possible landmark types.
enum LandmarkStatus {
LANDMARK_CANDIDATE, LANDMARK_ESTIMATED, LANDMARK_FIXED, LANDMARK_OUT_OF_VIEW,
LANDMARK_OLD
}
enum PendingStatus { NOT_PENDING, ADD_PENDING, UPDATE_PENDING }
Pending status of a node.
Functions
WolfScalar pi2pi (const WolfScalar &angle)
Enumeration of all possible feature types.
Detailed Description
Author
Joan Sola
Definition in file wolf.h.
Typedef Documentation
typedef double WolfScalar
This typedef makes it possible to recompile the whole Wolf project with double, float, or other precisions.
To change the project precision, just edit wolf.h and change the precision of this typedef.
Do NEVER forget to use Wolf scalar definitions when you code!!!
Do NEVER use plain Eigen scalar types!!! (This is redundant with the above. But just to make sure you behave!)
The ONLY exception to this rule is when you need special precision. The ONLY example by now is the time stamp which uses double.
Definition at line 40 of file wolf.h.
typedef WolfProblem* WolfProblemPtr
Definition at line 239 of file wolf.h.
typedef std::list<MapBase*> MapBaseList
Definition at line 254 of file wolf.h.
typedef MapBaseList::iterator MapBaseIter
Definition at line 255 of file wolf.h.
typedef std::list<LandmarkBase*> LandmarkBaseList
Definition at line 258 of file wolf.h.
typedef LandmarkBaseList::iterator LandmarkBaseIter
Definition at line 259 of file wolf.h.
typedef std::list<LandmarkCorner2D*> LandmarkCorner2DList
Definition at line 262 of file wolf.h.
typedef LandmarkCorner2DList::iterator LandmarkCorner2DIter
Definition at line 263 of file wolf.h.
typedef std::list<FrameBase*> FrameBaseList
Definition at line 270 of file wolf.h.
typedef FrameBaseList::iterator FrameBaseIter
Definition at line 271 of file wolf.h.
typedef std::list<CaptureBase*> CaptureBaseList
Definition at line 274 of file wolf.h.
typedef CaptureBaseList::iterator CaptureBaseIter
Definition at line 275 of file wolf.h.
typedef std::list<CaptureRelative*> CaptureRelativeList
Definition at line 278 of file wolf.h.
typedef CaptureRelativeList::iterator CaptureRelativeIter
Definition at line 279 of file wolf.h.
typedef std::list<FeatureBase*> FeatureBaseList
Definition at line 282 of file wolf.h.
typedef FeatureBaseList::iterator FeatureBaseIter
Definition at line 283 of file wolf.h.
typedef std::list<FeatureCorner2D*> FeatureCorner2DList
Definition at line 286 of file wolf.h.
typedef FeatureCorner2DList::iterator FeatureCorner2DIter
Definition at line 287 of file wolf.h.
typedef std::list<ConstraintBase*> ConstraintBaseList
Definition at line 290 of file wolf.h.
typedef ConstraintBaseList::iterator ConstraintBaseIter
Definition at line 291 of file wolf.h.
typedef std::map<unsigned int, TransSensor*> TransSensorMap
Definition at line 298 of file wolf.h.
typedef TransSensorMap::iterator TransSensorIter
Definition at line 299 of file wolf.h.
typedef std::list<StateBase*> StateBaseList
Definition at line 302 of file wolf.h.
typedef StateBaseList::iterator StateBaseIter
Definition at line 303 of file wolf.h.
typedef StatePoint<1> StatePoint1D
Definition at line 305 of file wolf.h.
typedef StatePoint<2> StatePoint2D
Definition at line 306 of file wolf.h.
typedef StatePoint<3> StatePoint3D
Definition at line 307 of file wolf.h.
typedef StatePoint<2> StateVelocity2D
Definition at line 308 of file wolf.h.
typedef StatePoint<1> StateOmega2D
Definition at line 309 of file wolf.h.
typedef StatePoint<0> NoState
Definition at line 310 of file wolf.h.
Enumeration Type Documentation
enum NodeLocation
Enumeration of node locations at Wolf Tree.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
TOP
root node location. This is the one that commands jobs down the tree.
MID
middle nodes. These delegate jobs to lower nodes.
BOTTOM
lowest level nodes. These are the ones that do not delegate any longer and have to do the job.
Definition at line 86 of file wolf.h.
enum FrameType
Enumeration of all possible frames.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
KEY_FRAME
marks a key frame. It will stay in the frames window and play at optimizations.
REGULAR_FRAME
marks a regular frame. It does play at optimizations but it will be discarded from the window once a newer frame arrives.
Definition at line 100 of file wolf.h.
enum ConstraintType
Enumeration of all possible constraints.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
CTR_GPS_FIX_2D
marks a 2D GPS Fix constraint.
CTR_FIX
marks a Fix constraint (for priors).
CTR_ODOM_2D_COMPLEX_ANGLE
marks a 2D Odometry constraint using complex angles.
CTR_ODOM_2D_THETA
marks a 2D Odometry constraint using theta angles.
CTR_TWIST_2D_THETA
marks a 2D Twist constraint using theta angles.
CTR_CORNER_2D_THETA
marks a 2D corner constraint using theta angles.
CTR_CONTAINER
marks a 2D container constraint using theta angles.
Definition at line 113 of file wolf.h.
enum StateType
Enumeration of all possible state parametrizations.
You may add items to this list as needed. Be concise with names, and document your entries. . TODO: Check othe attributes also (
Enumerator
ST_POINT_1D
A 1D point. No parametrization.
ST_POINT_2D
A 2D point. No parametrization.
ST_POINT_3D
A 3D point. No parametrization.
ST_THETA
A 2D orientation represented by a single angle. No parametrization.
ST_COMPLEX_ANGLE
A 2D orientation represented by a complex number.
ST_QUATERNION
A 3D orientation represented by a quaternion.
Definition at line 132 of file wolf.h.
enum StateStatus
Enumeration of all possible state status.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
ST_ESTIMATED
State in estimation (default)
ST_FIXED
State fixed, estimated enough or fixed infrastructure.
ST_REMOVED
Removed state. TODO: is it useful?
Definition at line 149 of file wolf.h.
enum SensorType
Enumeration of all possible sensor types.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
ODOM_2D
Odometry measurement from encoders: displacement and rotation.
TWIST_2D
Twist measurement form encoders or motion command: lineal and angular velocities.
IMU
Inertial measurement unit with 3 acceleros, 3 gyros.
CAMERA
Regular pinhole camera.
GPS_FIX
GPS fix calculated from a GPS receiver.
GPS_RAW
GPS pseudo ranges, doppler and satellite ephemerides.
LIDAR
Laser Range Finder, 2D.
RADAR
Radar.
ABSOLUTE_POSE
Full absolute pose (XYZ+quaternion)
Definition at line 163 of file wolf.h.
enum LandmarkType
Enumeration of all possible landmark types.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
LANDMARK_POINT
A point landmark, either 3D or 2D.
LANDMARK_CORNER
A corner landmark (2D)
LANDMARK_CONTAINER
A container landmark (2D)
Definition at line 183 of file wolf.h.
enum LandmarkStatus
Enumerator
LANDMARK_CANDIDATE
A landmark, just created. Association with it allowed, but not yet stablish an actual constraint for the solver.
LANDMARK_ESTIMATED
A landmark being estimated. Association with it allowed, stablishing actual constraints for the solver where both vehicle and landmark states are being estimated.
LANDMARK_FIXED
A landmark estimated. Association with it allowed, stablishing actual constraints for the solver, but its value remains static, no longer optimized.
LANDMARK_OUT_OF_VIEW
A landmark out of the field of view. Association with it is not allowed, so does not pose constraints for the solver.
LANDMARK_OLD
An old landmark. Association with it not allowed, but old constraints can still be taken into account by the solver.
Definition at line 190 of file wolf.h.
enum PendingStatus
Enumeration of all possible pending status of a node.
You may add items to this list as needed. Be concise with names, and document your entries.
Enumerator
NOT_PENDING
A point landmark, either 3D or 2D.
ADD_PENDING
A corner landmark (2D)
UPDATE_PENDING
A container landmark.
Definition at line 206 of file wolf.h.
Function Documentation
WolfScalar pi2pi (const WolfScalar & angle) inline
Enumeration of all possible feature types.
You may add items to this list as needed. Be concise with names, and document your entries.
Definition at line 334 of file wolf.h.
Referenced by CaptureLaser2D::computeExpectedFeature(), CaptureLaser2D::computeSquaredMahalanobisDistances(), CaptureLaser2D::establishConstraintsMHTree(), and CaptureLaser2D::fitNewContainer().